.title	DSRMSG.MSG - message text file for DSR
!
!			      IDENT = 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!++
! FACILITY:
!   Digital Standard Runoff
!
! ABSTRACT:
!
!	VMS MESSAGE utility input file for error message handling.
!
! ENVIRONMENT:
!   MESSAGE utility within VMS
!
! AUTHOR:  Ray Marshall,   CREATION DATE:  9-October-1981
!
! MODIFIED BY:
!
!	003	REM00003	Ray Marshall	30-November-1981
!		Added new TMF error message for support of new footnote
!		  processing done by Rich Friday.
!
!	002	REM00002	Ray Marshall	16-October-1981
!		Changed MRC & NIC from informational to warning.
!		Added AAA so that RUNOFF.BLI can report any error in the
!		  total number of messages.  Notice that it's a FATAL!
!
!--

    .FACILITY	RUNOFF,150/PREFIX=RNF/SYSTEM
    .BASE	0
    .SEVERITY	SUCCESS
	AAA	/FATAL		<!AS>/fao_count=1
	BAK	/INFORMATIONAL	<!_!AS>/fao_count=1
	BMS	/ERROR		<!AS>/fao_count=1
	BVN	/ERROR		<!AS>/fao_count=1
	CEM	/FATAL		<!AS>/fao_count=1
	CJL	/WARNING	<!AS>/fao_count=1
	CNF	/WARNING	<!AS>/fao_count=1
	CNS	/WARNING	<!AS>/fao_count=1
	COF	/WARNING	<!AS>/fao_count=1
	COI	/FATAL		<!AS>/fao_count=1
	COO	/FATAL		<!AS>/fao_count=1
	COR	/WARNING	<!AS>/fao_count=1
	COT	/FATAL		<!AS>/fao_count=1
	COX	/FATAL		<!AS>/fao_count=1
	CRF	/WARNING	<!AS>/fao_count=1
	CRP	/FATAL		<!AS>/fao_count=1
	CWF	/WARNING	<!AS>/fao_count=1
	DNS	/WARNING	<!AS>/fao_count=1
	DVN	/WARNING	<!AS>/fao_count=1
	DWF	/WARNING	<!AS>/fao_count=1
	EFD	/WARNING	<!AS>/fao_count=1
	ELD	/WARNING	<!AS>/fao_count=1
	ERD	/INFORMATIONAL	<!AS>/fao_count=1
	ERR	/INFORMATIONAL	<!AS>/fao_count=1
	EVL	/WARNING	<!AS>/fao_count=1
	FAB	/WARNING	<!AS>/fao_count=1
	FEL	/WARNING	<!AS>/fao_count=1
	FNA	/WARNING	<!AS>/fao_count=1
	FWF	/WARNING	<!AS>/fao_count=1
	GFC	/INFORMATIONAL	<!AS>/fao_count=1
	IBO	/WARNING	<!AS>/fao_count=1
	IFT	/WARNING	<!AS>/fao_count=1
	IIF	/WARNING	<!AS>/fao_count=1
	ILC	/WARNING	<!AS>/fao_count=1
	ILE	/WARNING	<!AS>/fao_count=1
	INI	/WARNING	<!AS>/fao_count=1
	INM	/WARNING	<!AS>/fao_count=1
	ITC	/WARNING	<!AS>/fao_count=1
	ITD	/WARNING	<!AS>/fao_count=1
	ITS			<!AS>/fao_count=1
	IVS	/FATAL		<!AS>/fao_count=1
	JEC	/WARNING	<!AS>/fao_count=1
	LDE	/WARNING	<!AS>/fao_count=1
	LOC	/INFORMATIONAL	<!_!AS>/fao_count=1
	LOM	/FATAL		<!AS>/fao_count=1
	LTC	/WARNING	<!AS>/fao_count=1
	MEI	/WARNING	<!AS>/fao_count=1
	MFN	/WARNING	<!AS>/fao_count=1
	MFS	/WARNING	<!AS>/fao_count=1
	MNL	/WARNING	<!AS>/fao_count=1
	MD1			<!AS>/fao_count=1
	MQS	/WARNING	<!AS>/fao_count=1
	MRC	/WARNING	<!AS>/fao_count=1
	MRG	/WARNING	<!AS>/fao_count=1
	NFS			<!AS>/fao_count=1
	NIA	/WARNING	<!AS>/fao_count=1
	NIC	/WARNING	<!AS>/fao_count=1
	NNA			<!AS>/fao_count=1
	NED	/INFORMATIONAL	<!AS>/fao_count=1
	NSF	/WARNING	<!AS>/fao_count=1
	NTD	/WARNING	<!AS>/fao_count=1
	PC1	/INFORMATIONAL	<!AS>/fao_count=1
	PCT	/INFORMATIONAL	<!AS>/fao_count=1
	PWF	/WARNING	<!AS>/fao_count=1
	QST	/WARNING	<!AS>/fao_count=1
	RTL	/WARNING	<!AS>/fao_count=1
	SKC	/WARNING	<!AS>/fao_count=1
	SPO			<!AS>/fao_count=1
	SSR	/WARNING	<!AS>/fao_count=1
	STD	/WARNING	<!AS>/fao_count=1
	STR	/INFORMATIONAL	<!_!AS>/fao_count=1
	TAR	/WARNING	<!AS>/fao_count=1
	TFE	/WARNING	<!AS>/fao_count=1
	TMF	/WARNING	<!AS>/fao_count=1
	TMP	/FATAL		<!AS>/fao_count=1
	TMT	/WARNING	<!AS>/fao_count=1
	TMV	/FATAL		<!AS>/fao_count=1
	TTL	/WARNING	<!AS>/fao_count=1
	UDS	/WARNING	<!AS>/fao_count=1
	UME	/WARNING	<!AS>/fao_count=1
	URE	/WARNING	<!AS>/fao_count=1
	URR	/WARNING	<!AS>/fao_count=1
	VVZ			<!AS>/fao_count=1
	XFL	/WARNING	<!AS>/fao_count=1
    .END
