	.TITLE	SDAMSG	System Dump Analyzer Messages
!
!	.IDENT	V03-001
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
!++
!
!	FACILITY
!
!		System Dump Analyzer
!
!	ABSTRACT
!
!		System Dump Analyzer Message File Definitions
!
!	ENVIRONMENT
!
!		Native Mode, User Mode
!
!	AUTHOR
!		Mike Rhodes	June 1981
!
!	MODIFIED BY
!
!	V03-001	KEK0027		K. E. Kinnear		1-Mar-1982
!		Add messages for obscure errors from SHOW PROC/RMS.
!
!--

	.FACILITY	SDA,1/PREFIX=MSG$_
!
!	Begin Symbol Definitions...
!

	.SEVERITY	SUCCESS

	SUCCESS		<>	!NOTE:  This is an internally used signal
				!	and does NOT have a printable message.

	.SEVERITY	WARNING

	SHORTDUMP	<the dump only contains !UL out of !UL pages of physical memory>/FAO=2
	NOREQ		<symbol "!AC" not found in system symbol table>/FAO=1
	BADGSD		<unknown type of GSD entry: !UB>/FAO=1
	NOREAD		<unable to access location !XL>/FAO=1
	INSKIPPED	<unreasonable instruction stream - !UL bytes skipped>/FAO=1
	SYNTAX		<error parsing '!AS'>
	NOIMGRMS	<no image RMS structures>
!
!	NOTE:	The following WARNING messages are internally signalled
!		conditions but, they DO NOT have printable messages!
!
	BACKUP		<>	!Used to back up 1 command level.
	EOF		<>	!Internal End Of File signal.
	EXITCMD		<>	!Used to abort command and erase screen.

	.SEVERITY	ERROR

	NOTVALID	<information not in physical memory>
	DUMPEMPTY	<dump file contains no valid dump>
	BADSYM		<unknown symbol "!AS">/FAO=1
	NOTINPHYS	<!XL : not in physical memory>/FAO=1
	BADPROC		<no such process>
	INVBLKTYP	<invalid block type in specified block>
	NOSYMBOLS	<no "!AS" symbols found to format this block>/FAO=1
	NOTRES		<process swapped out>
	SPTNOTFND	<system page table not found in dump file>
	NOINSTRAN	<cannot translate instruction>
	RMSTERM		<structure display terminated prematurely>

	.SEVERITY	FATAL

	OPENIN		<error opening !AS as input>/FAO=1
!
!	End Symbol Definitions...and this message file!
!
	.END
