	.title	Phone_Messages Messages for the PHONE Facility

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

	.facility	phone,166/prefix=phn$_/system

	.severity	success
ok		"Normal successful completion."

	.severity	informational
answered	"That person has answered your call."
busycall	"That person's phone is busy right now.  Try again later."
cancall		"That person just cancelled the call."
cantreach	"That person cannot be reached at the moment.  Try again."
confcall	"!AS has set up a conference call with !AS."/fao_count=2
dead		"That person's phone just went dead.  Try again."
decnetlink	"Establishing DECnet link..."
dircan		"Press any key to cancel the directory listing and continue."
facscan		"Press any key to cancel the facsimile operation and continue."
helpcan		"Press any key to cancel the help information and continue."
hungup		"!AS just hung up the phone."/fao_count=1
justrang	"!32<Ringing !AS...!>(Press any key to cancel call and continue.)"/fao_count=1
loggedoff	"That person just now logged off the system."
rejected	"That person has rejected your call at this time."
ring		"!AS!AS is phoning you !#<on !AS!>     (!8%T)"/fao_count=5
sendingmail	"Sending mail..."

	.severity	warning
rejectjunk	<Extraneous text "!AS" ignored on command line.>/fao_count=1

	.severity	error
badcmd		"Invalid command entered.  Try again."
badhelp		"Invalid help keywords specified.  Try HELP."
badmailcmd	<Try again, using the following format:  MAIL addressee "message">
badsmb		"SYSTEM ERROR:  Invalid steering message."
badspec		"Invalid specification of node or person.  Try again."
helpmissing	"Help library is missing.  Please inform your system manager."
ivredunans	"By answering the phone you will create a redundant call."
ivreduncall	"You cannot place redundant calls."
linkerror	"An error has occurred in transmitting to !AS."/fao_count=1
needuser	"You did not specify a person to call.  Try again."
nocall		"No one is calling you now."
noholds		"No one is on hold now."
noports		"There is no room on the screen for another person."
nopriv		"You do not have the privilege to place that call."
noproc		"No one with that name is available at this time."
notconv		"You are not conversing with anyone now."
onlynode	"Only a node name is allowed in a DIRECTORY command."
phonebusy	"Your phone is ringing; you cannot place an outgoing call."
remoteerror	"An error has occurred in remote communication."
targterm	"That person's terminal cannot be used as a telephone."
unplugged	"That person's phone is unplugged (/NOBROADCAST)."

	.severity	fatal
badterm		"you cannot use this type of terminal as a telephone"

	.end
