!---
!
!	Error messages for the MONITOR utility
!
! IDENT V03-001
!
!---

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:  VAX/VMS MONITOR Utility
!
! ABSTRACT:
!
!	These are the error messages used by the MONITOR utility.
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, user mode utility,
!	operates in EXEC and KERNEL modes to collect
!	data from protected data bases.
!	Operates at both AST and non-AST level.
!
!	This module contains only non-executable message
!	definitions.
!
! AUTHOR:  Tom Cafarella, Aug, 1981.
!
! MODIFIED BY:
!
!	V03-001	TLC1011		Thomas L. Cafarella	29-Mar-1982	20:00
!		Move system service names for SSERROR msg to static storage.
!
!----

.FACILITY	MONITOR,206 /SYSTEM /PREFIX=MNR$_

.SEVERITY	WARNING

CLASNP		<some requested class(es) not present in /INPUT file>

.SEVERITY	ERROR

ERRINPFIL	<error processing /INPUT file>
ERRRECFIL	<error processing /RECORD file>
UNEXPERR	<unexpected error>
SSERROR		<!AC system service error>/FAO_COUNT=1
COLLERR		<error during data collection>
DISPERR		<error during display or summary output>
NOCLASS		<none of the requested classes present in /INPUT file>
CLASDISAB	<class disabled>
SQUALERR	<more than one statistic qualifier specified for !AC class>/FAO=1
PDQUALERR	<more than one display type qualifier specified for !AC class>/FAO=1
QUALINV		</!AS qualifier not valid for !AC class>/FAO_COUNT=2
BEGRAN		<requested beginning time beyond range of /INPUT file>
PREMEOF		<premature end-of-file on /INPUT file>
INVINPFIL	</INPUT file is not a valid MONITOR recording file>
UNSTLEV		</INPUT file has an unsupported MONITOR file structure level>
CLASMISS	<requested class record missing from input file>
INVBTIMSP	<invalid /BEGINNING time specification>
INVETIMSP	<invalid /ENDING time specification>
INVINTSP	<invalid /INTERVAL specification>
INVVIEWSP	<invalid /VIEWING_TIME specification>
INVCLSNM	<class-name "!AS" is invalid or not uniquely identified>/FAO_COUNT=1
BEGNLEND	<beginning time not earlier than ending time>
NOOUTPUT	<no output selected ... specify /DISPLAY, /RECORD or /SUMMARY>

.SEVERITY	INFORMATIONAL

HIB		<hibernating until requested beginning time....>

.SEVERITY	FATAL


.END
