! MPERRMSG.MSG - error messages for multi-processing code
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  MP - multi-processing code
!
! ABSTRACT:
!
!	This file contains the MSG source for MP messages
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  Kathleen D. Morse	 CREATION DATE:  12-Apr-1982
!
! MODIFICATION HISTORY:
!

!
! Multi-processing error messages
!
	.FACILITY	MP,239 /SYSTEM /PREFIX=ERR$_


	.SEVERITY	FATAL

	SHMDBLUSE	<MA780 cannot be used for main memory and system interconnect>
	LCLMEMUSED	<local memory usage prevents executing as multi-processor system>
	MA780_REQ	<multi-processor system must be booted with MA780 as main memory>


	.END
