	.TITLE	RTMSG	MESSAGE FILE FOR RTPAD

!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!++
! FACILITY: REMOTE TERMINAL SUPPORT
!
! ABSTRACT:
!	
!	MESSAGE FILE
!
!
!		
!
! AUTHOR: W M CARDOZA,	 CREATION DATE: 20-AUG-79
!
! MODIFIED BY:
!
!	V03-003	WMC0033		Wayne Cardoza		13-Jan-1982
!		Add control-y request message.
!
!	V03-002 WMC0009		Wayne Cardoza		11-Nov-1981
!		Out of band AST message
!
!	V03-001	WMC0001		Wayne M. Cardoza,	23-June-1980
!		Add link mailbox message
!
!**
!
!--
	.PAGE

	.FACILITY	REM,510/SYSTEM

	.SEVERITY	FATAL
	NOTERM	<command device is not a terminal>
	NETDIS	<disconnect on remote terminal DECnet link>
	NETERR	<DECnet channel error on remote terminal link>
	NOPROT	<protocol not supported on remote node>
	NETMBX	<link mailbox code !XW>/FAO=1
	BADOUTBAND <invalid out of band AST specification>

	.SEVERITY	INFORMATIONAL
	REMOTE	<connection established to remote node !AS>/FAO=1
	ACSIGN	<access control string ignored>
	CNTRLY	<Are you repeating ^Y to abort the remote session on node !AS? >/FAO=1

	.SEVERITY	SUCCESS
	END	<control returned to node !AS>/FAO=1

	.END
