!---
!
!	Error messages for the SET utility
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:  SET utility
!
! ABSTRACT:
!
!	These are the error messages used by the SET command
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, privileged user mode utility,
!	operates at non-AST level.
!
! AUTHOR:  Greg Robert,  June, 1981
!
! MODIFIED BY:
!
!	V03-004	GAS0046		Gerry Smith		10-Feb-1982
!		Add SET$_SYSNOTUPD, to show that the UCB and VCB were
!		not able to be updated.
!
!	V03-003	GAS0045		Gerry Smith		 9-Feb-1982
!		Add disk name to HB$_READ and HB$_WRITE
!
!	V03-002 GAS0026		Gerry Smith		18-Dec-1981
!		Use shared message file, and lower fatal messages to
!		simple error messages.
!
!	V03-001	GAS0018		Gerry Smith		16-Nov-1981
!		Add messages for SET FILE, SET DIRECTORY, and SET VOLUME.
!
!----

	.FACILITY	SET,119 /SYSTEM

!
! Fatal errors
!

!
! Non-fatal errors
!
.SEVERITY ERROR
	CLOSEERR	<error closing !AS> /FAO=1
	ENTERR		<error entering !AS as !AS> /FAO=2
	HBREAD		<error reading home block of !AS> /FAO=1
	HBWRITE		<error writing home block of !AS> /FAO=1
	NOHOME		<volume does not contain a valid home block>
	NONODE		<node specification not allowed>
	NOTDIR		<file is not a directory>
	NOTODS2		<!AS qualifier invalid on Files-11 Structure Level 1 disk> /FAO=1
	OPENDIR		<error opening parent directory for !AS> /FAO=1
	OPERREQ		<OPER privilege required for /ACCESSED qualifier>
	PRONOTCHG	<Protection on !AS not changed> /FAO=1 
	READERR		<error reading !AS> /FAO=1
	REMERR		<error removing !AS> /FAO=1
	WRITEERR	<error modifying !AS> /FAO=1
!
! Warning messages
!
.SEVERITY WARNING
	BUFBLKREQ	<Buffer count or block count required> 
	SYSNOTUPD	<I/O database not updated for volume !AS> /FAO=1

!
! Informational messages
!
.SEVERITY INFORMATIONAL
	ENTERED		<!AS entered as !AS> /FAO=2
	MODIFIED	<!AS modified> /FAO=1
	REMOVED		<!AS removed> /FAO=1
.END
