	.TITLE	LIB_MESSAGES
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! Return status codes for library command
!
! Author: Benn Schreiber, June 1979
!
! Modified by:
!
!	V02-006		RPG44341	Bob Grosso	02-Mar-1982
!		Correct foa count on message toomnyendr and change 
!		the foa directive from a descriptor string to a counted
!		ASCII string for several messages that print the macro name.
!
!	V02-005		RPG005		Bob Grosso	17-Dec-1981
!		Add update history message.
!
!	V02-004		RPG002		Bob Grosso	17-Jul-1981
!		Add lib$_brknlib.
!
!	V02-003		RPG001		Bob Grosso	25-Jun-1981
!		Add warning message, lib$_dupmod.
!
!	V02-002	BLS0029		Benn Schreiber	23-Dec-1980
!		Convert to .MSG file and add new message for illegal shareable
!		image format.
!
!	V001	TMH0001		Tim Halvorsen	11-Mar-1980
!		Remove LIB$_NORMAL (conflicts with RTL)
!

	.FACILITY	LIBRAR,134/SYSTEM/PREFIX=LIB$_

	.SEVERITY	SUCCESS

	INSERTED/FAO_COUNT=2	<module !AS inserted in !AS>
	DELETED	/FAO_COUNT=2	<module !AS deleted from !AS>
	REPLACED/FAO_COUNT=2	<module !AS replaced in !AS>
	REMOVED	/FAO_COUNT=2	<symbol !AS removed from !AS>
	EXTRACTED/FAO_COUNT=2	<module !AS extracted from !AS>

	.SEVERITY	WARNING

	DIFTYP/FAO_COUNT=3	<expected !AC library !AS to be !AC>
	COMCOD/FAO_COUNT=3	<compilation !AS in module !AC file !AS>
	ENDWRNGMAC/FAO_COUNT=3	<.ENDM !AS does not end macro !AS in !AS>
	EXTRAENDM/FAO_COUNT=1	<extraneous .ENDM in !AS>
	NOHLPTXT/FAO_COUNT=1	<no level 1 help text found in !AS>
	NOMACFOUND/FAO_COUNT=1	<no .MACRO found in !AS>
	NOMTCHENDM/FAO_COUNT=2	<no matching .ENDM for macro !AC in !AS>
	NOMTCHENDR/FAO_COUNT=3	<!UL missing .ENDR!%S for macro !AC in !AS>
	NOSYMBOLS/FAO_COUNT=1	<no global symbol table found in !AS>
	TOOMNYENDR/FAO_COUNT=2	<too many .ENDR in macro !AC in !AS>
	NOMTCHFOU/FAO_COUNT=1	<no matches found for !AS>
	DUPMODULE/FAO_COUNT=3	<module !AC from file !AS already in !AS>
	BRKNLIB/FAO_COUNT=1	<library !AS not properly closed, compress or rebuild>
	HISTERR/FAO_COUNT=1	<error accessing library update history in !AS>

	.SEVERITY	ERROR

	DELKEYERR/FAO_COUNT=2	<error deleting !AS from !AS>
	DELDATERR/FAO_COUNT=1	<error deleting data from !AS>
	DUPGLOBAL/FAO_COUNT=3	<global symbol !AS from file !AS already in library !AS>
	DUPMOD/FAO_COUNT=3	<module !AC from file !AS already in !AS>
	FAOFAIL/FAO_COUNT=0	<FAO system service failure>
	GSDTYP/FAO_COUNT=3	<module !AC file !AS has an illegal GSD record (type !UB)>
	ILLKEYLVL/FAO_COUNT=4	<illegal key level !UL key !AS in !AS expected !UL>
	INDEXERR/FAO_COUNT=1	<index error in !AS>
	INSERTERR/FAO_COUNT=2	<error inserting !AS in !AS>
	KEYNAMLNG/FAO_COUNT=2	<key !AS name length illegal in !AS>
	LOOKUPERR/FAO_COUNT=2	<error looking up !AS in !AS>
	MACNAMLNG/FAO_COUNT=2	<macro !AS name is too long in !AS>
	MODNAMLNG/FAO_COUNT=3	<illegal module name (!AC) of !UB characters in !AS>
	NESTLEVEL/FAO_COUNT=2	<nesting level exceeded in macro !AC file !AS>
	NOEOM/FAO_COUNT=2	<module !AC is not terminated with EOM record in !AS>
	NOMODNAM/FAO_COUNT=1	<no module name found for !AS>
	NOTOBJLIB/FAO_COUNT=1	<library !AS is not an object library>
	NOTSHRIMG/FAO_COUNT=1	<file !AS is not a shareable image>
	RECLNG/FAO_COUNT=3	<illegal record length (!UB) in module !AC in !AS>
	RECTYP/FAO_COUNT=3	<illegal record type (!UB) in module !AC in !AS>
	REPLACERR/FAO_COUNT=2	<error replacing !AS in !AS>
	SEQNCE/FAO_COUNT=2	<illegal record sequence in module !AC in !AS>
	SPNAMLNG/FAO_COUNT=4	<PSECT !AC module !AC file !AS has illegal length (!UB.)>
	STRLVL/FAO_COUNT=3	<object structure level !UB unsupported in module !AC in !AS>
	SYMNAMLNG/FAO_COUNT=4	<symbol !AC module !AC file !AS has illegal length (!UB)>

	.SEVERITY	INFORMATIONAL

	CNVRTING/FAO_COUNT=1	<!AS is a copy of !AS>

	.SEVERITY	SEVERE

	MHDERR/FAO_COUNT=2	<module header error for !AS in !AS>
	INITERR/FAO_COUNT=1	<error initializing !AS>

	.END
