.TITLE	NCPERRMSG Error Messages

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:	Network Control Program (NCP)
!
! ABSTRACT:
!
!	All facility specific error messages
!
! ENVIRONMENT:	VAX/VMS Operating System
!
! AUTHOR:	Darrell Duffy	, CREATION DATE: 6-March-1980
!
! MODIFIED BY:
!
!	V004	TMH0004		Tim Halvorsen	03-Feb-1982
!		Fix list of required privileges.
!
!	V003	TMH0003		Tim Halvorsen	11-Jan-1982
!		Add message for V2.0 NML conversion error.
!
!	V002	TMH0002		Tim Halvorsen	21-Dec-1981
!		Add message indicating SHOW response has parameters
!		out of ascending order.
!
!	V001	TMH0001		Tim Halvorsen	11-Aug-1981
!		Remove comma from NMLRSP message, and add another
!		FAO argument which can be used to supply the comma
!		if its really needed.  This is to avoid having the
!		comma appear if there is no detail following.
!--

.FACILITY NCP,504/SYSTEM

.SEVERITY ERROR

!
!	Each of the following messages may be generated by NCP.
!	A brief description follows each message giving the reason for
!	the failure and its possible remedy if appropriate.
!
!	Two concepts are common to many messages.  Context refers to the
!	text surrounding the invalid portion of a command.  This context
!	is printed as up to 30 characters before and after the invalid
!	token which is enclosed in backslashes (\).
!	Due to the nature and complexity of the parsing the backslashes
!	may not always surround the token which is invalid. The token will
!	always be adjacent to the backslashes however.
!
!	Secondary messages are printed to give more information about a
!	failure.  Sometimes the secondary messages are from NCP itself.
!	More often however the messages are system or RMS messages which
!	detail the failure.
!

!
AMBCMD/FAO=6	"ambiguous command!/!AD\!AD\!AD"
!
!		A keyword in the command has not been specified with enough
!		characters to distinguish it from another keyword acceptable
!		in this context. The context is printed.
!
CMDCAN/FAO=0	"command canceled"
!
!		A CTRL/Z was typed in response to a prompt.  This cancels
!		the current command and returns to the NCP> prompt.
!
CMDERR/FAO=0	"I/O error reading commands"
!
!		An error condition was returned from RMS while reading
!		commands from SYS$INPUT.  The RMS error is printed as
!		additional information.
!
INVCMD/FAO=6	"unrecognized command!/!AD\!AD\!AD"
!
!		The command verb specified is not valid. The context
!		of the error is printed.


!
INVKEY/FAO=0	"unrecognized keyword"
!
!		A keyword is not recognized.  This is an error from a prompt
!		and the context should be clear.
!
INVVAL/FAO=0	"unrecognized value"
!
!		A value to a prompt was not valid.  The context should be
!		clear from a previous error message or from the prompt.
!
NOTDONE/FAO=0	"command not complete"
!
!		Not enough of the command has been entered to tell its
!		intent and prompting cannot be done since the commands are
!		coming from a command procedure.  Prompting is not valid
!		in command procedures.
!
PRMLEN/FAO=6	"parameter too long!/!AD\!AD\!AD"
!
!		A parameter string or value has too many characters.
!		The context is printed.
!
PRMRNG/FAO=6	"parameter value out of range!/!AD\!AD\!AD"
!
!		A numeric parameter value is out of the valid range.
!		The context is printed.
!
SYNTAX/FAO=6	"command syntax error!/!AD\!AD\!AD"
!
!		A token in the command could not be parsed.
!		The context is printed.
!
INVEVE/FAO=6	"invalid event range!/!AD\!AD\!AD"
!
!		The range of event types is not valid. The context is printed.
!
REPEAT/FAO=6	"parameter repeated!/!AD\!AD\!AD"
!
!		A parameter can appear only once in a command.  The context
!		is printed.
!
NOPARM/FAO=0	"no parameters"
!
!		No parameters were specifed for a command.  Probably no
!		parameters were selected in a sequence of prompts.


!
CONNEC/FAO=0	"unable to connect to listener"
!
!		NCP is unable to connect to NML to perform network operations.
!		The secondary reason is printed with this error.
!		The network may not be configured correctly or all the files
!		may not be present.
!
UNSVRS/FAO=0	"version of listener on executor is not supported"
!
!		NML did not respond with a valid version.  The executor
!		cannot be accessed by network management.
!
NETIO/FAO=0	"network communication error"
!
!		A network error of some type occured.  The secondary message
!		gives more detail.
!
DISCON/FAO=0	"error disconnecting link to listener"
!
!		Some error occured while disconnecting the link to NML.
!		The secondary message explains in more detail.
!
INVACC/FAO=0	"invalid access control specified for executor"
!
!		Invalid or conflicting access control was specified for
!		connecting to an executor.  Use standard VMS access control or
!		DNA standard access control, not both or a mixture.
!
INVRSP/FAO=0	"invalid management response"
!
!		NCP could not recognize the form of the response from the
!		NML or the response was inappropriate.
!
BADMSG/FAO=1	"invalid management message, !AC"
!
!		The form of the data from NML could not be correctly parsed.
!		A reason is specified at the end of the message.


!
LOGIC/FAO=1	"logic error in NCP, !AC"
!
!		A logic error occurred in NCP.  A program bug caused an
!		inconsistancy.  The circumstances and message should be
!		reported in an SPR.
!
SHOFIL/FAO=0	"unable to open output for show or list"
!
!		An error was returned from RMS when attempting to open the
!		output file for the show or list commands.   The secondary
!		RMS error is printed as well.
!
SHOIO/FAO=0	"error writing output file for show or list"
!
!		An error was returned from RMS when attempting to write to
!		the output file for show or list.  The RMS error is printed
!		as well.
!
PH2INV/FAO=0	"function is invalid for phase II executor node"
!
!		NCP command cannot be performed by a phase II executor node.
!		Either the command, an option or a parameter was invalid.
!		Consult the documentation for the functions which are valid
!		with a phase II executor node.
!
ACCLIN/FAO=0	"access control specified with loop line"
!
!		Access control with a loop command may only be specified
!		with a loop node or loop executor command.  Not with a loop
!		line command.
!
HLPINI/FAO=0	"error initializing librarian"
!
!		An error occurred when initializing the librarian to open the
!		help library file.  The secondary status is reported.
!
HLPLIB/FAO=0	"unable to open help library"
!
!		An error occurred when opening the help library.
!		The secondary status is reported.
!
HELP/FAO=0	"error writing help text"
!
!		An error occurred when writing the help text.
!		The secondary status is reported.
!
HLPOUT/FAO=0	"too many subtopics for help"
!
!		Too many subtopics were specified for help.  Eight are
!		permitted.
!
NONET/FAO=0	"no net device, driver not loaded"
!
!		No net device is available.  The NETDRIVER has not been
!		loaded with the SYSGEN program.
!
MOUCHK/FAO=0	"unable to tell if NETACP is mounted"
!
!		An error was returned when NCP was trying to determine
!		if NETACP is mounted.  Remove the NETACP and restart
!		the network after correcting the problem.
!
CREACP/FAO=0	"error creating process to run NETACP"
!
!		Create process system service returned the associated
!		error when creating the NETACP process.
!
ACPMOU/FAO=0	"error mounting network,  NETACP failed to start properly"
!
!		After a 30 second wait, the NET device was still not mounted,
!		or the associated error was returned from the ASSIGN system
!		service.
!
CRENML/FAO=0	"error creating process to run NML"
!
!		Create process system service returned the associated error
!		when creating the NML process.  Try restarting NML manually
!		with the command :  RUN /UIC=[1,4] SYS$SYSTEM:NML.  The only
!		other recourse is to use the NCP DISMOUNT NETACP command
!		to stop NETACP and when NETACP has stopped, run NCP
!		again to start the network when the condition which caused
!		NML to fail to start is corrected.
!
ACPDSM/FAO=0	"error attempting to shutdown NETACP"
!
!		An error occurred while attempting to perform the
!		DISMOUNT NETACP function.  If OPER privilege is present
!		then the only recourse is to perform @SYS$SYSTEM:SHUTDOWN
!		and reboot the system.
!
INSFPRV/FAO=0	"privileges required are: DETACH,CMKRNL or SETPRV"
!
!		These privileges are required to start the network. The
!		process using NCP to start the network the first time must
!		have these privileges.
!
V2COMP		"parameter not applicable on V2.0 DECnet executor node"
!
!		A given request could not be converted into V2.0 NICE
!		message when connected to a V2.0 NML.
!

.SEVERITY INFORMATIONAL

NMLRSP/FAO=5	"listener response - !AC!AC !AC!/!AC!/!AC"
!
!		Standard form for an error response from NML.  The first line
!		contains an error reason and detail.  The next line contains
!		An entity code if one is present in the response and the next
!		line contains additional error text if any is present in the
!		response.
!

PARMORDER	"listener error - parameters not returned in ascending order"
!
!		This error indicates that the network management listener
!		has returned a SHOW response with the parameters not in
!		ascending order, as required by DNA.  This is only an
!		informational message - the final display will be produced
!		regardless of the order, since this implementation of NCP
!		does not need them to be in order.



.END				!End of module
