	.TITLE	INS_MESSAGE
! 
! INSTALL UTILITY MESSAGES 
! 
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!  AUTHOR:	Bob Grosso
!
!  DATE:	11-Nov-1981
!
!  MODIFIED BY:
!
!	V03-003	RPG0003		Bob Grosso		11-Jan-1982
!		Add message to inform how to obtain HELP and replace
!		KFINOTFND message with NOVER.
!
!	V03-002	RPG0002		Bob Grosso		08-Dec-1981
!		Support user privilege checking.
!		Change filopnerr to shared message OPENIN.
!
!	V03-001	RPG0001		Bob Grosso		18-Nov-1981
!		Add messages for errors with privileges.
!
! 
	.FACILITY	INS,123 /SYSTEM

	.SEVERITY	INFORMATION

	HELP			<Enter /HELP for INSTALL help>

	.SEVERITY	WARNING

	GBLSECFAIL		<failed to create global section>
	HDRNOTRES		<unable to make image header resident>


	.SEVERITY	ERROR

	CONFQUAL		<conflicting qualifiers>
	EXIST			<name already in use>
	INVPRVNAM/FAO_COUNT=1	<!AS is not a valid privilege>
	IVQUAL			<invalid qualifier>
	KFIFULL			<no room to add a new known file list>
	NOCMK			<operation requires CMKRNL privilege>
	NOKFIFND		<no known file entry found>
	NOVER/FAO_COUNT=1	<error obtaining file version for !AS>
	PRVNOTUNQ/FAO_COUNT=1	<privilege name !AS is not unique>

	.END
