!++
!
!	Error messages for SEARCH
!
! IDENT V02-005
!
!--

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:  SEARCH
!
! ABSTRACT:
!
!	This utility program searchs a file or files for a specified
!	string and lists all occurances.
!
! ENVIRONMENT:  
!
!	VAX/VMS operating system, unprivileged user mode utility,
!	operates at non-AST level.
!
! REVISION HISTORY:
!	V02-005	CWH0005		CW Hobbs		25-Jan-1982
!		Improve insufficient virtual memory message.
!
!	V02-004	CWH0004		CW Hobbs		18-Jan-1982
!		Use shared messages for several codes.
!
!	V02-002	CWH0003		CW Hobbs		31-Aug-1981
!		Add messages for V3 SEARCH changes.
!
!	V02-001	CNH0032		Chris Hume		16-Apr-1980
!		Added windowing and CLI callback.
!
!--

.FACILITY	SEARCH,1 /PREFIX=SRH$_

.SEVERITY	FATAL

BADEXCL		<directory or device not allowed in /EXCLUDE=!AS>/FAO=1
BADEXCLNAM	<invalid filename in /EXCLUDE=!AS>/FAO=1
BADFORM		<invalid option for /FORMAT>
BADMATCH	<invalid option for /MATCH>
NOSTRING	<no search string specified>
RFAERR		<RMS error using RFA access:  RFA = !UL, !UL>/FAO=2
WDW_MAXPREV	<too many previous records in window>
WDW_MAXPRM	<too many window parameters>

.SEVERITY	ERROR

NOFILE		<no file found>

.SEVERITY	INFORMATION

NOMATCHES	<no strings matched>
NULLFILE	<file !AS contains no records>/FAO=1
TRUNCATE	<record(s) in !AS truncated to !UW bytes>/FAO=2

.SEVERITY	SUCCESS

MATCHED		<!AS - !UL record!%S, !UL match!AS>/FAO=4
NOMATCH		<!AS - !UL record!%S>/FAO=2

.END
