!	Version 'V03-001'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

! MODIFIED BY:
!
!	V03-001	MLJ0086		Martin L. Jack,	3-Apr-1982  23:09
!		Clarify text of TRMMBXUSE, QUEERR, CREQERR.  Delete INIQERR,
!		QUESHRKERR, QUEEXPAERR, QUECHKPERR.  Add NEWQUEUE.
!
!	V02-005	GWF0105		Gary W. Fowler		19-Aug-1981
!		Add error messages for create queue and init queue failure
!
!	V02-004	GWF0068		Gary W. Fowler		23-Jun-1981
!		Add codes for no such destination and invalid destination queue
!
!	V02-003	GWF0035		Gary W. Fowler		17-APR-1981
!		Add codes for JBC$OPENJOB and JBC$CLSJOB
!
!	V02-002	GWF0002		Gary W. Fowler		30-NOV-1979
!		Add error messages for various symbiont create errors.
!
!	V02-001	GWF0001		Gary W. Fowler		23-AUG-1979
!		Added error messages for too many chars in parameter string and
!		for SYNCHRONIZE command
!
! DEFINE JOB_CONTROL - SYMBIONT MANAGER ERROR CODE
!
 
 
!
! ALL MESSAGE ARE BUILT AS WARNINGS - ERROR CLASS IS ADDED BY THE 
! JOB CONTROLLER WHEN NECESSARY.
!
!
 
	.FACILITY	JBC,4 /SYSTEM /MACRO=$JBCMSGDEF
	.SEVERITY	WARNING
	.BASE		0

	ILLDEVNAM	<illegal device name>
	ILLDEVTYP	<illegal device type for queue>
	ILLFILNAM	<illegal file name>
	ILLQUENAM	<illegal queue name>
	NOPRIV		<no privilege for attempted operation>
	NOQUEHDR	<queue header space full>
	NOQUESPACE	<no space to queue files>
	NOSUCHQUE	<no such queue exists>
	NOSUCHJOB	<no job as specified>
	NOOPENJOB	<user job not open>
	QUENOSTOP	<queue not stopped for operation>
	SMINVOPR	<operation not properly requested>
	SMINVOPT	<invalid option code>
	SMINVREQ	<invalid symbiont manager request>
	SMZEROJOB	<zero length job released>
	SYMBDSAB	<symbiont manager is disabled>
	JOBABORT	<job aborted>
	ACMINVOP	<invalid accounting manager request>
	PARLENEXD	<parameter block length exceeded>
	TRMMBXUSE	<SYNCHRONIZE already issued for this job>
	MAXSYMEXD	<max. system symbiont count exceeded>
	SCTTABFUL	<SCT table full>
	CREPRCFAL	<$CREPRC error creating symbiont>
	SYMNTBFUL	<symbiont name table full>
	NODESTQUE	<no such destination queue>
	ILLDESQUE	<illegal destination queue name>
 
!
! DEFINE JOB CONTROLLER INTERNAL ERRORS
! LEAVE SPACE FOR 128 NORMAL MESSAGES
!
 

	.BASE		128

	MBASGN		<error assigning mailbox>
	MBREAD		<error reading mailbox>
	PRCREAT		<error creating process>
	INVMSG		<invalid message code received>
	SNDRESP		<error sending response>
	QUECNT		<queue count is incorrect>
	MULTREC		<queue record multiply allocated>
	LOSTREC		<queue record lost>
	SYMBASN		<error assigning symbiont mailbox>
	SYMBWRT		<error writing symbiont mailbox>
	SCTERR		<error searching SCT>
	QUEERR		<error mapping queue file - symbiont manager disabled>
	MBDEAS		<error deassigning mailbox>
	INVSCT		<invalid SCT state>
	SYMDEL		<symbiont delete error>
	ACNTOPN		<error opening account file>
	ACNTWRT		<error writing account file>
	INPASGN		<error assigning input channel>
	INPREAD		<error reading input>
	USERVAL		<user validation error>
	UAFOPN		<user authorization file open error>
	ENTQUE		<error entering job in queue !AC> /FAO=1
	JOBCRD		<job card syntax error '!AS'> /FAO=1
	PASSCRD		<password card syntax error '!AS'> /FAO=1
	UNESYMMSG	<unexpected message from symbiont manager>
	MBSETAST	<error setting unsolicited mailbox message AST>
	MBWRITE		<error writing mailbox>
	SYMBCRE		<error creating symbiont mailbox>
	PRINTOUT	<printer I/O error>
	QUEUPD		<error updating queue file>
	CREQERR		<error creating queue file - symbiont manager disabled>
	NEWQUEUE	<new queue file created>

	.LITERAL	JBC$_NORMAL=262145
	.LITERAL	JBC$_OPENJOB=262153
	.LITERAL	JBC$_CLSJOB=262161
	.END
