!
! Macros to define VAX/VMS UETP message codes.
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!  LAST MODIFIED BY:
!
!	V03-003	RNH0003		Richard N. Holstein,	13-Jan-1982
!		Set up BASEs such that even though message codes were deleted,
!		the new codes are the same as the old codes.
!
!	V03-001	RNH0002		Richard N. Holstein,	30-Nov-1981
!		RNH0001 broke SATSSS10 which depends on UETP$_DDB.  Put it back
!		in, but comment that it's only a dummy and not to be used.
!
!	V03-001	RNH0001		Richard N. Holstein,	30-Nov-1981
!		Remove obsolete UETP$_CONF, UETP$_DDB and UETP$_UCB.
!
!	T. CAFARELLA 31-JAN-78 (TO REMOVE DUMMY1 AND SATSXX)
!	T. CAFARELLA 29-DEC-1977 (16:25) (FOR SATSMS SUCCESS)
!	R. BATOR  27-DEC-1977 (14:00)
!	R. BATOR  27-DEC-1977 (10:30)
!	L. JONES   19-DEC-1977 (11:30)
!	T. CAFARELLA 19-DEC-1977 (11:00)
!	R. BATOR   16-DEC-1977
!	R. BATOR   15-DEC-1977
!	P. TIRAK   11-SEP-1979 (CHANGE !UB IN DATAER TO !UW)
!
!

!  *****  WARNINGS  *****
	.FACILITY	UETP,116 /SYSTEM
	.SEVERITY	WARNING

	ERBOX		<!/********************!/* Error count = !2UW *!/********************> /FAO=1
	DATAER		<data error on !AS unit !UW byte# !XW good data= !XB bad data= !XB> /FAO=5
!  *****  SUCCESS  *****

	.SEVERITY	SUCCESS
	.BASE		27

	SATSMS		<test module !AC !AC> /FAO=2
! The DDB message is a dummy that remains only for the benefit of SATSSS10, the
! $GETMSG checking System Service UETP.
	DDB		<UETINIT00 DDB 0 !AS 00000000 00000000> /FAO=1
	.BASE		30

!  *****  ERRORS  *****

	.SEVERITY	ERROR
	.BASE		51

	DEUNUS		<!AS device !AS is unusable, error code= !XL> /FAO=3
	DESTP		<!AS stopped testing !AS unit !UB at !%T> /FAO=4
!  *****  INFO  *****
!

	.SEVERITY	INFORMATIONAL
	.BASE		101

	ABORTC		<!AS to abort this test, type ^C> /FAO=1
	DENOSU		<!AS device !AS is not supported> /FAO=2
	USER		<!AS !UW user!%S running> /FAO=2
	.END
