!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
!  TITLE:  CDD$MSG			CDD Program Interface Message File
!
!  FACILITY:  Common Data Dictionary
!
!  ABSTRACT:
!
!	This file contains all messages used by the CDDSHR.EXE image.
!
!  ENVIRONMENT:
!
!  AUTHOR:  Jeff East,	20-Jul-81
!
!  MODIFIED BY:
!
!	08-Sept-81	(KJM)	Added SPBALREXI message.
!
!--
        .FACILITY       CDD,43/SYSTEM
        .TITLE          CDD$MSG Common Data Dictionary Exception Messages

	.BASE	20
ACLNOTFND	<>/ERROR

	.BASE	40
ALLFAILED	<>/SUCCESS

	.BASE	60
ALLPATFND	<>/SUCCESS

	.BASE	80
ASYNCTRAP	<>/SEVERE

	.BASE	100
ATTALREXI	<>/ERROR

	.BASE	120
ATTERROR	<>/SEVERE/FAO=1

	.BASE	140
ATTNOTFND	<>/ERROR

	.BASE	160
BADCHKSUM       <>/SEVERE

	.BASE	180
BADCLUSEQ	<>/SEVERE

	.BASE	200
BADGRPSEQ	<>/SEVERE

	.BASE	220
BADLINNUM       <>/SEVERE

	.BASE	240
BADPATH		<>/ERROR

	.BASE	260
BADREFCOU       <>/SEVERE

	.BASE	280
BADSTREAM       <>/ERROR

	.BASE	300
BADUIC		<>/ERROR

	.BASE	320
BADUSRCNX       <>/ERROR

	.BASE	340
BLKALREXI       <>/SEVERE/FAO=2

	.BASE	360
BLKNOTFIT       <>/SEVERE

	.BASE	380
BLKNOTFND       <>/SEVERE

	.BASE	400
BLKTOOBIG       <>/SEVERE

	.BASE	420
CCBWASACT       <>/SEVERE

	.BASE	430
CDDNOTINS	<VAX-11 CDD is not installed on your system>/SEVERE

	.BASE	440
CELNOTEMP	<>/ERROR

	.BASE	460
CELTOOBIG	<>/ERROR

	.BASE	480
CLOSEPER	<>/ERROR

	.BASE	500
CLOSERROR	<>/SEVERE/FAO=1

	.BASE	520
CONSECPER	<>/ERROR

	.BASE	540
CORDATSTR	<>/SEVERE

	.BASE	560
DENIED		<>/ERROR

	.BASE	580
ENDOFATT	<>/ERROR

	.BASE	600
ENDOFDIR	<>/ERROR

	.BASE	620
EMPTYCELL	<>/ERROR

	.BASE	640
EXTENDERR	<>/SEVERE/FAO=1

	.BASE	660
FILALRACC       <>/ERROR

	.BASE	680
FILNOTCOR	<>/SEVERE

	.BASE	700
FNDDIRNOD	<>/SUCCESS

	.BASE	720
FNDTOPNOD	<>/SUCCESS

	.BASE	740
FORFILDIR	<>/SUCCESS

	.BASE	760
ILLATTOPR	<>/ERROR

	.BASE	780
ILLDATTYP	<>/ERROR

	.BASE	800
ILLLOCCON	<>/ERROR

	.BASE	820
ILLLOCREQ	<>/SEVERE

	.BASE	840
ILLNAMCHR	<>/error

	.BASE	860
ILLNAMSIZ	<>/ERROR

	.BASE	880
ILLPURTYP       <>/SEVERE

	.BASE	900
ILLSIBLNG       <>/SEVERE

	.BASE	920
ILLVALSIZ	<>/ERROR

	.BASE	940
INCOMPVER	<>/SEVERE/FAO=2

	.BASE	960
INSFILNAM	<>/ERROR

	.BASE	980
INV1STCHR	<>/ERROR

	.BASE	1000
INVARGOPT	<>/SEVERE

	.BASE	1020
INVATTNAM	<>/ERROR

	.BASE	1040
INVBLKTYP 	<>/SEVERE

	.BASE	1060
INVBUFSIZ	<>/ERROR

	.BASE	1080
INVCLOPAR	<>/ERROR

	.BASE	1100
INVCELNUM	<>/ERROR

	.BASE	1120
INVCONPTR       <>/SEVERE

	.BASE	1140
INVDELLOC       <>/SEVERE

	.BASE	1160
INVHISCIB       <>/SEVERE

	.BASE	1180
INVHYPHEN	<>/ERROR

	.BASE	1200
INVLSTCHR	<>/ERROR

	.BASE	1220
INVLOCTYP       <>/SEVERE

	.BASE	1240
INVNODNAM	<>/ERROR

	.BASE	1260
INVOPNPAR	<>/ERROR

	.BASE	1280
INVPARAM	<>/ERROR

	.BASE	1300
INVPARNCB	<>/SEVERE

	.BASE	1320
INVPERIOD	<>/ERROR

	.BASE	1340
INVPOOTYP	<>/SEVERE

	.BASE	1360
INVRLSOPT	<>/ERROR

	.BASE	1380
LCCNOTAVL       <>/ERROR

	.BASE	1400
LCCNOTFND       <>/ERROR

	.BASE	1420
LISALRACT       <>/SEVERE

	.BASE	1440
LISTOOBIG	<>/ERROR

	.BASE	1460
LOCKEDPAG       <>/ERROR

	.BASE	1480
LOCNOTREL       <>/ERROR

	.BASE	1500
LOCTOOLOW       <>/SEVERE

	.BASE	1520
NODALREXI	<>/ERROR

	.BASE	1540
NODICT		<>/SEVERE

	.BASE	1560
NODHASCHI	<>/ERROR

	.BASE	1580
NODNOTFND	<>/ERROR

	.BASE	1600
NODNOTLOC 	<>/ERROR

	.BASE	1620
NOFREEBUF       <>/SEVERE

	.BASE	1640
NOFREEPAG       <>/ERROR

	.BASE	1660
NOLCKTBL	<>/SEVERE

	.BASE	1680
NOLOGIN         <>/SEVERE

	.BASE	1700
NOPAGES		<>/SEVERE

	.BASE	1720
NOPRIV		<>/ERROR

	.BASE	1740
NORLSENCB	<>/SEVERE

	.BASE	1760
NOSTORDIR	<>/ERROR

	.BASE	1780
NOSUCHLIN       <>/SEVERE

	.BASE	1800
NOSUCHLOC       <>/SEVERE

	.BASE	1820
NOTASTREE       <>/ERROR

	.BASE	1840
NOTDIRNOD	<>/ERROR

	.BASE	1860
NOTLIST		<>/ERROR

	.BASE	1880
NOTNODE 	<>/ERROR

	.BASE	1900
NOTOWNER        <>/ERROR

	.BASE	1920
NOTPORPAG       <>/SEVERE

	.BASE	1940
NOTSYSNAM	<>/ERROR

	.BASE	1960
NOUSRCNTX       <>/ERROR

	.BASE	1980
NULNODNAM       <>/ERROR

	.BASE	2000
PAGFULL         <>/SEVERE

	.BASE	2020
PAGNOTFND       <>/SEVERE

	.BASE	2040
PAGNOTMAP       <>/SEVERE/FAO=2

	.BASE	2060
PASTTOP		<>/ERROR

	.BASE	2080
PERINPASS	<>/ERROR

	.BASE	2100
REAONLATT	<>/ERROR

	.BASE	2120
READERROR	<>/SEVERE/FAO=2

	.BASE	2140
READONLY        <>/ERROR

	.BASE	2160
RMSERROR        <>/ERROR

	.BASE	2180
SOMFAILED	<>/SUCCESS

	.BASE	2190
SPBALREXI	<>/SEVERE

	.BASE	2200
TOOFEWPAR       <>/ERROR

	.BASE	2220
TOOMANFIL       <>/SEVERE

	.BASE	2240
TOOMANLCC 	<>/SEVERE

	.BASE	2260
TOOMANPAR       <>/ERROR

	.BASE	2280
TOPNOTDEL       <>/ERROR

	.BASE	2300
TOPNOTREN	<>/ERROR

	.BASE	2320
VALTRUNC	<>/SUCCESS

	.BASE	2340
WRITERROR	<>/SEVERE/FAO=2

	.BASE	2360
WRODATTYP	<>/ERROR

	.BASE	2380
WRONGPAGE	<>/SEVERE

	.BASE	2400
WROPAGPTR       <>/SEVERE


!++
!
!	DEBUGGING MESSAGES
!
!--

!EXTEND		<>/FAO=3/INFO


        .END
