!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! RETURN STATUS CODES FOR CROSS REFERENCE PROGRAM
!
! MODIFIED BY:
!
!	V02-002	BLS0156		Benn Schreiber	 1-Mar-1982
!		Remove unused messages
!
!	V02-001	BLS0123		Benn Schreiber	19-Dec-1981
!		Change text of FAOFAIL
!


!
! SUCCESS CODES		(SEVERITY LEVEL 1)
!
	.FACILITY	CREF,101 /SYSTEM /PREFIX=CRF$_ /MACRO=$CRFMSG
	.SEVERITY	SUCCESS
	.BASE		0

	SUCCESS		<success>
	KEYPRVENTR	<key previously entered in table>
	KEY1STENTR	<first time key entered in table>
	REFPRVENTR	<reference previously entered in table>
	UNUSERR		<unused>

!
! SEVERE ERROR CODES		(SEVERITY LEVEL 2)
!


	.SEVERITY	ERROR
	.BASE		10

	UNUERR1		<unused>
	UNUERR2		<unused>
	UNUERR3		<unused>
	UNUERR4		<unused>
	UNUERR5		<unused>
	UNUERR6		<unused>
	UNUERR7		<unused>
	NO_OUTRTN	<no output routine address provided>
	LINELNG		<illegal output line length>
	FAOFAIL		<FAO system service failure>
	UNUERR8		<unused>
	.END
