!---
!
!	Error messages for the message compiler
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:  MESSAGE compiler
!
! ABSTRACT:
!
!	These are the error messages used by the message compiler
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, unprivileged user mode utility,
!	operates at non-AST level.
!
! AUTHOR:  Tim Halvorsen,  Nov 1979
!
! MODIFIED BY:
!
!	V02-002 JWT0002		Jim Teague		13-Nov-1981
!		LITCONF and NOFACIL extended to include /SDL errors
!
!	V02-001	PCG0001		Peter George		29-Dec-1980
!		Add LITCONF and NOFACIL warnings.
!----

	.FACILITY	MESSAGE,151 /SYSTEM /PREFIX=MSG$_

	.SEVERITY	ERROR

	SYMTOOLNG	<symbol name too long>
	BADVALUE	<illegal qualifier value>
	NOMSGS		<no messages defined>
	NOSEVER		<severity unspecified, ERROR used>
	DUPMSG		<message code !XL already assigned to !AD>/FAO=3
	CONFFAC		<facility definition conflicts with previous definition>
	SHARCONF	</SHARED conflicts with facility number>
	INDEXOVFL	<index area overflow in section - please submit SPR>
	DATAOVFL	<data area overflow in section - please submit SPR>
	FACOVFL		<facility table overflow in section - please submit SPR>
	DUPSYM		<duplicate symbol definition>

	.SEVERITY	WARNING

	LITCONF		<literal conflicts with facility prefix - omitted in MDL/SDL>
	NOFACIL		<constant outside scope of facility - omitted in MDL/SDL>

	.END
