!	VERIFYMSG.MSG - VERIFY Messages
!
!	Version	'V02-002'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
!
! FACILITY:
!	Files-11 structure verification utility.
!
! ABSTRACT:
!	This file contains the messages for VERIFY.
!
! ENVIRONMENT:
!	VAX/VMS user mode.
!
!--
!
! AUTHOR: M. Jack, CREATION DATE: 11-Oct-1980
!
! MODIFIED BY:
!
!	V02-002	MLJ0074		Martin L. Jack,	23-Jan-1982  23:24
!		Rename [001003] to [SYSLOST] to remove VMS dependence on
!		numbered directories.
!
!	V02-001	MLJ0055		Martin L. Jack,	15-Oct-1981  20:28
!		Add messages DIRNAME, LOSTSCAN, GETDVI.  Downgrade severity of
!		READSCB.
!
!**

.title VERIFYMSG
.facility VERIFY,165/system
.severity fatal
ALLOCMEM	<error allocating virtual memory>
ASSIGN		<error assigning channel to !AS>/FAO=1
BADBITMAP	<BITMAP.SYS too small or not contiguous, RVN !UL>/FAO=1
FINDHOME	<no valid home block, RVN !UL>/FAO=1
FREEMEM		<error freeing virtual memory>
GETDVI		<error getting device characteristics, RVN !UL>/FAO=1
INVDEVICE	<invalid device !AS>/FAO=1
MAXVOLS		<too many volumes in volume set>
OPENBITMAP	<error opening BITMAP.SYS, RVN !UL>/FAO=1
OPENINDEX	<error opening INDEXF.SYS, RVN !UL>/FAO=1
.severity informational
ADDQUOTA	<error adding quota record for [!OB,!OB]>/FAO=2
ALLOCCLR	<blocks incorrectly marked allocated!/!_LBN !UL to !UL, RVN !UL>/FAO=3
ALLOCEXT	<blocks allocated to lost extension file header!/!_LBN !UL to !UL, RVN !UL>/FAO=3
ALLOCSET	<blocks incorrectly marked free!/!_LBN !UL to !UL, RVN !UL>/FAO=3
ALTIHDBAD	<invalid alternate index file header, RVN !UL>/FAO=1
BACKLINK	<incorrect directory back link [!AS]!AC;!UL>/FAO=3
BADDIR		<directory [!AS] has invalid format>/FAO=1
BADDIRENT	<invalid file identification in directory entry [!AS]!AC;!UL>/FAO=3
BADEFBLK	<file (!UL,!UL,!UL) !AF!/!_inconsistent EFBLK and map area>/FAO=4
BADHEADER	<file (!UL,!UL,!UL) !AF!/!_invalid file header>/FAO=4
BADHIBLK	<file (!UL,!UL,!UL) !AF!/!_inconsistent HIBLK and map area>/FAO=4
BBLHEADER	<file (!UL,!UL,!UL) !AF!/!_contains suspected bad blocks>/FAO=4
CHKALTHOME	<invalid alternate home block, VBN !UL, RVN !UL>/FAO=2
CHKPRIHOME	<invalid primary home block, VBN !UL, RVN !UL>/FAO=2
CHKSCB		<invalid storage control block, RVN !UL>/FAO=1
CREATELOST	<error creating directory [SYSLOST]>
DELETE		<file (!UL,!UL,!UL) !AF!/!_error deleting file>/FAO=4
DELHEADER	<file (!UL,!UL,!UL) !AF!/!_marked for delete>/FAO=4
DIRNAME		<directory file [!AS]!AC;!UW is not named '.DIR;1'>/FAO=1
DSAQUOTA	<error disabling quota processing>
ENAQUOTA	<error enabling quota processing>
ENTERLOST	<file (!UL,!UL,!UL) !AF!/!_error entering file in directory [SYSLOST]>/FAO=4
FINDIHD		<no valid index file header, RVN !UL>/FAO=1
FUTBAKDAT	<file (!UL,!UL,!UL) !AF!/!_backup date is in the future>/FAO=4
FUTCREDAT	<file (!UL,!UL,!UL) !AF!/!_creation date is in the future>/FAO=4
FUTREVDAT	<file (!UL,!UL,!UL) !AF!/!_revision date is in the future>/FAO=4
INCQUOTA	<QUOTA.SYS indicates !UL blocks used, actual use is !UL blocks for [!OB,!OB]>/FAO=4
INVEXTBACK	<file (!UL,!UL,!UL) !AF!/!_invalid extension file header back link>/FAO=4
INVEXTFID	<file (!UL,!UL,!UL) !AF!/!_invalid extension file header forward link>/FAO=4
INVEXTHDR	<file (!UL,!UL,!UL) !AF!/!_invalid extension file header sequence>/FAO=4
LOCKHEADER	<file (!UL,!UL,!UL) !AF!/!_deaccess locked>/FAO=4
LOCKVOL		<error locking volume set - /REPAIR cancelled>
LOSTEXTHDR	<file (!UL,!UL,!UL) !AF!/!_lost extension file header>/FAO=4
LOSTHEADER	<file (!UL,!UL,!UL) !AF!/!_not found in a directory>/FAO=4
LOSTSCAN	<due to directory errors, lost files will not be entered>
MAPAREA		<file (!UL,!UL,!UL) !AF!/!_invalid map area>/FAO=4
MODQUOTA	<error modifying quota record for [!OB,!OB]>/FAO=2
MULTALLOC	<file (!UL,!UL,!UL) !AF!/!_multiply allocated blocks!/!_VBN !UL to !UL!/!_LBN !UL to !UL, RVN !UL>/FAO=9
MULTEXTHDR	<file (!UL,!UL,!UL) !AF!/!_multiply allocated extension file header>/FAO=4
NOREPAIR	<one or more volumes write locked - /REPAIR cancelled>
OPENDIR		<error opening directory [!AS]>/FAO=1
OPENFILE	<file (!UL,!UL,!UL) !AF!/!_error opening file for read check>/FAO=4
OPENQUOTA	<error opening QUOTA.SYS>
PRIIHDBAD	<invalid primary index file header, RVN !UL>/FAO=1
READBOOT	<error reading boot block, RVN !UL>/FAO=1
READDIR		<error reading directory [!AS]>/FAO=1
READFILE	<file (!UL,!UL,!UL) !AF!/!_error reading VBN !UL>/FAO=5
READHEADER	<file (!UL,!UL,!UL) !AF!/!_file header read error>/FAO=4
READHOME	<error reading home block, VBN !UL, RVN !UL>/FAO=2
READIBMAP	<error reading index file bitmap, VBN !UL, RVN !UL>/FAO=2
READQUOTA	<error reading QUOTA.SYS, VBN !UL>/FAO=1
READSBMAP	<error reading storage bitmap, VBN !UL, RVN !UL>/FAO=2
READSCB		<error reading storage control block, RVN !UL>/FAO=1
REMOVE		<file (!UL,!UL,!UL)!/!_error removing directory entry>/FAO=3
UNLKVOL		<error unlocking volume set>
WRITEHEADER	<file (!UL,!UL,!UL) !AF!/!_file header write error>/FAO=4
WRITEHOME	<error writing home block, VBN !UL, RVN !UL>/FAO=2
WRITEIBMAP	<error writing index file bitmap, VBN !UL, RVN !UL>/FAO=2
WRITESBMAP	<error writing storage bitmap, VBN !UL, RVN !UL>/FAO=2
WRITESCB	<error writing storage control block, RVN !UL>/FAO=1
WRONGOWNER	<file (!UL,!UL,!UL) !AF!/!_inconsistent extension file header owner UIC>/FAO=4
.end
