! Error message definitions for BASIC PLUS/VAX AME
! File: BPAMSG.MSG, Edit: SBL2001
!
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! 2-001 - Convert to MESSAGE compiler source format.  From BPAMSG.MDL
!	  version 1-001.  SBL 22-Apr-1981
!
!
!
! Define INFO message codes
!
	.FACILITY	BPA,131 /SYSTEM
	.SEVERITY	INFORMATIONAL
	.BASE		0

	BASPLUS		<PDP-11 Instr. BASIC/VAX T1.0>
!
! Define WARNING message codes
!

	.SEVERITY	WARNING

	ILLACCMOD	<Illegal access mode>
	RECTOOLON	<Record too long>
!
! Gap for severe error
!

	.BASE		4

	ILLOP		<Illegal Floating-point op-code>
	CVTERR		<Floating-point conversion error>
	ODDADR		<Floating-point odd address error>
	ILLTI_DEV	<Illegal TI: device>
	ENDFILBAT	<End of file on Batch input>
!
! Define SEVERE message codes
!

	.SEVERITY	FATAL
	.BASE		3

	INTCONCHK	<Internal consistency check error>
	.END
!
! End of definition file
!
