! VAX-11 COBOL Run-Time error condition values/message IDs
! File: COBMSG.MSG, Edit: LB2009
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
!
! Edit History:
!
! 2-001 - Convert to MESSAGE utility source format.  Adapted from COBMSG.MDL
!	  version 1-019.  SBL 22-Apr-1981
! 2-002 - Use COB$ facility for COB$_NORMAL.  SBL 27-Apr-1981
! 2-003 - Copied changes made to COBMSG.MDL to this MSG file.  The messages
!	  added include COB$_LSTHNDUSE, COB$_LSTHNDLDB, and COB$_EXPDBOVER.
!	  LB 7-MAY-81.
! 2-004	- Added COB$_KEYNOTMAT.  PDG 24-Jul-81.
! 2-005	- Added .TITLE PDG 26-Jul-81.
! 2-006	- Added COB$_UNLUNOFIL and COB$_RECNOTLOC.  PDG 7-AUG-81.
! 2-007 - Updated Copyright date and fixed spelling error.  LB 9-AUG-81.
! 2-008 - Added COB$_UNLNO_CUR.  LB 29-OCT-81.
! 2-009 - Changed COB$_GOTNO_ALT to be COB$_GOTO_ALT.  This had been in
!	  error in this file as well as in COBERROR.  LB  1-APR-82.
!
!+
! Symbols are defined following the standard for global names:
!
!	COB$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
!

! MACRO-32 Programming:
!
! The macro call:
!
!	$COBDEF
!
! will cause all symbols to be made available to the module.
! The Run-time Library declares these symbols as EXTERNAL;
! the macros are provided only for the convenience of the user.

!-


!
!
!			; Note: Error codes must not overlap success codes!!!

	.TITLE		COB$MSG
	.FACILITY	COB,25 /SYSTEM


	.SEVERITY	SUCCESS
	.BASE		0

	NORMAL		<normal successful completion>

	.SEVERITY	FATAL
	.BASE		8

	GOTO_ALT	<GO TO with no preceding ALTER>
	RECACTPER	<recursive activation of PERFORM>
	NESERRPER	<nesting error for PERFORM>
	TIMOVELON	<TIMES value overflows longword>
	OCCDEPOVE	<OCCURS DEPENDING value overflows longword>
	SUBOVELON	<subscript or reference modifier overflows longword>
	ERRDURSOR	<error during SORT or MERGE>
	UNEINSCON	<INSPECT CONVERTING lengths unequal>
	CALFAI		<CALL failed on routine (!AS)> /FAO=1
	INVLINVAL	<invalid LINAGE value on file>
!				***** NO_USEPRO must be the first error
!				***** message associated with
!				***** COB$IOEXCEPTION.  It is used as
!				***** the base of an encoding algorithm.
!
	NO_USEPRO	<no USE procedure available for error on file !AS> /FAO=1
	ERRON_FIL	<error on file !AS> /FAO=1
	OPTMISOPE	<optional file !AS missing on OPEN> /FAO=1
	FILALRLOC	<file !AS is already locked> /FAO=1
	FILALROPE	<file !AS is already open> /FAO=1
	FILCLOLOC	<file !AS is closed with LOCK> /FAO=1
	NO_SPACE	<no filespace on device for file !AS> /FAO=1
	FILNOTFOU	<file !AS not found on OPEN> /FAO=1
	OPTMISCLO	<optional file !AS missing on CLOSE> /FAO=1
	FILALRCLO	<file !AS already closed> /FAO=1
	NO_NEXLOG	<no next logical record on file !AS> /FAO=1
	OPTMISREA	<optional file !AS missing on READ> /FAO=1
	NO_NEXVAL	<no next valid record on file !AS> /FAO=1
	RECLOCREA	<record on file !AS is already locked (READ attempt)> /FAO=1
	RECLOC_OK	<record on file !AS already locked, but ok> /FAO=1
	REAUNOFIL	<attempting READ on unopened file !AS> /FAO=1
	REAINCOPE	<READ on file !AS incompatible with OPEN mode> /FAO=1
	WRIBEYBOU	<attempting WRITE beyond boundaries of file !AS> /FAO=1
	WRIUNOFIL	<attempting WRITE on unopened file !AS> /FAO=1
	WRIINCOPE	<WRITE on file !AS incompatible with OPEN mode> /FAO=1
	REWNO_R_S	<attempting REWRITE on file !AS with no previous READ or START> /FAO=1
	REWUNOFIL	<attempting REWRITE on unopened file !AS> /FAO=1
	REWINCOPE	<REWRITE on file !AS incompatible with OPEN mode> /FAO=1
	RECNOTEXI	<record does not exist on file !AS> /FAO=1
	OPTMISSTA	<optional file !AS missing on START> /FAO=1
	RECLOCSTA	<record on file !AS is already locked (START attempt)> /FAO=1
	STAUNOFIL	<attempting START on unopened file !AS> /FAO=1
	STAINCOPE	<START on file !AS incompatible with OPEN mode> /FAO=1
	RECLOCWRI	<record on file !AS is already locked (WRITE attempt)> /FAO=1
	RECLOCDEL	<record on file !AS is already locked (DELETE attempt)> /FAO=1
	DELNO_R_S	<attempting DELETE on file !AS without previous READ or START> /FAO=1
	DELUNOFIL	<attempting DELETE on unopened file !AS> /FAO=1
	DELINCOPE	<DELETE on file !AS incompatible with OPEN mode> /FAO=1
	RECLOCREW	<record on file !AS is already locked (REWRITE attempt)> /FAO=1
	WRIDUPKEY	<attempting WRITE of duplicate key in file !AS> /FAO=1
	WRICREDUP	<WRITE created an allowed duplicate alternate key on file !AS> /FAO=1
	WRINOTASC	<attempting to WRITE non-ascending ISAM key on file !AS> /FAO=1
	WRIDUPALT	<attempting to WRITE duplicate alternate key on file !AS> /FAO=1
	REWCREDUP	<REWRITE created an allowed duplicate alternate key on file !AS> /FAO=1
	PRIKEYCHA	<primary record key on file !AS changed between READ and REWRITE> /FAO=1
	REWDISDUP	<attempting to REWRITE disallowed duplicate key on file !AS> /FAO=1
	WRIDISDUP	<attempting to WRITE disallowed duplicate key on file !AS> /FAO=1
	REASMAMIN	<attempting READ of variable length smaller than minimum allowed from file !AS> /FAO=1
	EOFON_ACC	<end-of-file detected on ACCEPT from file !AS> /FAO=1
	ERRDURACC	<error during ACCEPT from file !AS> /FAO=1
	DISMORMAX	<attempting to DISPLAY more than !SL characters on a single DISPLAY> /FAO=1
	INTEXPOVE	<intermediate exponent overflow>
	INTEXPUND	<intermediate exponent underflow>
	INTRESOPE	<intermediate reserved operand>
	INTDIVZER	<intermediate divide by zero>
	INVDECDIG	<invalid decimal digit: "!AC"> /FAO=1
	UNDEF_EXP	<attempting undefined exponentiation -- negative base raised to fractional exponent>
	WRISMAMIN	<attempting WRITE of variable length smaller than minimum allowed on file !AS> /FAO=1
	REWSMAMIN	<attempting REWRITE of variable length smaller than minimum allowed on file !AS> /FAO=1
	NAMNOTLIN	<attempting to CANCEL routine (!AS), not in linked image> /FAO=1
	INVCHANAM	<invalid character (hexadecimal !XB) in name string> /FAO=1
	ORGNOTMAT	<attempting to open file !AS whose actual organization does not match that declared> /FAO=1
	CANFAIL		<CANCEL failed on routine (!AS)> /FAO=1
	INVARG		<invalid argument>
	FAIGET_VM	<failure to get virtual memory>
	FAIFREEVM	<failure to free virtual memory>
	ERRDURDIS	<error during DISPLAY on file !AS> /FAO=1
	USE_EXIT	<>
	RECACTUSE	<recursive activation of USE procedure>
	FATINTERR	<fatal internal error>
	FAIGET_EF	<failure to get event flag>
	SETEXTFAI	<SET external switch failed>
	INVDECDAT	<invalid decimal data>
	LSTHNDUSE	<lost handler for a USE procedure - environment corrupted !2(+)>/FAO=2
	LSTHNDLDB	<lost handler for data base exception - environment corrupted !+>/FAO=1
	EXPDBOVER	<expression value in data base argument list overflows longword>
	KEYNOTMAT	<attempting to open indexed file !AS whose actual keys do not match those declared>/FAO=1
	UNLUNOFIL	<attempting UNLOCK on unopened file !AS> /FAO=1
    	RECNOTLOC	<record not locked in file !AS (UNLOCK attempt)> /FAO=1
	UNLNO_CUR	<attempting UNLOCK on file !AS with no current record> /FAO=1
	.END

!	[End of file COBMSG.MSG]
