! VAX-11 FORTRAN Run-Time error condition values/message IDs
! File: FORMSG.MSG, Edit: DGP2004
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! 1-014 - Add errors 17-19 for NAMELIST.  SBL 10-Nov-1980
! 1-015 - Correct typo in TOOMANVAL.  SBL 15-Dec-1980
! 1-016 - Restore closing bracket on OPEDEFREQ, mysteriously dropped in 1-015.
!	  SBL 6-Jan-1981
! 2-001 - Convert to MESSAGE utility source format.  Adapted from FORMSG.MDL
!	  version 1-016.  SBL 22-Apr-1981
! 2-002 - Add UNFIO_FMT, FMTIO_UNF, DIRIO_KEY, SEQIO_DIR, KEYIO_DIR,
!	  IO_NONFOR, INVTXTREC, FLOUNDEXC.  JAW 23-Aug-1981
! 2-003 - Change INVTXTREC to INVTEXREC.  JAW 24-Aug-1981
! 2-004 - Add INVTEX which does not require a record number.  This is for indexed
!	  and internal files that do not have a valid record number.  DGP 21-Dec-9181
!--

!+
! Symbols are defined following the standard for global names:
!
!	FOR$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
! The names of all procedures using each error condition value should appear
! in the comments included with each error definition.
!

! MACRO-32 Programming:
!
! The macros call:
!
!	$FORDEF
!
! will cause all symbols to be made available to the module.
! The STS$V_MSG_ID is the FORTRAN error number (1:94).
! These symbols are declared EXTERNAL by the Run-time Library,
! the macros are provided only for the convenience of the user.

!-




!			; Make all errors be severe (except as noted)

!			; Set sub-system specific bit and make SEVERE
!			; Set LH to 24 (decimal).

	.FACILITY	FOR,24 /SYSTEM
	.SEVERITY	FATAL

	NOTFORSPE	<not a FORTRAN-specific error!/!+!+  user PC !XL> /FAO=3
!		; never signaled. Used only as a FORTRAN error
!		; number for ERRSNS to mean some other facility
!		; than FOR$ or MTH$ detected the error.


!			; Set sub-system specific bit and make SEVERE
!			; Set LH to 24 (decimal).


	.BASE		17

	SYNERRNAM	<syntax error in NAMELIST input at or before "!AS"!/  unit !SL  file !AS!/  user PC !XL> /FAO=4
	TOOMANVAL	<too many values for NAMELIST variable "!AC"!/  unit !SL  file !AS!/  user PC !XL> /FAO=4
	INVREFVAR	<invalid reference to variable "!AS" in NAMELIST input!/  unit !SL  file !AS!/  user PC !XL> /FAO=4
	REWERR		<REWIND error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	DUPFILSPE	<duplicate file specifications!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INPRECTOO	<input record too long!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	BACERR		<BACKSPACE error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	ENDDURREA	<end-of-file during read!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	RECNUMOUT	<record number outside range!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	OPEDEFREQ	<OPEN or DEFINE FILE required for keyed or direct access!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	TOOMANREC	<too many records in I/O statement!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	CLOERR		<CLOSE error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	FILNOTFOU	<file not found!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	OPEFAI		<open failure!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	MIXFILACC	<mixed file access modes!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INVLOGUNI	<invalid logical unit number!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	ENDFILERR	<ENDFILE error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	UNIALROPE	<unit already open!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	SEGRECFOR	<segmented record format error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	ATTACCNON	<attempt to access non-existent record!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INCRECLEN	<inconsistent record length!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	ERRDURWRI	<error during write!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	ERRDURREA	<error during read!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	RECIO_OPE	<recursive I/O operation!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INSVIRMEM	<insufficient virtual memory!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	NO_SUCDEV	<no such device!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	FILNAMSPE	<file name specification error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INCRECTYP	<inconsistent record type!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	KEYVALERR	<keyword value error in OPEN statement!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INCOPECLO	<inconsistent OPEN/CLOSE parameters!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	WRIREAFIL	<write to READONLY file!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INVARGFOR	<invalid argument to FORTRAN Run-Time Library!/!+!+  user PC !XL> /FAO=3
	INVKEYSPE	<invalid key specification!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INCKEYCHG	<inconsistent key change or duplicate key!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INCFILORG	<inconsistent file organization!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	SPERECLOC	<specified record locked!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	NO_CURREC	<no current record!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	REWRITERR	<REWRITE error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	DELERR		<DELETE error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	UNLERR		<UNLOCK error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	FINERR		<FIND error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3

	.LITERAL	FOR$_MORONEREC=1605852

	.LITERAL	FOR$_ATTREANON=1605924

!			; Set sub-system specific bit and make SEVERE


	.BASE		59

	LISIO_SYN	<list-directed I/O syntax error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INFFORLOO	<infinite format loop!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	FORVARMIS	<format/variable-type mismatch!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	SYNERRFOR	<syntax error in format!/  unit !SL  file !AS!/  user PC !XL> /FAO=3

!			; Set sub-system specific bit and make ERROR (not SEVERE)

	.SEVERITY	ERROR

	OUTCONERR	<output conversion error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3

!			; Set sub-system specific bit and make SEVERE


	.SEVERITY	FATAL

	INPCONERR	<input conversion error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3

!			; Set sub-system specific bit and make SEVERE


	.BASE		66

	OUTSTAOVE	<output statement overflows record!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	INPSTAREQ	<input statement requires too much data!/  unit !SL  file !AS!/  user PC !XL> /FAO=3
	VFEVALERR	<variable format expression value error!/  unit !SL  file !AS!/  user PC !XL> /FAO=3



!			; Set sub-system specific bit and make SEVERE

	.BASE		93

	ADJARRDIM	<adjustable array dimension error>

! **********
! The following messages are secondary messages, or are used only in
! exit handlers, and therefore do not need to be (and should not be)
! contiguous with the messages above.

	.BASE		256

! The next six messages are secondary messages for use with MIXFILACC in
! FOR$$IO_BEG and FOR$$CB.

	UNFIO_FMT	<unformatted I/O to unit open for formatted transfers> /FAO=0
	FMTIO_UNF	<formatted I/O to unit open for unformatted transfers> /FAO=0
	DIRIO_KEY	<direct-access I/O to unit open for keyed access> /FAO=0
	SEQIO_DIR	<sequential-access I/O to unit open for direct access> /FAO=0
	KEYIO_DIR	<keyed-access I/O to unit open for direct access> /FAO=0
	IO_NONFOR	<I/O to non-FORTRAN unit> /FAO=0

! The next two messages are secondary messages for use with INPCONERR in
! FOR$$UDF_WF and FOR$$UDF_WL.

	INVTEXREC	<invalid text is "!AS" in record number !UL> /FAO=2
	INVTEX		<invalid text is "!AS"> /FAO=1

! The next message is a primary message used in the exit handler which
! is declared by FOR$HANDLER.

	.BASE		300
	.SEVERITY	INFORMATION

	FLOUNDEXC	<!SL floating underflow exception!%S> /FAO=1

! End of special messages
! **********

	.END

! End of file FORMSG.MSG
