! VAX-11 Common Run-Time Procedure Library error condition values/message IDs
! File: LIBMSG.MSG, Edit: MLJ2012
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! 1-013 - Add LIB$_KEYALRINS, LIB$_KEYNOTFOU.  SBL 20-Mar-1981
! 1-014	- Add LIB$_INVCVT. FM 24-MAR-81
! 1-015 - Add LIB$_INVDTYDSC, LIB$_INVCLADSC, LIB$_INVCLADTY, LIB$_INVNBDS
!	      LIB$_DESSTROVF, LIB$_OUTSTRTRU.  FM 21-APR-81
! 2-001 - Convert to MESSAGE utility source format.  Adapted from LIBMSG.MDL
!	  version 1-015.  SBL 23-Apr-1981
! 2-002 - Use LIB$ facility for LIB$_NORMAL.  SBL 27-Apr-1981
! 2-003 - Add LIB$_INTOVF, LIB$_FLTOVF, LIB$_FLTUND, LIB$_DECOVF, LIB$_ROPRAND.
! 2-004 - Add LIB$_WRONUMARG.  RKR 4-SEP-1981
! 2-005 - Add messages for LIB$CLI_CALLBACK.  SBL 14-Sept-1981
! 2-006 - Add LIB$_INVSYMNAM, messages for LIB$EXTEND_RANGE.  SBL 1-Oct-1981
! 2-007 - Add LIB$_WASSET and LIB$_WASCLR.  SBL 16-Oct-1981
! 2-008 - Correct typo in LIB$_UNAEXTRAN.  SBL 30-Oct-1981
! 2-009 - Remove LIB$_WASSET and LIB$_WASCLR.  Add LIB$_ATTREQREF.  SBL 21-Dec-1981
! 2-010 - Remove messages for LIB$EXTEND_RANGE.  SBL 22-Dec-1981
! 2-011 - Correct typo.  SBL 23-Dec-1981
! 2-012 - Add LIB$_INVFILSPE for file manipulation procedures.  MLJ 30-Dec-1981
!-

!+
! Symbols are defined following the standard for global names:
!
!	LIB$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
! The names of all procedures using each error condition value should appear
! in the comments included with each error definition.
!

! MACRO-32 Programming:
!
! The macros call:
!
!	$LIBDEF
!
! will cause all symbols to be made available to the module.
! The Run-time Library declares these symbols as EXTERNAL;
! the macros are provided only for the convenience of the user.

!-


!			; Set LH to 21 (decimal).
	.FACILITY	LIB,21 /SYSTEM
	.SEVERITY	SUCCESS
	.BASE		0

	NORMAL		<normal successful completion>

	.BASE		2

	STRTRU		<string truncated>

	ONEENTQUE	<one entry in queue>
!			;  LIB$INSQHI, LIB$INSQTI, LIB$REMQHI, LIB$REMQTI
	KEYALRINS	<key already inserted in tree>
!			; LIB$INSERT_TREE


!			; Note: Error codes must not overlap sucess codes!!!
!			; Set sub-system specific bit for now.
!			; Set LH to 21 (decimal).
!			; so that each code will be an WARNING code.
!			; Set sub-system specific bit for now.


	.SEVERITY	FATAL
	.BASE		64

	BADSTA		<bad stack>
!			;    LIB$FIXUP_FLT
	FATERRLIB	<fatal error in library>
!			;    LIB$VM_GET

	INSVIRMEM	<insufficient virtual memory>
!			;    LIB$VM_GET, LIB$LOOKUP_KEY
	INPSTRTRU	<input string truncated>
!			;    LIB$GET_INPUT

	INVSTRDES	<invalid string descriptor>
!			;    LIB$SCOPY_xxxx
	INTLOGERR	<internal logic error>

	INVARG		<invalid argument(s)>
!			;    LIB$LOOKUP_KEY

	AMBKEY		<"!AS" is an ambiguous keyword> /FAO=1
!			;    LIB$LOOKUP_KEY

	UNRKEY		<"!AS" is an unrecognized keyword> /FAO=1
	PUSSTAOVE	<pushdown stack overflow>
!			;    LIB$FIXUP_FLT
	USEFLORES	<use of floating reserved operand>
!			;    LIB$LOOKUP_KEY
	SIGNO_ARG	<signal with no arguments>
!			;    LIB$SIGNAL, LIB$STOP
	BADBLOADR	<bad block address>
!			; LIB$FREE_VM
	BADBLOSIZ	<bad block size>
!			; LIB$GET_VM
	NOTFOU		<not found>
!			; LIB$FFS, LIB$FFC
	ATTCONSTO	<attempt to continue from stop>
!			; LIB$SIGNAL, LIB$STOP
	SYNTAXERR	<string syntax error detected by LIB$TPARSE>
	INVTYPE		<invalid LIB$TPARSE state table entry>
!			; LIB$TPARSE
	INSEF		<insufficient event flags>
!			; LIB$GET_EF
	EF_ALRFRE	<event flag already free>
!			; LIB$FREE_EF
	EF_ALRRES	<event flag already reserved>
!			; LIB$RESERVE_EF
	EF_RESSYS	<event flag reserved to system>
!			; LIB$FREE_EF, LIB$RESERVE_EF
	INSLUN		<insufficient logical unit numbers>
!			; LIB$GET_LUN
	LUNALRFRE	<logical unit number already free>
!			; LIB$FREE_LUN
	LUNRESSYS	<logical unit number reserved to system>
!			; LIB$FREE_LUN, LIB$RESERVE_LUN
	SCRBUFOVF	<screen buffer overflow>
!			; SCR package
	INVSCRPOS	<invalid screen position>
!			; SCR package
	SECINTFAI	<secondary interlock failure in queue>
!			; LIB$INSQHI, LIB$INSQTI, LIB$REMQHI, LIB$REMQTI
	INVCHA		<invalid character>
!			; LIB$TRA_ASC_EBC, LIB$TRA_EBC_ASC
	QUEWASEMP	<queue was empty>
!			; LIB$REMQHI, LIB$REMQTI
	STRIS_INT	<string is interlocked>
!			; LIB$SCOPY, etc.
	KEYNOTFOU	<key not found in tree>
!			; LIB$LOOKUP_TREE
	INVCVT		<invalid conversion>
!			; LIB$CVTDXDX
	INVDTYDSC	<invalid data type in descriptor>
!			; LIB$CVTDXDX
	INVCLADSC	<invalid class in descriptor>
!			; LIB$CVTDXDX
	INVCLADTY	<invalid class data type combination in descriptor>
!			; LIB$CVTDXDX
	INVNBDS		<invalid numeric byte data string>
!			; LIB$CVTDXDX
	DESSTROVF	<destination string overflow>
!			; LIB$CVTDXDX
	INTOVF		<integer overflow>
!			; LIB$CVTDXDX
	DECOVF		<decimal overflow>
!			; LIB$CVTDXDX
	FLTOVF		<floating overflow>
!			; LIB$CVTDXDX
	FLTUND		<floating overflow>
!			; LIB$CVTDXDX
	ROPRAND		<reserved operand>
!			; LIB$CVTDXDX
	WRONUMARG	<wrong number of arguments>
!			; LIB$ANALYZE_SDESC
	NOSUCHSYM 	<no such symbol>
!			; LIB$CLI_CALLBACK
	INSCLIMEM 	<insufficient CLI memory>
!			; LIB$CLI_CALLBACK
	AMBSYMDEF 	<ambiguous symbol definition>
!			; LIB$CLI_CALLBACK
	NOCLI     	<no CLI present to perform function>
!			; LIB$CLI_CALLBACK
	UNECLIERR 	<unexpected CLI error>
!			; LIB$CLI_CALLBACK
	INVSYMNAM	<invalid symbol name>
!			; LIB$CLI_CALLBACK
	ATTREQREF	<attach request refused>
!			; LIB$ATTACH
	INVFILSPE	<invalid file specification>
!			; LIB$FID_TO_NAME, LIB$EXTRACT_CONCEALED,
!			; LIB$SET_FILE_PROT, LIB$UNLOCK_FILE, LIB$CREATE_DIR


	.SEVERITY	WARNING
	.BASE		512

	OUTSTRTRU	<output string truncated>
!			; LIB$CVTDXDX
	.END

!	End of file LIBMSG.MSG
