! VAX-11 Math Library error condition values/message IDs
! File: MTHMSG.MSG, Edit: SBL2001
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! 2-001 - Convert to MESSAGE utility source format.  Adapted from MTHMSG.MDL
!	  version 1-004.  SBL 22-Apr-1981

!+
! Symbols are defined following the standard for global names:
!
!	MTH$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
! The names of all procedures using each error condition value should appear
! in the comments included with each error definition.
!

! MACRO-32 Programming:
!
! The macros call:
!
!	$MTHDEF
!
! will cause all symbols to be made available to the module.
! The STS$V_MSG_ID is the FORTRAN error number (1:94).
! The Run-time Library declares these symbols EXTERNAL;
! the macros are provided only for the convenience of the user.

!-






!			; Set sub-system specific bit and make SEVERE
!			; Set LH to 22 (decimal) MTH$ prefix

	.FACILITY	MTH,22 /SYSTEM
	.SEVERITY	FATAL
	.BASE		80

	WRONUMARG	<wrong number of arguments!/  user PC !XL> /FAO=1
	INVARGMAT	<invalid argument to math library!/  user PC !XL> /FAO=1
	UNDEXP		<undefined exponentiation!/  user PC !XL> /FAO=1
	LOGZERNEG	<logarithm of zero or negative value!/  user PC !XL> /FAO=1
	SQUROONEG	<square root of negative value!/  user PC !XL> /FAO=1

!			; Set sub-system specific bit and make SEVERE
!			; Set LH to 22 (decimal) MTH$ prefix


	.BASE		87

	SIGLOSMAT	<significance lost in math library!/  user PC !XL> /FAO=1
	FLOOVEMAT	<floating overflow in math library!/  user PC !XL> /FAO=1
	FLOUNDMAT	<floating underflow in math library!/  user PC !XL> /FAO=1

	.LITERAL	MTH$_SINCOSSIG=1475260

	.END

! End of file MTHMSG.MSG
