! VAX-11 Common Run-Time Procedure Library error condition values/message IDs
! File: OTSMSG.MSG, Edit: RKR2002
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! 2-001 - Convert to MESSAGE utility source format.  Adapted from OTSMSG.MDL
!	  version 1-009.  SBL 22-Apr-1981
! 2-002 - Add OTS$_WRONUMARG.   RKR 4-SEP-1981
!--

!+
! Symbols are defined following the standard for global names:
!
!	OTS$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
! The names of all procedures using each error condition value should appear
! in the comments included with each error definition.
!

! MACRO-32 Programming:
!
! The macros call:
!
!	$OTSDEF
!
! will cause all symbols to be made available to the module.
! The Run-time Library declares these symbols EXTERNAL;
! the macros are provided only for the convenience of the user.

!-








!+
! Define OTS$ SEVERE error messages
!-

!			; Do not have concept of error number (see FOR$ MTH$)
!			; Set sub-system specific bit and make SEVERE
!			; Set LH to 23 (decimal) OTS$ prefix

	.FACILITY	OTS,23 /SYSTEM
	.SEVERITY	FATAL

	INVSTRDES	<invalid string descriptor>
	FATINTERR	<fatal internal error in Run-Time Library>
	INTDATCOR	<internal data corrupted in Run-Time Library>
	IO_CONCLO	<I/O continued to closed file>
	INPCONERR	<input conversion error>
	OUTCONERR	<output conversion error>
	STRIS_INT	<string is interlocked>
	INSVIRMEM	<insufficient virtual memory>
	WRONUMARG	<wrong number of arguments>
!			; OTS$SCOPY


!+
! Define OTS$ WARNING messages:
!-

!			; Do not have concept of error number (see FOR$ MTH$)
!			; Set sub-system specific bit and make WARNING
!			; Set LH to 23 (decimal) OTS$ prefix


	.SEVERITY	WARNING
	.BASE		128

	USEFLORES	<use of floating reserved operand>


	.END

! End of file OTSMSG.MSG
