! VAX-11 String Library error condition values/message IDs
! File: STRMSG.MSG, Edit: SBL2002
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! 2-001 - Convert to MESSAGE utility source format.  Adapted from STRMSG.MSG
!	  version 1-004.  SBL 22-Apr-1981
! 2-002 - Don't define STR$_NORMAL here, do it in STRMSGDEF.MAR.  SBL 27-Apr-1981

!+
! Symbols are defined following the standard for global names:
!
!	STR$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
!

! MACRO-32 Programming:
!
! The macro call:
!
!	$STRDEF
!
! will cause all symbols to be made available to the module.
! The Run-time Library declares these symbols as EXTERNAL;
! the macros are provided only for the convenience of the user.

!-


!
! The following SEVERE errors are always signalled.
!
!			; Note: Error codes must not overlap sucess codes!!!
	.FACILITY	STR,36 /SYSTEM

	.SEVERITY	FATAL
	.BASE		8

	FATINTERR	<Fatal internal error>
	DIVBY_ZER	<Division by zero>
	ILLSTRCLA	<Illegal string class>
	STRIS_INT	<String is interlocked>
	WRONUMARG	<Wrong number of arguments, !UB, to !AS> /FAO=2
	INSVIRMEM	<Insufficient virtual memory>
	STRTOOLON	<String is too long (greater than 65535)>
!
! The following are warning errors.
!
!			; go in steps of 8.

	.SEVERITY	WARNING
	.BASE		64

	TRU		<Truncation>

!
! The following are qualified success messages
!
!			; go in steps of 8.

	.SEVERITY	SUCCESS
	.BASE		128

	NEGSTRLEN	<Negative string length>
	ILLSTRPOS	<Illegal string position>
	ILLSTRSPE	<Illegal string specification>

!
	.END

!	[End of file STRMSG.MSG]

