!	Version 'V03-012'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! MODIFIED BY:
!
!	V012	PCG0004		Peter George	22-Apr-1982
!		Add INVRANGE.
!
!	V011	PCG0003		Peter George	07-Apr-1982
!		Add ASTDCL and TRMMBX and change BADINPUT to SPWNIO.
!
!	V010	MAJ0002		Melanie Johnson	01-Apr-1982
!		Add NOSPAWN and change the text of BADINPUT.
!
!	V009	PCG0002		Peter George	22-Mar-1982
!		Add BADINPUT, CONCAT, INVIFTHEN, and SYMTOOLNG messages.
!		Change text of NOCLINT message.
!
!	V008	PCG0001		Peter George	07-Feb-1982
!		Add INVRFM and NOCLINT messages.
!
!	V007	MLJ41102	Martin L. Jack,	18-Jan-1982  17:47
!		Add INVFILSPE to fix confusing SUBMIT/PRINT message.  Add
!		INVLOGFIL to support /LOG and /NAME semantics cleanup.
!
!	V006	TMH0006		Tim Halvorsen	30-Dec-1981
!		Add messages for new CLI interface.
!
!	V005	ROW0048		Ralph O. Weber	24-NOV-1981
!		Add "bad control character enable/disable mask", BADCTLMSK, 
!		message.
!
!	V004	TMH0004		Tim Halvorsen	07-Nov-1981
!		Remove the word "account" from message in MAJ0001.
!		Add messages for SPAWN and ATTACH commands.
!
!	V003	MAJ0001		Melanie Johnson	16-Oct-81
!		Add warning "insufficient privilege to change account UIC".
!
!	V002	TMH0002		Tim Halvorsen	20-Mar-1981
!		Add "label ignored outside of procedure".
!
!	V001	TMH0001		Tim Halvorsen	13-Sep-1980
!		Add "illegal structure level for command tables" message
!---

!
! DEFINE CLI RELATED STATUS VALUES
!
 
 
	.FACILITY	CLI,3 /SYSTEM /MACRO=$CLIMSGDEF
	.SEVERITY	WARNING

	ABVERB		<ambiguous verb>
	ABKEYW		<ambiguous keyword>
	BUFOVF		<command buffer overflow>
	COMPLX		<expression too complex - simplify>
	DEFOVF		<too many symbols defined>
	DIRECT		<invalid directory syntax>
	EXPSYN		<invalid expression syntax>
	IMCHNG		<two images requested in one command>
	INSFPRM		<insufficient parameters>
	IVCHAR		<non-numeric character in value string>
	.LITERAL	CLI$_SPARE1=229464

	.BASE		12

	IVKEYW		<unrecognized qualifier keyword>
	IVOPER		<unrecognized operator>
	IVPROT		<invalid protection code>
	IVQLOC		<invalid qualifier location>
	IVSYMB		<symbol must start with alphabetic>
	IVVALU		<invalid syntax for value specification>
	IVVERB		<unrecognized command>
	MAXPARM		<maximum parameter count exceeded>
	NOATFIL		<no file name for command procedure>
	NOCCAT		<no concatenation allowed in parameter>
	NOCOMD		<no command on line>
	NOKEYW		<no keyword in qualifier>
	NOLIST		<parameter list not allowed>
	NOQUAL		<qualifier not allowed on this command>
	NOVALU		<no value allowed on qualifier>
	NOTNEG		<qualifier has no negative form>
	NULFIL		<null file specification>
	NUMBER		<invalid numeric field>
	ONCOMD		<ON command too complex>
	ONERR		<invalid ON error level specified>
	ONLEVL		<ON condition not legal at current level>
	ONOVF		<no room for ON condition command text>
	PARMDEL		<invalid parameter delimiter>
	RSLOVF		<result parse buffer overflow>
	SKPDAT		<data records encountered by system were ignored>
	STKOVF		<command procedures are too deeply nested>
	SYMDEL		<invalid symbol delimiter>
	SYMOVF		<no room for symbol definitions>
	UNDSYM		<undefined symbol>
	USGOTO		<unsatisfied GOTO command>
	VALREQ		<value required on qualifier>
	ONEVAL		<multiple values are not permitted>
	OVRFLW		<value overflow>
	UNPROQUAL	<unprocessed qualifiers>
	UNPROPARM	<unprocessed parameters>
	INVKEY		<invalid keyword>
	INVRSP		<invalid response>
	UNDFIL		<file not open>
	FILOPN		<file is already open>
	BADRET		<RETURN was issued without a subroutine>
	ABSYMD		<ambiguous symbol definition>
	INVUIC		<invalid UIC>
	BADTEXT		<  \!AS\!AS> /FAO=2
	ABFNAM		<ambiguous function name>
	IVFNAM		<invalid function name>
	BLKOVRFLOW	<block overflow>
	BLKUNDFLOW	<block underflow>
	BADBLK		<END issued without corresponding BEGIN>
	NOLBLS		<label ignored while not in a procedure>
 	INSPRIV		<insufficient privilege to change UIC>
	ABSENT		<entity value absent from command string>
	NEGATED		<entity explicitly negated in command string>
	INVFILSPE	<invalid file specification>
	INVLOGFIL	<invalid log file specification>
	INVIFTHEN	<IF statement syntax error - THEN keyword not found>
	SYMTOOLNG	<symbol !AS is too long to copy to subprocess> /FAO=1
	ASTDCL		<out-of-band or ctrl/c AST's will also be delivered to parent>
	INVRANGE	<field specification is out of bounds>
 
!
! DEFINE CLI RELATED "ERROR" LEVEL ERROR CODES
!	BEGIN ERROR CODE 2048 FROM WARNING TO
!	LEAVE ROOM FOR 256 WARNINGS.
!

	.SEVERITY	ERROR
	.BASE		256

	CONFQUAL	<conflicting qualifiers>
	INVQUAL		<invalid qualifier>
	REQPRMABS	<required parameter is absent>
	INVQUALNUM	<invalid qualifier number>
	INVREQTYP	<invalid request type>
	NOVALUE		<value not present>
	VALCNVERR	<error converting value>
	ILLVAL		<illegal value is present>
	NOOPTPRS	<no option present on command>
	CREQUEJOB	<error creating job on queue !AS> /FAO=1
	SUBMITERR	<error submitting file to queue !AS> /FAO=1
	DEVALSPL	<device already spooled>
	DEVNOTSPL	<device not spooled>
	IVDEVTYPE	<invalid device type>
	IMGFNF		<image file not found>
	DEVNOTFOR	<device not mounted foreign>
	PWDNOTVAL	<old password validation error - password unchanged>
	PWDNOTVER	<new password verification error - password unchanged>
	PWDLOCKED	<password was locked to prevent change>
	NOTFR		<no transfer address>
	PWDSYNTAX	<illegal password syntax>
	IMGNAME		<image file !AS> /FAO=1
	IMAGEFNF	<image file not found !AS> /FAO=1
	BADSTRLVL	<unrecognized structure level for command tables>
	REFUSED		<you cannot attach to that process>
	BADCTLMSK	<bad control character enable/disable mask>
	INVRFM		<invalid record format for record I/O - file not opened>
	NOCLINT		<image requested CLI interface routine that does not exist>
	NOSPAWN		<DCL cannot spawn an MCR subprocess - subprocess aborted>
	SPWNIO		<cannot spawn subprocess - input or output is non-terminal PPF>
	TRMMBX		<cannot spawn subprocess - terminal has an associated mailbox>

!
! DEFINE SUCCESSFUL OR INFORMATIONAL MESSAGES
!

	.SEVERITY	SUCCESS
	.BASE		4000

	SPAWNED		<process !AS spawned> /FAO=1
	ATTACHED	<terminal now attached to process !AS> /FAO=1
	RETURNED	<control returned to process !AS> /FAO=1
	PRESENT		<entity value is present in command string>
	DEFAULTED	<entity defaulted present in command string>
	CONCAT		<requested value is terminated by a plus sign>

	.BASE		4094

	PROC_ID		<identification of created process is !XL> /FAO=1
	QUEJOBCRE	<  Job !UW entered on queue !AC> /FAO=2

	.LITERAL	CLI$_NORMAL=196609
 
	.END
