!
!DTS/DTR ERROR MESSAGES
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
!ALL MESSAGES ARE INFORMATIONAL
!
	.FACILITY	NET,501 /SYSTEM /PREFIX=DTS$_ /MACRO=$DTSDEF
	.SEVERITY	INFORMATIONAL
	.BASE		0

	CINBAD		<connect not accepted/rejected as expected>
	BADUSRLEN	<connect/disconnect userdata is wrong length>
	BADUSRDAT	<connect/disconnect userdata invalid>
	CINREJ		<connect aborted, nsp reason is !XL> /FAO=1
	BADDATLEN	<not enough data sent/received>
	DISBAD		<disconnect response not that expected>
	BADDATDAT	<data echoed invalid>
	BADMAIL		<unexpected mail received, type is !XL> /FAO=1
	BADPAT		<invalid  data pattern received>
	BADSEQNUM	<invalid data sequence received>
	BADSUBFCN	<invalid subfunction received>
	BADFUNC		<invalid function type received>
	INVOPTION	<non-supported flow control parameter received>
	.END
