	.title	Obj_Exe_Messages Messages for ANALYZE/OBJECT and ANALYZE/IMAGE

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

	.facility	analyze,177/prefix=anl$_/system

	.severity	success
ok		"Normal successful completion."

	.severity	informational
anything	"!AS"/fao=1
datatype	"data type: DSC$K_DTYPE_!AC (!UL)"/fao=2
errorcount	"The analysis uncovered !UL error!%S."/fao=1
errornone	"The analysis uncovered NO errors."
errors		"!55<!AS!> !UL error!%S"/fao=2
exefixa		".ADDRESS Reference Fixups (relative to %X'!XL')"/fao=1
exefixaimage	"!UL reference!%S to image !UL:"/fao=2
exefixaline	"!#(10XL)"/fao=2
exefixcount	"shareable image count: !UL"/fao=1
exefixextra	"extra image count: !UL"/fao=1
exefixfixed	"Fixed Information"
exefixflags	"Flags:"
exefixg		"G^ Reference Fixups"
exefixgimage	"!UL reference!%S to image !UL:"/fao=2
exefixgline	"!#(10XL)"/fao=2
exefixlist	"Shareable Image List"
exefixname	<!UL)  "!AC">/fao=2
exefixname0	"!UL)  this image"/fao=1
exefixp		"Protection Change Fixups (relative to %X'!XL')"/fao=1
exefixpsect	"address: %X'!XL', page count: !UL"/fao=2
exefixup	"IMAGE ACTIVATOR FIXUP SECTION"
exefixupnone	"There is no fixup section in this image."
exegst		"SHAREABLE IMAGE - GLOBAL SYMBOL TABLE"
exehdr		"IMAGE HEADER"
exehdractive	"Image Activation Information"
exehdrblkcount	"header block count: !UL"/fao=1
exehdrchancount	"I/O channel count: !UL"/fao=1
exehdrchandef	"I/O channel count: default"
exehdrdececo	"DEC eco levels   1- 98: %X'!XL', %X'!XL', %X'!XL'"/fao=3
exehdrdst	"debug symbol table VBN:  !UL, block count: !UL"/fao=2
exehdrfileid	<image file identification: "!AC">/fao=1
exehdrfixed	"Fixed Header Information"
exehdrflags	"linker flags:"
exehdrgblident	"global section major id: %X'!2<!XL!>', minor id: %X'!-!6XL'"/fao=2
exehdrgst	"global symbol table VBN: !UL, record count: !UL"/fao=2
exehdrident	"Image Identification Information"
exehdrimageid	"image format major id: !AD, minor id: !AD"/fao=2
exehdrisd	"Image Section Descriptors (ISD)"
exehdrisdbase	"base virtual address: %X'!XL' (!AC space)"/fao=2
exehdrisdcount	"page count: !UL"/fao=1
exehdrisdflags	"ISD flags:"
exehdrisdgblnam	<global section name: "!AC">/fao=1
exehdrisdnum	"!UL)  image section descriptor (!UL bytes)"/fao=2
exehdrisdpfcdef	"page fault cluster size: default"
exehdrisdpfcsiz	"page fault cluster size: !UL"/fao=1
exehdrisdtype	"section type: ISD$K_!AC"/fao=1
exehdrisdvbn	"base VBN: !UL"/fao=1
exehdrlinkid	<linker identification: "!AC">/fao=1
exehdrmatch	"match control: !AC"/fao=1
exehdrname	<image name: "!AC">/fao=1
exehdrnopatch	"There are no patches at this time."
exehdrpagecount	"I/O page count: !UL"/fao=1
exehdrpagedef	"I/O page count: default"
exehdrpatch	"Patch Information"
exehdrpatchdate	"last patch date/time: !%D"/fao=1
exehdrpriv	"privilege mask: %X'!XL', %X'!XL'"/fao=2
exehdrropatch	"read-only patch area address:  %X'!XL', length: !UL"/fao=2
exehdrrwpatch	"read/write patch area address: %X'!XL', length: !UL"/fao=2
exehdrsymdbg	"Global Symbol Table & Debug Symbol Table Information"
exehdrsysver	"system version: !AF"/fao=1
exehdrtextvbn	"patch command text VBN: !UL"/fao=1
exehdrtime	"link date/time: !%D"/fao=1
exehdrtypeexe	"image type: executable (IHD$K_EXE)"
exehdrtypelim	"image type: shareable (IHD$K_LIM)"
exehdrusereco	"user eco levels 99-132: %X'!XL'"/fao=1
exehdrxfer1	"first transfer address:  %X'!XL'"/fao=1
exehdrxfer2	"second transfer address: %X'!XL'"/fao=1
exehdrxfer3	"third transfer address:  %X'!XL'"/fao=1
exeheading	"!42<Analyze Image!>   !%D   Page !UL"/fao=2
exepatch	"PATCH TEXT"
flag		"!5<(!UL)!>!16AC !UL"/fao=3
hexdata		"!#<!>!#(3XB)|  !4XW  |!8AF|"/fao=13
hexheading1	"  7  6  5  4  3  2  1  0          01234567"
hexheading2	"------------------------          --------"
interact	"Press RETURN to continue, or enter a period (.) for next file: "
mask		"entry mask: <!AS>"/fao=1
objcprrec	"!UL.  COPYRIGHT HEADER (OBJ$C_HDR_CPR), !UL bytes"/fao=1
objdbgrec	"!UL.  DEBUGGER INFORMATION (OBJ$C_DBG), !UL bytes"/fao=2
objenv		"environment: !UL"/fao=1
objeomflags	"transfer address flags:"
objeomrec	"!UL.  END OF MODULE (OBJ$C_EOM), !UL bytes"/fao=2
objeomsevabt	"severity: abort (!UL)"/fao=1
objeomseverr	"severity: errors (!UL)"/fao=1
objeomsevign	"severity: ignored (!UL)"/fao=1
objeomsevres	"severity: reserved (!UL)"/fao=1
objeomsevsuc	"severity: successful (!UL)"/fao=1
objeomsevwrn	"severity: warnings (!UL)"/fao=1
objeomwrec	"!UL.  END OF MODULE (OBJ$C_EOMW), !UL bytes"/fao=2
objfadpassmech	"passing mechanism: ARG$K_!AC"/fao=1
objgsdenv	"!UL)  Environment Specification (GSD$C_ENV)"/fao=1
objgsdenvflags	"environment flags:"
objgsdenvpar	"!43<parent environment: !UL!><-- environment !UL"/fao=2
objgsdepm	"!UL)  Entry Point Symbol and Mask Definition (GSD$C_EPM)"/fao=1
objgsdepmw	"!UL)  Entry Point Symbol and Mask Definition (GSD$C_EPMW)"/fao=1
objgsdidc	"!UL)  Entity Identity Check (GSD$C_IDC)"/fao=1
objgsdidcent	"entity name: !AF"/fao=1
objgsdidcflags	"identity flags:"
objgsdidcmatch	"match control: IDC$C_!AC"/fao=1
objgsdidcobj	"object name: !AF"/fao=1
objgsdidcvala	"ascii ident: !AF"/fao=1
objgsdidcvalb	"binary ident: %X'!2<!XL!>', %X'!-!6XL'"/fao=1
objgsdlepm	"!UL)  Local Entry Point Symbol and Mask Definition (GSD$C_LEPM)"/fao=1
objgsdlpro	"!UL)  Local Procedure with Formal Argument Definition (GSD$C_LPRO)"/fao=1
objgsdlsy	"!UL)  Local Symbol Specification (GSD$C_LSY)"/fao=1
objgsdpro	"!UL)  Procedure with Formal Argument Definition (GSD$C_PRO)"/fao=1
objgsdprow	"!UL)  Procedure with Formal Argument Definition (GSD$C_PROW)"/fao=1
objgsdpsc	"!UL)  Program Section Definition (GSD$C_PSC)"/fao=1
objgsdpscalign	"!49<alignment: !UL-byte boundary!><-- psect !UL"/fao=2
objgsdpscalloc	"allocation: !UL (%X'!-!XL')"/fao=1
objgsdpscbase	"base address: %X'!XL'"/fao=1
objgsdpscflags	"attribute flags:"
objgsdrec	"!UL.  GLOBAL SYMBOL DIRECTORY (OBJ$C_GSD), !UL bytes"/fao=2
objgsdspsc	"!UL)  Shareable Image Program Section Definition (GSD$C_SPSC)"/fao=1
objgsdsym	"!UL)  Global Symbol Specification (GSD$C_SYM)"/fao=1
objgsdsymw	"!UL)  Global Symbol Specification (GSD$C_SYMW)"/fao=1
objgtxrec	"!UL.  GENERAL TEXT HEADER (OBJ$C_HDR_GTX), !UL bytes"/fao=1
objhdrignrec	"!UL.  IGNORED HEADER (subtype !UL), !UL bytes"/fao=3
objheading	"!42<Analyze Object File!>   !%D   Page !UL"/fao=2
objlitindex	"literal index: !UL"/fao=1
objlnkrec	"!UL.  LINK OPTION SPECIFICATION (OBJ$C_LNK), !UL bytes"/fao=2
objlnmrec	"!UL.  LANGUAGE PROCESSOR HEADER (OBJ$C_HDR_LNM), !UL bytes"/fao=2
objmhdcreate	"creation   date/time: !AS"/fao=1
objmhdname	<module name: "!AF">/fao=1
objmhdpatch	"last patch date/time: !AS"/fao=1
objmhdrec	"!UL.  MODULE HEADER (OBJ$C_HDR_MHD), !UL bytes"/fao=2
objmhdrecsiz	"maximum record size: !UL"/fao=1
objmhdstrlvl	"structure level: !UL"/fao=1
objmhdversion	<module version: "!AF">/fao=1
objmtccorrect	<correction file: "!AF">/fao=1
objmtcinput	<input      file: "!AF">/fao=1
objmtcname	<utility: "!AF">/fao=1
objmtcrec	"!UL.  MAINTENANCE STATUS HEADER (OBJ$C_HDR_MTC), !UL bytes"/fao=2
objmtcseqnum	"sequence number: !UL"/fao=1
objmtcuic	"UIC: [!OB,!OB]"/fao=2
objmtcversion	<version: "!AF">/fao=1
objmtcwhen	"date/time: !AS"/fao=1
objproargcount	"argument count: !UL to !UL"/fao=2
objproargnum	"argument #!UL -"/fao=1
objpsect	"psect: !UL"/fao=1
objsrcrec	"!UL.  SOURCE FILE HEADER (OBJ$C_HDR_SRC), !UL bytes"/fao=1
objstatheading1	"SUMMARY STATISTICS:"
objstatheading2	"Record Type!_Count!_Total Bytes"
objstatline	"OBJ$C_!AC!_!5UL!_!6UL"/fao=3
objstattotal	"Totals!_!_!5UL!_!6UL"/fao=2
objsymbol	<symbol: "!AF">/fao=1
objsymflags	"symbol flags:"
objtirargindex	"argument index: !UL"/fao=1
objtircmd	"!UL)  TIR$C_!AC (!UL, %X'!-!XB')"/fao=3
objtircmdstk	"!56<!UL)  TIR$C_!AC (!UL, %X'!-!XB')!>stack depth: !SL"/fao=4
objtbtrec	"!UL.  TRACEBACK INFORMATION (OBJ$C_TBT), !UL bytes"/fao=1
objtirrec	"!UL.  TEXT INFORMATION/RELOCATION (OBJ$C_TIR), !UL bytes"/fao=1
objtirstoim	"!UL)  Store Immediate, !UB byte!%S:"/fao=2
objtirvield	"vield: position !UL, size !UL"/fao=2
objttlrec	"!UL.  TITLE HEADER (OBJ$C_HDR_TTL), !UL bytes"/fao=1
objvalue	"value: !SL (%X'!-!XL')"/fao=1
objuvalue	"unsigned value: !UL (%X'!-!XL')"/fao=1
protection	"protection: PRT$C_!AC"/fao=1
severity	"severity code: STS$K_!AC"/fao=1
text		<"!AF">/fao=1
texthdr		"Textual information:"

	.severity	warning
nosuchmod	"library !AS does not contain !AS"/fao=2

	.severity	error
baddate		"!ASDate is not in the correct 17-byte format (dd-mmm-yyyy hh:mm)."/fao=1
badseverity	"!ASSeverity code (!UL) is reserved to Digital."/fao=1
badsym1st	"!ASFirst character of symbol cannot be a digit."
badsymchar	"!ASSymbol contains invalid character(s)."
badsymlen	"!ASLength of symbol is not within valid range of 1 to !UL."/fao=1
exebadfixupend	"!ASFixup information runs off the end of the fixup section."/fao=1
exebadfixupisd	"!ASFixup ISD specifies zero VBN or block count."/fao=1
exebadfixupvbn	"!ASFixup section does not fit within image file (VBN: !UL, blocks: !UL)."/fao=3
exebadisds1	"!ASThere is no such thing as S1 space."/fao=1
exebadisdtype	"!ASSection type code (!UL) is invalid."/fao=2
exebadmatch	"!ASMatch control value (!UL) is invalid."/fao=2
exebadpatchlen	"!ASPatch command line is longer than !UL characters."/fao=2
exebadobj	"!ASObject record !UL (type !UL) is invalid in an image."/fao=3
exebadtype	"!ASImage type code (!UL) is invalid."/fao=2
exebadxfer0	"!ASTransfer address list does not end with a zero."/fao=1
exehdrisdlong	"!ASISD extends beyond end of header block."/fao=1
exehdrlong	"!ASHeader does not fit within file allocation."/fao=1
exeisdlendzro	"!ASISD extends beyond format for demand-zero section."/fao=1
exeisdlengbl	"!ASISD extends beyond format for global section."/fao=1
exeisdlenpriv	"!ASISD extends beyond format for private section."/fao=1
exenotnative	"!ASThis file is not a VAX/VMS native image."/fao=1
extrabytes	"!ASSpurious bytes are present at the end of the record."/fao=1
fieldfit	"!ASObject record is not large enough to accomodate mandatory fields."/fao=1
flagerror	"!ASReserved flag bit !UL is set."/fao=1
notok		"At least one error occurred."
objbadidcmatch	"!ASInvalid identity match control value (!UL)."/fao=2
objbadnum	"!AS!_!UL"/fao=2
objbadpop	"!ASToo many longwords have been popped from the stack."/fao=1
objbadpush	"!ASThe stack still contains !UL longword!%S."/fao=2
objbadtype	"!ASObject record !UL contains invalid type code !UL:"/fao=3
objbadvield	"!ASVield cannot be longer than 8 bits and cannot cross a byte boundary."/fao=1
objeombadsev	"!ASReserved severity code."/fao=1
objeommissing	"!ASEnd of module record is missing from previous module."/fao=1
objfadbadavc	"!ASSpurious bits set in argument validation control byte."/fao=1
objfadbadrbc	"!ASNon-zero remaining byte count."/fao=1
objgsdbadalign	"!ASPsect alignment is greater than maximum alignment of !UL."/fao=2
objgsdbadsubtyp	"!ASGSD record subtype !UL invalid.  Remainder of record ignored:"/fao=2
objhdrres	"!ASObject record !UL is a reserved header, subtype !UL."/fao=3
objmhdbadrecsiz	"!ASMaximum record size is too large.  Allowable size is up to !UL bytes."/fao=2
objmhdbadstrlvl	"!ASSpecified structure level is unsupported.  Highest supported level is !UL."/fao=1
objmhdmissing	"!ASModule header record is missing."/fao=1
objnontircmd	"!ASThe above command is only valid in Debugger and Traceback records."/fao=1
objnopsc	"!ASNo psects were defined in this module."/fao=1
objnullrec	"!ASObject record !UL has a length of zero."/fao=2
objp0space	"!ASThe above item will result in a reference outside of P0 space."/fao=1
objprominmax	"!ASMinimum argument count is greater than maximum."/fao=1
objpscabslen	"!ASThe allocation for an absolute psect must be zero."/fao=1
objrectoobig	"!ASObject record is longer than maximum size in module header (!UL bytes)."/fao=2
objtirres	"!ASReserved command !UL encountered.  Remainder of record ignored:"/fao=1
objundefenv	"!ASThe following environments were referenced but not defined:"/fao=1
objundeflit	"!ASThe specified literal has not been defined."/fao=1
objundefpsc	"!ASThe following psects were referenced but not defined:"/fao=1

	.severity	fatal

	.end
