	.title	RMS_Messages Messages for ANALYZE/RMS_FILE

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

	.facility	analyze,177/prefix=anl$_/system

	.severity	success
ok		"Normal successful completion."

	.severity	informational
alloc		"Blocks Allocated: !UL, Default Extend Size: !UL"
anything	"!AS"
backup		"!16<Backup Date:!> !%D"
bkt		"BUCKET HEADER (VBN !UL)"
bktarea		"Area Number: !UL"
bktcheck	"Check Character: %X'!XB'"
bktflags	"Bucket Header Flags:"
bktfree		"Free Space Offset: %X'!XW'"
bktkey		"Key of Reference: !UL"
bktlastbkt	"Last Continuation VBN: !UL"
bktlevel	"Level: !UL"
bktnext		"Next Bucket VBN: !UL"
bktptrsize	"Bucket Pointer Size: !UL"
bktrecid	"Free Record ID Range: !UL - !UL"
bktrecid3	"Free Record ID: !UL"
bktsample	"VBN Sample: !UL"
bktvbnfree	"VBN Free Space Offset: %X'!XW'"
bucketsize	"Bucket Size: !UL"
cell		"RECORD CELL (VBN !UL, offset %X'!XW'):"
celldata	"Record Bytes:"
cellflags	"Cell Control Flags:"
checkhdg	"!42<Check RMS File Integrity!>   !%D   Page !UL"
contig		"!20<Contiguity Options:!> !AC"
creation	"!16<Creation Date:!> !%D"
ctlsize		"Fixed Control Size: !UL"
datarec		"DATA BYTES (VBN !UL, offset %X'!XW'):"
databktvbn	"First Data Bucket VBN: !UL"
dumpheading	"DUMP OF VIRTUAL BLOCK !UL:"
eof		"End-of-File VBN: !UL, Offset: %X'!XW'"
errorcount	"The analysis uncovered !UL error!%S."
errornone	"The analysis uncovered NO errors."
errors		"!55<!AS!> !UL error!%S"/fao=2
expiration	"!16<Expiration Date:!> !%D"
fileattr	"RMS FILE ATTRIBUTES"
filehdr		"FILE HEADER"
fileid		"File ID: (!UL,!UL,!UL)"
fileorg		"File Organization: !AC"
filespec	"File Spec: !AS"
flag		"!5<(!UL)!>!16AC !UL"
globalbufs	"Global Buffer Count: !UL"
hexdata		"!#<!>!#(3XB)|  !4XW  |!8AF|"
hexheading1	"  7  6  5  4  3  2  1  0          01234567"
hexheading2	"------------------------          --------"
idxarea		"AREA DESCRIPTOR #!UL (VBN !UL, offset %X'!XW')"
idxareaalign	"Alignment: !AC"
idxareabktsz	"Bucket Size: !UL"
idxareaflags	"Alignment Flags:"
idxareanext	"Next Extent Start: !UL, Blocks: !UL"
idxareaqty	"Default Extend Quantity: !UL"
idxarearecl	"Reclaimed Bucket VBN: !UL"
idxarearelid	"Related File ID: (!UL,!UL,!UL)"
idxareaused	"Current Extent Start: !UL, Blocks: !UL, Used: !UL, Next: !UL"
idxkey		"KEY DESCRIPTOR #!UL (VBN !UL, offset %X'!XW')"
idxkeyareas	"Index Area: !UL, Level 1 Index Area: !UL, Data Area: !UL"
idxkeybktsz	"Index Bucket Size: !UL, Data Bucket Size: !UL"
idxkeybytes	"Key:"
idxkey1type	"!19<Data Type:!> !AC"
idxkeydatavbn	"First Data Bucket VBN: !UL"
idxkeyfill	"Index Fill Quantity: !UL, Data Fill Quantity: !UL"
idxkeyflags	"Key Flags:"
idxkeykeysz	"Key Size: !UL"
idxkeyname	"Name: !AD"
idxkeynext	"Next Key Descriptor VBN: !UL, Offset: %X'!XW'"
idxkeyminrec	"Minimum Record Size: !UL"
idxkeynull	"Null Character: %X'!XB'"
idxkeyposs	"!19<Segment Positions:!> !#(10UL)"/fao=9
idxkeyrootlvl	"Root Level: !UL"
idxkeyrootvbn	"Root VBN: !UL"
idxkeysegs	"Key Segments: !UL"
idxkeysizes	"!19<Segment Sizes:!> !#(10UL)"/fao=9
idxprimrec	"PRIMARY DATA RECORD (VBN !UL, offset %X'!XW')"
idxprimrecflags	"Record Control Flags:"
idxprimrecid	"Record ID: !UL"
idxprimreclen	"Data Record Length: !UL"
idxprimrecrrv	"RRV ID: !UL, !UL-Byte Bucket Pointer: !UL"
idxproareas	"Number of Areas: !UL, VBN of First Descriptor: !UL"
idxprolog	"FIXED PROLOGUE"
idxrec		"INDEX RECORD (VBN !UL, offset %X'!XW')"
idxrecptr	"!UL-Byte Bucket Pointer: !UL"
idxsidr		"SIDR RECORD (VBN !UL, offset %X'!XW')"
idxsidrflags	"Control Flags:"
idxsidrrecid	"Record ID: !UL"
idxsidrptrflags	"sidr pointer control flags:"
idxsidrptrref	"sidr pointer record id: !UL, !UL-byte record VBN: !UL"
intercommand	"ANALYZE> !AS"
interhdg	"!42<Interactive Analysis of RMS File!>   !%D   Page !UL"
longrec		"Longest Record: !UL"
maxrecsize	"Maximum Record Size: !UL"
nobackup	"!16<Backup Date:!> none posted"
noexpiration	"!16<Expiration Date:!> none specified"
nospanfiller	"NOSPAN BLOCK FILLER (VBN !UL, offset %X'!XW')"
perform		"!20<Performance Options:!> !AC"
prologflags	"Prologue Flags:"
prologver	"Prologue Version: !UL"
prot		"Protection:  System: !AC, Owner: !AC, Group: !AC, World: !AC"
recattr		"Record Attributes: !AC  !AC"
recfmt		"Record Format: !AC"
reclaimbkt	"RECLAIMED BUCKET (VBN !UL)"
relbucket	"DATA BUCKET (VBN !UL)"
releofvbn	"End-of-File VBN: !UL"
relmaxrec	"Maximum Record Number: !UL"
relprolog	"FIXED PROLOGUE"
reliab		"!20<Reliability Options:!> !AC"
revision	"!16<Revision Date:!> !%D, Number: !UL"
stathdg		"!42<RMS File Statistics!>   !%D   Page !UL"
owneruic	"Owner UIC: [!3OL,!3OL]"

! The following messages are used in response to interactive commands.

attop		"You are already at the top of the file structure."
badcmd		"Invalid command entered.  Please try again."
badpath		"You have specified an invalid path name.  Please try again."
badvbn		"You have specified an invalid VBN.  Please try again."
downhelp	"The following is a list of paths down from this structure:"
downpath	"!15AC!AC"/fao=2
emptybkt	"This data bucket is empty."
nodata		"This record does not contain actual data bytes."
nodown		"There are no paths down from this structure."
nonext		"There is no structure following the current one."
noreclaimed	"There are no reclaimed buckets on the available chain."
norecs		"There are no data records in this file."
norrv		"This record does not contain an RRV."
restdone	"All structures at this level have been displayed."
stackfull	"Implementation restriction: you cannot go any deeper into the file structure."
uninitindex	"This index has not been initialized."

! The following messages are used to generate an FDL file.  They are in the
! order they will appear in the file.

fdlident	"IDENT!_!20%D!_VAX-11 ANALYZE/RMS_FILE Utility"
fdlsystem	"SYSTEM"
fdlsource	"!24<SOURCE!>VAX/VMS"
fdlfile		"FILE"
fdlalloc	"!24<ALLOCATION!>!UL"
fdlbesttry	"!24<BEST_TRY_CONTIGUOUS!>!AC"
fdlbucketsize	"!24<BUCKET_SIZE!>!UL"
fdlcontig	"!24<CONTIGUOUS!>!AC"
fdlextension	"!24<EXTENSION!>!UL"
fdlglobalbufs	"!24<GLOBAL_BUFFER_COUNT!>!UL"
fdlmaxrecord	"!24<MAX_RECORD_NUMBER!>!UL"
fdlfilename	"!24<NAME!>!AS"
fdlorg		"!24<ORGANIZATION!>!AC"
fdlowner	"!24<OWNER!>[!3OW,!3OW]"
fdlprotection	"!24<PROTECTION!>(system:!AC, owner:!AC, group:!AC, world:!AC)"
fdlreadcheck	"!24<READ_CHECK!>!AC"
fdlwritecheck	"!24<WRITE_CHECK!>!AC"
fdlrecord	"RECORD"
fdlspan		"!24<BLOCK_SPAN!>!AC"
fdlcc		"!24<CARRIAGE_CONTROL!>!AC"
fdlvfcsize	"!24<CONTROL_FIELD_SIZE!>!UL"
fdlformat	"!24<FORMAT!>!AC"
fdlsize		"!24<SIZE!>!UL"
fdlarea		"AREA !UL"
fdlkey		"KEY !UL"
fdlchanges	"!24<CHANGES!>!AC"
fdldataarea	"!24<DATA_AREA!>!UL"
fdldatafill	"!24<DATA_FILL!>!UL"
fdldatakeycompb	"!24<DATA_KEY_COMPRESSION!>!AC"
fdldatareccompb	"!24<DATA_RECORD_COMPRESSION!>!AC"
fdldups		"!24<DUPLICATES!>!AC"
fdlindexarea	"!24<INDEX_AREA!>!UL"
fdlindexcompb	"!24<INDEX_COMPRESSION!>!AC"
fdlindexfill	"!24<INDEX_FILL!>!UL"
fdll1indexarea	"!24<LEVEL1_INDEX_AREA!>!UL"
fdlkeyname	"!24<NAME!>!AF"
fdlnorecs	"!! This index is uninitialized; there are no records."
fdlnullkey	"!24<NULL_KEY!>!AC"
fdlnullvalue	"!24<NULL_VALUE!>!UL"
fdlprolog	"!24<PROLOGUE!>!UL"
fdlseglength	"!24<SEG!UL_LENGTH!>!UL"
fdlsegpos	"!24<SEG!UL_POSITION!>!UL"
fdlsegtype	"!24<TYPE!>!AC"
fdlanalarea	"ANALYSIS_OF_AREA !UL"
fdlrecl		"!24<RECLAIMED_SPACE!>!UL"
fdlanalkey	"ANALYSIS_OF_KEY !UL"
fdldatakeycomp	"!24<DATA_KEY_COMPRESSION!>!SL"
fdldatareccomp	"!24<DATA_RECORD_COMPRESSION!>!SL"
fdldatarecs	"!24<DATA_RECORD_COUNT!>!UL"
fdldataspace	"!24<DATA_SPACE_OCCUPIED!>!UL"
fdldepth	"!24<DEPTH!>!UL"
fdldupsper	"!24<DUPLICATES_PER_SIDR!>!UL"
fdlidxcomp	"!24<INDEX_COMPRESSION!>!SL"
fdlidxfill	"!24<INDEX_FILL!>!UL"
fdlidxspace	"!24<INDEX_SPACE_OCCUPIED!>!UL"
fdldatalenmean	"!24<MEAN_DATA_LENGTH!>!UL"
fdlidxlenmean	"!24<MEAN_INDEX_LENGTH!>!UL"

! The following messages are used to generate a statistics report.

statarea	"STATISTICS FOR AREA #!UL"
statrecl	"!30<Count of Reclaimed Blocks:!>!6UL"
statkey		"STATISTICS FOR KEY #!UL"
statdepth	"!30<Number of Index Levels:!>!6UL"
statidxlenmean	"!30<Mean Length of Index Entry:!>!6UL"
statidxspace	"!30<Count of Index Blocks:!>!6UL"
statidxfill	"!30<Mean Index Bucket Fill:!>!6UL%"
statidxcomp	"!30<Mean Index Entry Compression:!>!6SL%"
statdatarecs	"!30<Count of Data Records:!>!6UL"
statdupsper	"!30<Mean Duplicates Per SIDR:!>!6UL"
statdatalenmean	"!30<Mean Length of Data Record:!>!6UL"
statdataspace	"!30<Count of Data Blocks:!>!6UL"
statdatafill	"!30<Mean Data Bucket Fill:!>!6UL%"
statdatakeycomp	"!30<Mean Data Key Compression:!>!6SL%"
statdatareccomp	"!30<Mean Data Record Compression:!>!6SL%"
statefficiency	"!30<Overall Space Efficiency:!>!6UL%"

	.severity	warning

	.severity	error
badarea1st2	"!ASVBN !UL:  First two bytes must be zero in area descriptor #!UL."
badareaalign	"!ASVBN !UL:  Invalid allocation alignment !UL present in area descriptor #!UL."
badareabktsize	"!ASVBN !UL:  Invalid bucket size !UL present in area descriptor #!UL."
badareafit	"!ASVBN !UL:  File is too short to contain all area descriptors."
badareaid	"!ASVBN !UL:  Area ID #!UL does not match position of area descriptor #!UL."
badareanext	"!ASVBN !UL:  Invalid next extent information in area descriptor #!UL."
badarearfi	"!ASVBN !UL:  Invalid related file ID present in area descriptor #!UL."
badarearoot	"!ASVBN !UL:  Information for locating area descriptors from prologue is invalid."
badareaused	"!ASVBN !UL:  Invalid current extent information present in area descriptor."
badbktareaid	"!ASVBN !UL:  Invalid area ID in bucket header."
badbktcheck	"!ASVBN !UL:  Bucket check byte is out of phase."
badbktfree	"!ASVBN !UL:  Invalid first free byte offset in bucket header."
badbktkeyid	"!ASVBN !UL:  Invalid key of reference in bucket header."
badbktlevel	"!ASVBN !UL:  Invalid level number in bucket header."
badbktrootbit	"!ASVBN !UL:  BKT$V_ROOTBKT flag in index bucket header is not correct."
badbktsample	"!ASVBN !UL:  Invalid bucket address sample in bucket header."
badcellfit	"!ASVBN !UL:  Record is too large to fit in record cell."
badchecksum	"!ASVBN !UL:  Prologue block checksum is invalid."
baddatarecfit	"!ASVBN !UL:  Data record spills over into free space of bucket."
baddatarecps	"!ASVBN !UL:  Pointer size of 3 is invalid in data record."
bad3idxkeyfit	"!ASVBN !UL:  Key spills over into free key space of bucket."
badidxlastkey	"!ASVBN !UL:  Last key in index bucket is not key specified by parent record."
badidxorder	"!ASVBN !UL:  Index records are out of order in index bucket."
badidxrecbits	"!ASVBN !UL:  Unused control bits in index record are not zero."
badidxrecfit	"!ASVBN !UL:  Index record spills over into free space of bucket."
badidxrecps	"!ASVBN !UL:  Pointer size of 3 is invalid in index record."
badkeyareaid	"!ASVBN !UL:  Invalid area ID in key descriptor #!UL."
badkeydatabkt	"!ASVBN !UL:  Invalid data bucket size in key descriptor #!UL."
badkeydatatype	"!ASVBN !UL:  Invalid data type code (!UL) in key descriptor #!UL."
badkeyidxbkt	"!ASVBN !UL:  Invalid index bucket size in key descriptor #!UL."
badkeyfill	"!ASVBN !UL:  Invalid fill quantities in key descriptor #!UL."
badkeyfit	"!ASVBN !UL:  Key descriptor #!UL does not fit in block."
badkeyrefid	"!ASVBN !UL:  Key of reference ID out of sequence in key descriptor #!UL."
badkeyrootlevel	"!ASVBN !UL:  Invalid index root level in key descriptor #!UL."
badkeysegcount	"!ASVBN !UL:  Invalid key segment count (!UL) in key descriptor #!UL."
badkeysegvec	"!ASVBN !UL:  Segment vectors contain spurious items in key descriptor #!UL."
badkeysummary	"!ASVBN !UL:  Invalid key size or minimum record length in key descriptor #!UL."
badreadnopar	"!ASAttempt to read block with invalid VBN !UL."
badreadpar	"!ASVBN !UL:  Structure references block with invalid VBN !UL."
badsidrdupct	"!ASVBN !UL:  Incorrect duplicate count in SIDR record."
badsidrptrfit	"!ASVBN !UL:  SIDR pointer extends past end of SIDR record."
badsidrptrsz	"!ASVBN !UL:  Duplicate count field size must be 1 in SIDR record."
badsidrsize	"!ASVBN !UL:  Invalid key/pointer size field in SIDR record."
badstreameof	"!ASVBN !UL:  Last stream record does not contain a delimiter."
badvbnfree	"!ASVBN !UL:  VBN free space offset is invalid."
bktloop		"!ASVBN !UL:  The bucket chains for key #!UL contain a loop."
extenderr	"!ASAn error had occurred while extending this file."
flagerror	"!ASVBN !UL:  Reserved flag bit !UL is set."
missingbkt	"!ASVBN !UL:  Index bucket references missing data bucket with VBN !UL."
notok		"At least one error occurred."
p3sidr		"Prologue 3 secondary keys are not supported in VMS V3.0."
spanerror	"!ASVBN !UL:  Record illegally spans a block."
toomanyrecs	"!ASThe file contains more records than the maximum specified in the prologue."
unwind		"!ASDrastic structure error precludes further analysis."
vfctooshort	"!ASVBN !UL:  Record not long enough to accomodate fixed control header."

	.severity	fatal
cachefull	"system error: bucket cache full"
cacherelfail	"system error: released bucket not in cache"

	.end
