! REQUIRE file for VAX-11 Common Run-Time Procedure Library error condition values/message IDs
! File: APLMSG.MDL, Version 'V03-000', RAMG, 20-Mar-79
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! Author: R. Gottlieb

!+
! For ease of maintainence, the symbols are arranged in the same order as
! in APLSF on the DECsystem-20.  In general, symbols are defined following
! the standard for global names:
!
!	APL$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
! The names of all procedures using each error condition value should appear
! in the comments included with each error definition.
!

! MACRO-32 Programming:
!
! The macros call:
!
!	$APLDEF
!
! will cause all symbols to be made available to the module.
! The STS$V_MSG_ID is the APL error number.
! These symbols are declared EXTERNAL by the Run-time Library,
! the macros are provided only for the convenience of the user.

!-




!			; Make all errors be warning (except as noted)

!			; Set sub-system specific bit and make WARNING
!			; Set LH to 35 (decimal).

	.FACILITY	APL,35 /SYSTEM
	.SEVERITY	ERROR

	WSNOTFOU	<workspace not found>

!			; Set sub-system specific bit and make ERROR


	.SEVERITY	FATAL

	SYSERR		<system error>

!			; Set sub-system specific bit and make WARNING


	.SEVERITY	ERROR

	WSFULL		<workspace full>
	ILLSYSVAR	<illegal system variable or function>
	DEFERR		<definition error>
	LABERR		<label error>
	SYNERR		<syntax error>
	INDERR		<index error>
	RANERR		<rank error>
	LENERR		<length error>
	VALERR		<value error>
	RNGERR		<range error>
	SIDAMN		<possible si damage>
	DPTERR		<depth error>
	DOMERR		<domain error>
	UNBDEL		<unbalanced delimiter>
	EDIERR		<edit error>
	ATTSIG		<attention signaled>
	
!			; Set sub-system specific bit and make WARNING

	.BASE		21

	INCCOM		<incorrect command>
	INCPAR		<incorrect parameter>
	WSLOCK		<ws locked>
	NOTGRONAM	<not grouped, name in use>

!			; Set sub-system specific bit and make WARNING

	.BASE		47

	LINTOOLON	<line too long to edit>

!			; Set sub-system specific bit and make ERROR (not WARNING)

	.SEVERITY	FATAL
	.BASE		57

	FILNOTWS	<file does not contain a workspace>

!			; Set sub-system specific bit and make WARNING

	.SEVERITY	ERROR
	.BASE		59

	FILALREXI	<file already exists with given name>
	WSNOTSAV	<ws not saved, this ws is !AS> /FAO=1

!			; Set sub-system specific bit and make WARNING

	.BASE		64

	CHANOTASS	<channel not assigned>
	CANDOBOTH	<cannot do both input and output>
	CANINPFIL	<cannot input from file>
	CANOUTFIL	<cannot output to file>

	.END

! End of file APLMSG.MDL 
