!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! DEFINE COBOL 74 ERROR/STATUS VALUES
!
 
 

	.FACILITY	C74,29 /SYSTEM
	.SEVERITY	WARNING

	SUBOUTRAN	<subscript out of range>
	OCCDEPVAL	<OCCURS DEPENDING value out of range>
	RETEXTOUT	<PERFORM exited out of order>
	RECPERDET	<recursive PERFORM detected>
	NULGOTO		<null GO TO executed has not been ALTERed>
	COMGENABO	<compiler generated abort>
	RECCALDET	<recursive CALL detected>
	NUMARGCAL	<number of arguments in CALL incorrect>
	PERCOUTOO	<PERFORM counter too large>
	EXPTOOLAR	<exponent too large>
	FILALROPN	<file: !AS (!AS) already open> /FAO=2
	FINNOTOPN	<file: !AS (!AS) not open> /FAO=2
	INVOPEFIL	<invalid operation on file: !AS (!AS)> /FAO=2
	REANOTPRE	<read not preceded by rewrite or delete on file: !AS (!AS)> /FAO=2
	FILPRELOC	<file: !AS (!AS) previously locked> /FAO=2
	ERRCLOUNI	<error in CLOSE UNIT or REEL on file: !AS (!AS) > /FAO=2
	OPNERRFIL	<OPEN error on file: !AS (!AS) > /FAO=2
	CLOERRFIL	<CLOSE error on file: !AS (!AS) > /FAO=2
	NOTOPNOPR	<file: !AS (!AS) not open for operation> /FAO=2
	INVLINVAL	<invalid LINAGE value on file: !AS (!AS)> /FAO=2
	NOEOFPRO	<no EOF processing on file: !AS (!AS)> /FAO=2
	REAERRFIL	<READ error on file: !AS (!AS) > /FAO=2
	WRIERRFIL	<WRITE error on file: !AS (!AS) > /FAO=2
	REWERRFIL	<REWRITE error on file: !AS (!AS) > /FAO=2
	DELERRFIL	<DELETE error on file: !AS (!AS) > /FAO=2
	STAERRFIL	<START error on file: !AS (!AS) > /FAO=2
	UNLERRFIL	<UNLOCK error on file: !AS (!AS) > /FAO=2
	BADFILNAM	<bad file name: !AS (!AS)> /FAO=2
	SAMAREUSE	<SAME AREA already in use when opening file: !AS (!AS)> /FAO=2
	OPNCOBOUT	<error opening !AS > /FAO=1
	OPNCOBIN	<error opening !AS > /FAO=1
	ERRDIS		<error in DISPLAY (!AS) > /FAO=1
	ERRACC		<error in ACCEPT (!AS) > /FAO=1
	INVDATDEC	<invalid data in decimal data-item (location = ^X!XL)> /FAO=1

	.END
