!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! Error message definitions for CORAL RUN-TIME LIBRARY
!
!
!
! define SEVERE ERROR message codes
!
	.FACILITY	COR,34 /SYSTEM
	.SEVERITY	FATAL
	.BASE		337

	SEVERROR1	<Severe error 1>
	SEVERROR2	<Severe error 2>
	SEVERROR3	<Severe error 3>
	SEVERROR4	<Severe error 4>
	SEVERROR5	<Severe error 5>
!
! Define INFO message codes
!

	.SEVERITY	INFORMATIONAL
	.BASE		1

	LUNALRCLO	<Lun already closed>
	RECLDIFCR	<Record length differs from create time>
	INFORM1		<Information 1>
	INFORM2		<Information 2>
	INFORM3		<Information 3>
	INFORM4		<Information 4>
	INFORM5		<Information 5>
!
! Define WARNING message codes
!

	.SEVERITY	WARNING
	.BASE		257

	INPCONERR	<Input conversion error>
	OUTCONERR	<Output conversion error>
	NODABEDEL	<No data before delimiter>
	WARNING1	<Warning 1>
	WARNING2	<Warning 2>
	WARNING3	<Warning 3>
	WARNING4	<Warning 4>
	WARNING5	<Warning 5>
!
! Define ERROR message codes
!

	.SEVERITY	ERROR
	.BASE		513

	LUNNOTOPE	<Lun not open>
	LUNOUTRAN	<Lun out of range>
	ATTEXTZER	<Attempted to extend by zero blocks>
	INVMODCRE	<Invalid mode for create>
	LUNALROPE	<Lun already open>
	LUNALRATT	<Lun already attached>
	LUNNOTATT	<Lun not attached>
	INVFUNOPE	<Invalid function for open>
	NULL1		<Not in use>
	NULL2		<Not in use>
	INVMODOPE	<Invalid mode for open>
	ATTEXTUFL	<Attempted to extend unopened file>
	NOTOPEREC	<Not opened for record i/o>
	NOTOPESTI	<Not opened for stream input>
	NOTOPESTO	<Not opened for stream output>
	NOTOPEBLO	<Not opened for block i/o>
	INVSIGLEV	<Invalid signal level>
	INVFORSTG	<Invalid format string>
	NOASYOPER	<No asynchronous operation pending>
	INVPROSTG	<Invalid protection string>
	INVRECATR	<Invalid record attributes>
	INVCONMOD	<Invalid conversion mode>
	ERROR1		<Error 1>
	ERROR2		<Error 2>
	ERROR3		<Error 3>
	ERROR4		<Error 4>
	ERROR5		<Error 5>
!
! Define SUCCESS message codes
!

	.SEVERITY	SUCCESS
	.BASE		81

	SUCCESS		<Successful operation>
	SUCCESS1	<Success 1>
	SUCCESS2	<Success 2>
	SUCCESS3	<Success 3>
	.END
!
! End of definition file
!
