! MOUNTMSG.MDL - system message file for MOUNT and DISMOUNT utilities
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for the DISMOUNT utility messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFIED BY:
!
!	0105	STJ0011		Steven T. Jeffreys,	14-Oct-1980
!		Add operator assisted mount error messages.
!
!	0104	ACG0123		Andrew C. Goldstein,	17-Jan-1980  19:52
!		Integrate disk rebuild with MOUNT
!
!	0103	ACG0079		Andrew C. Goldstein,	4-Nov-1979  17:32
!		Add messages related to write-back cacheing
!
!	 0102	ACG0044		Andrew C. Goldstein,  18-Jun-1979  13:31
!	Add disk quota support
!
!	 0101	ACG0003		Andrew C. Goldstein,  29-Dec-1978  13:01
!	Add messages for multi-volume disk
!
!**

!+
!
! THE FOLLOWING ARE MESSAGES ISSUED BY THE DISMOUNT UTILITY
!
!-



	.FACILITY	DISM,115 /SYSTEM /MACRO=$$DISMOUDEF
	.SEVERITY	FATAL

	MAXDEV		<too many devices>
	SYSDEV		<The system device cannot be dismounted>
	.END
