! MOUNTMSG.MDL - system message file for MOUNT and DISMOUNT utilities
!
!	Version 'V03-001'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for the MOUNT utility messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFIED BY:
!
!	V03-001	STJ0241		Steven T. Jeffreys	28-Mar-1982
!		Added RQSTDON message.
!
!	0111	STJ0211		Steven T. Jeffreys	11-Feb-1982
!		Added support for user comments to the operator request.
!
!	0110	DMW0014		David Michael Walp	16-Aug-1981
!		Added MOUNEWVOL and REMOUVOL and changed /ANSI to /LABEL
!
!	0109	STJ0085		Steven T. Jeffreys	4-Aug-1981
!		Added WRONGVOL message for operator assisted mount support.
!
!	0108	DMW0013		David Michael Walp	4-Aug-1981
!		Added "/FAO=2" to WRITELCK
!
!	0107	STJ0034		Steven T. Jeffreys,	4-May-1981
!		Added more messages for operator assisted mount.
!
!	0106	DMW0001		David Michael Walp,	10-Mar-1981
!		Added /ANSI error.  Init common error.  Not used yet.
!
!	0105	STJ0011		Steven T. Jeffreys,	14-Oct-1980
!		Add operator assisted mount error messages.
!
!	0104	ACG0123		Andrew C. Goldstein,	17-Jan-1980  19:52
!		Integrate disk rebuild with MOUNT
!
!	0103	ACG0079		Andrew C. Goldstein,	4-Nov-1979  17:32
!		Add messages related to write-back cacheing
!
!	 0102	ACG0044		Andrew C. Goldstein,  18-Jun-1979  13:31
!	Add disk quota support
!
!	 0101	ACG0003		Andrew C. Goldstein,  29-Dec-1978  13:01
!	Add messages for multi-volume disk
!
!**

!+
!
! THE FOLLOWING ARE MESSAGES ISSUED BY THE MOUNT UTILITY.
!
!-



!
! ***** Following messages are shared with INIT
!
	.FACILITY	MOUNT,114 /SYSTEM /PREFIX=MOUN$_ /MACRO=$$MOUNDEF
	.SEVERITY	FATAL

	BADDATCHK	<invalid keyword on /DATACHECK qualifier>
	BADDENS		<unknown value on /DENSITY qualifier>
	BADPRO		<invalid syntax on /PROTECTION qualifier>
	BADUIC		<invalid UIC syntax>
	CONFQUAL	<conflicting qualifiers>
	ILLOPT		<qualifier(s) not appropriate to this device>
	NONLOCAL	<device is not a local device>
	NOTRAN		<logical name cannot be translated>
	UNKDEV		<unknown device type>
	BADLABELQ	<invalid keyword on /LABEL qualifier>
	.LITERAL	MOUN$_D2=7503964
	.LITERAL	MOUN$_D3=7503972
	.LITERAL	MOUN$_D4=7503980
	.LITERAL	MOUN$_D5=7503988
!
! ***** Preceding messages are shared with INIT
!

	.BASE		15

	LOGNAME		<logical name is too long>
	MAXDEV		<too many devices>
	MAXLAB		<too many volume labels>
	NOACPDEV	<device named by /PROCESSOR:SAME has no ACP>
	MOUVOL		<MOUNT relative volume !ZB (!AD) on !AC!UW:!/> /FAO=5
	INCOMPACP	<indicated ACP is incompatible with volume>
	INCOMPAT	<qualifiers incompatible with already mounted volume>
	VOLALRMNT	<another volume of same label already mounted>
	BADVOL1		<bad VOL1 ANSI label>
	.LITERAL	MOUN$_ILLDENS=7504068

	.BASE		25

	NOTGENDEV	<not a generic device>
	DUPDEVSPC	<duplicate device specified>
	ILLANSIBS	<ANSI magnetic tape block size must be at least 18 characters>
	ACCERR		<non-blank accessibility field in volume labels on !AC!UW:!/> /FAO=2
	FILNOTEXP	<file not expired on volume on !AC!UW:!/> /FAO=2
	NOPRIV		<user denied privilege to write to volume on !AC!UW:!/> /FAO=2
	NOTANSI		<not ANSI volume on !AC!UW:!/> /FAO=2
	NOTLABEL	<(!AD) not on !AC!UW:!/> /FAO=4
	NOTVOLSET	<volume on !AC!UW: not in volume set !AD!/> /FAO=4
	NOTRELVOL	<Relative volume !ZB not on !AC!UW:!/> /FAO=3
	OFFLINE		<!AC!UW: offline> /FAO=2
	IOERROR		<I/O error initializing volume on !AC!UW:!/> /FAO=2
	ILLQUAL		<invalid qualifier>
	WRITLCK		<volume on !AC!UW: is write locked!/> /FAO=2
	RECGTRBL	<record size is greater than block size>
	ACPNAME		<ACP file name is too long>
	ACPTIME		<ACP does not respond>
	AQBTIME		<ACP queue is unstable>
	BADACP		<invalid syntax on /PROCESSOR qualifier>
	BADEBC		<unknown keyword on /EBCDIC qualifier>
	BADOVR		<unknown keyword on /OVERRIDE qualifier>
	DEVICES		<only one device allowed>
	SZTOOBIG	<record size or block size greater than 65534>
	INCONSDEV	<inconsistent device types>
	DEVCOUNT	<number of devices must match number of volumes>
	VOLINSET	<volume is already part of another volume set>
	RVN1NOTMT	<root volume is not mounted>
	SETLIMIT	<too many volumes in volume set>
	DUPVOLNAM	<volume label already present in set>
	HOMBLKCHK	<home block software consistency error>
	DUPRVN		<duplicate volume number already mounted>
	BADCACHE	<invalid syntax on /CACHE qualifier>
	UNRELVOL	<volume is not part of volume set being mounted>
	MBXCRERR	<error creating operator reply mailbox>
	MBXRDERR	<error reading operator reply mailbox>
	BADREPLY	<unknown type of operator reply, reply = !XW!XW!XL!AF> /FAO=5
	OPRSNDERR	<error sending request to operator>
	OPRABORT	<mount aborted by operator>
	BATCHNOOPR	<no operator available to service batch request>
	MOUNEWVOL	<MOUNT new relative volume !ZB (!AD) on !AC!UW:!/> /FAO=5
	REMOUVOL	<REMOUNT relative volume !ZB (!AD) on !AC!UW:!/> /FAO=5

!
! Warning messages
!

	.SEVERITY	WARNING
	.BASE		512

	HOMBLKBAD	<primary home block is bad; backup used>
	IDXHDRBAD	<index file header is bad; backup used>
	MAPHDRBAD	<storage map header is bad; volume locked>
	IDXMAPERR	<I/O error on index file bitmap; volume locked>
	BITMAPERR	<I/O error on storage bitmap; volume locked>
	BADHOMBLK	<bad home block encountered on volume>
	WRTHOMBLK	<I/O error rewriting home block>
	QUOTAFAIL	<failed to activate quota file; volume locked>
	BITMAPINV	<storage bitmap is invalid; volume locked>
	WRITESCB	<write error on storage control block; volume write locked>
!
! Informational messages
!

	.SEVERITY	INFORMATIONAL
	.BASE		1024

	MOUNTED		<!AF mounted on !AS> /FAO=3
	VOLIDENT	<label = '!AF', owner = '!AF', format = '!AF'> /FAO=6
	WRITELOCK	<volume is write locked>
	REBUILD		<volume was improperly dismounted; rebuild in progress>
	OPRQST		<!AS> /FAO=1
	OPREPLY		<!AS> /FAO=1
	OPRQSTCAN	<operator request canceled>
	NOOPR		<no operator available to service request>
	INVLDRESP	<invalid operator response>
	MOUNTDEV	<Please mount!AS device !AS!AS> /FAO=3
	VOLNAME		< volume !AS in> /FAO=1
	NODEVAVL	<Device !AS is not available for mounting.!AS> /FAO=2
	RPLYARRIVD	<operator reply has arrived>
	WRONGVOL	<device !AS contains the wrong volume> /FAO=1
	RQSTDON		<operator request canceled - mount completed successfully>

	.END
