! OPCMSG.MSG - system definition file for OPCOM
!
!	Version	'V03-001'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the source for OPCOM messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFICATION HISTORY:
!
!	V03-001	RLRV3A1		Robert L. Rappaport	5-Apr-1982
!		Added MSG$_UDA50MVER and MSG$_DUPUNITNO.
!
! V02-006	STJ0180		Steven T. Jeffreys,	07-Jan-1981
!		Added MVCOMPLETE and MVABORTED messages, and slightly
!		change the test of the existing mount verification messages.
!
! V02-005	STJ0079		Steven T. Jeffreys,	31-Jul-1981
!		Added BLANK message for the mag. tape ACP.
!
! V02-004	STJ0063		Steven T. Jeffreys,	14-Jul-1981
!		Added an alternate CANCEL message.
!		Added an INITIALIZE message for the mag. tape ACP.
!		Added messages for mount verification support.
!
! V02-003	STJ0042		Steven T. Jeffreys,	22-May-1981
!		Change format of RQSTCMPLTE, RQSTABORT, and RQSTPEND
!		to be enable existing code to parse the messages.
!
! V02-002	STJ0028		Steven T. Jeffreys,	29-Mar-1981
!		Modify existing messages and add new ones as part of
!		the support for the new OPCOM.

!+
! OPERATOR COMMUNICATIONS MESSAGES 
!-
 
	.FACILITY	OPCOM,5 /SYSTEM /PREFIX=OPC$_ /MACRO=$OPCMSG
	.SEVERITY	SUCCESS
	.BASE		0

	TERMENAB	<!%D, operator enabled, operator !AS> /FAO=1
	LOGINIT		<!%D, logfile initialized by operator !AS!/!8* logfile is !AS> /FAO=2
	TERMDSBL	<!%D, operator disabled, operator !AS> /FAO=1

	.SEVERITY	FATAL

	RQSTABORT	<!AS!/!%D, request !UL aborted by operator !AS> /FAO=3

	.SEVERITY	SUCCESS

	RQSTPEND	<!AS!/!%D, request !UL pending by operator !AS> /FAO=3
	RQSTCMPLTE	<!AS!/!%D, request !UL completed by operator !AS> /FAO=3

	.SEVERITY	FATAL

	LOGFAIL		<!%D, failed logfile operation on file !AS!/AS> /FAO=2
	TERMFAIL	<!%D, failed to enable terminal>
	NOSUCHRQST	<!%D, no such request>
	DEVOFFLINE	<!%D, device !AS is offline> /FAO=1
	DEVONLINE	<!%D, device !AS is online> /FAO=1
	NOCLI		<no command interpreter>

	.SEVERITY	SUCCESS

	NOPERATOR	<!%D, no operator coverage>

	.SEVERITY	FATAL

	UNKNOPR		<unknown operator>
	DEVNOTERM	<illegal source operator device>
	ILLRQST		<!%D, illegal operator request>
	RQSTCAN		<!%D, request !UL was canceled>

	.SEVERITY	SUCCESS

	OPRNOTIF	<operator notified, waiting... !%T> /FAO=1
	OPREPLY		<!AD> /FAO=2
	LOGTIME		<!%D, logfile time stamp>

	.SEVERITY	FATAL

	LOGCLOS		<!%D, logfile closed by operator !AS!/!8* logfile was !AS> /FAO=2

	.SEVERITY	INFORMATIONAL

	USERQST		<!%D, request !UL, from user !AD!/!AS> /FAO=4
	USERMSG		<!%D, message from user !AD!/!AS> /FAO=3
	LOGSTS		<!%D, logfile status for file !AS!/!AS> /FAO=2
	OPERSTS		<!%D, operator status for operator !AS!/!AS> /FAO=2
	RQSTSTST	<!%D, request status for request !UL!/!AS> /FAO=2
	SHUTDOWN	<!%D, OPCOM shutting down.   Requested by operator !AS> /FAO=1

	SYSTEMOPER	<SYSTEM>
	GROUPOPER	<GROUP>
	USEROPER	<USER>

	NOTENABLED	<!8* *** disabled ***>
	CENTRL		<CENTRAL>
	PRINT		<PRINTER>
	TAPES		<TAPES>
	DISKS		<DISKS>
	DEVICE		<DEVICES>
	CARDS		<CARDS>
	NTWORK		<NETWORK>
	OPER1		<OPER1>
	OPER2		<OPER2>
	OPER3		<OPER3>
	OPER4		<OPER4>
	OPER5		<OPER5>
	OPER6		<OPER6>
	OPER7		<OPER7>
	OPER8		<OPER8>
	OPER9		<OPER9>
	OPER10		<OPER10>
	OPER11		<OPER11>
	OPER12		<OPER12>		

	DEVOFFLINX	<!%D, Device !AS is offline.!/!8* Mount verification in progress.>/FAO=1
	WRONGVOL	<!%D, Device !AS contains the wrong volume.!/!8* Mount verification in progress.>/FAO=1
	DEVWRTLCK	<!%D, Device !AS has been write locked.!/!8* Mount verification in progress.>/FAO=1

	INITAPE		<!AS!/!%D, request !UL completed by operator !AS> /FAO=3
	RQSTDONE	<!%D, request !UL was satisfied.> /FAO=1
	BLANKTAPE	<!AS!/!%D, request !UL completed by operator !AS> /FAO=3

	MVCOMPLETE	<!%D, Mount verification completed for device !AS> /FAO=1
	MVABORTED	<!%D, Mount verification aborted for device !AS> /FAO=1
	UDA50MVER	<!%D, UDA50 microcode not up to rev level !AS> /FAO=1
	DUPUNITNO	<!%D, MSCP Controller - duplicate unit number !AS> /FAO=1
	.END
