! PL1MSG.MDL
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! These messages are used by programs compiled by the VAX-11 PL/I
! compiler. They are output because of unfielded exceptions which
! occur durring execution.
!
 
!	Facility code=30 (PLI)
!	Error number=0
!	Severity=0 (Warning)
	.FACILITY	PLI,30 /SYSTEM /PREFIX=PL1$_ /MACRO=$PL1DEF
	.SEVERITY	WARNING
	.BASE		0

	VAXCOND		<User defined condition, !XL.> /FAO=1
	ENDPAGE		<End of page condition. File: !AD> /FAO=1
	ENDFILE		<End of file condition. File: !AD> /FAO=1
	UKNFILE		<Unknown file condition. File: !AD> /FAO=1
	KEY		<File key condition. File: !AD> /FAO=1
	ERROR		<PL/I ERROR condition.>
	ANYCOND		<PL/I ANYCONDITION condition.>
	ZERODIV		<PL/I ZERO DIVIDE condition.>
	FIXOVF		<PL/I FIXED OVERFLOW condition.>

	.BASE		10

	PARM		<PL/I I/O. Not enough or bad parameters.>
	ATTR		<PL/I I/O. Inconsistent attributes.>
	FLID		<PL/I I/O. Invalid file identifier.>
	LNSZ		<PL/I I/O. Invalid line size.>
	PGSZ		<PL/I I/O. Invalid page size.>
	NOVM		<PL/I I/O. Virtual memory overflow.>
	TITL		<PL/I I/O. Invalid file title.>
	RMSF		<PL/I I/O. RMS FAB error value.>
	RMSR		<PL/I I/O. RMS RAB error value.>
	ROP		<PL/I I/O. Invalid read options.>
	KEYD		<PL/I I/O. Not a keyed file.>
	DEVM		<PL/I I/O. Run-time library error.>
	NKEY		<PL/I I/O. No key specified.>
	NREC		<PL/I I/O. Not a record file.>
	NSQL		<PL/I I/O. Not a sequential file.>
	OPEN		<PL/I I/O. Open failure.>
	BATR		<PL/I I/O. Opened file has conflicting attributes.>
	NCUR		<PL/I I/O. No current record.>
	NFRM		<PL/I I/O. No from or no buffer specified.>

	.BASE		50

	SUCCESS		<PL/I I/O. Success.>
	.END
