! RSXMSG.MDL - system definition file for RSX AME
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for the RSX AME messages.
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFICATION HISTORY:
!
!	V001	TMH0001		Tim Halvorsen	02-Feb-1981
!		Remove FAO arguments from LOADERROR and NOTSKIMG.
!---

!
! THIS FILE DEFINES THE ERROR MESSAGES FOR THE RSX AME
!
	.FACILITY	RSX,6 /SYSTEM /MACRO=$RSXMSGDEF
	.SEVERITY	WARNING
	.BASE		200

	EXITSTATUS	<RSX-11M exit with status>
	VERIFYCMD	<  MCR!AD> /FAO=2

	.SEVERITY	ERROR
	.BASE		100

	NOSUCHDEV	<TKB-assigned device not found, !AD!UW:, lun=!UB> /FAO=4
	PMD		<post-mortem dump, !AD> /FAO=2
	NOPMD		<post-mortem dump failure, !AD> /FAO=2

	.SEVERITY	FATAL
	.BASE		0

	RESERVED	<compatibility mode reserved instruction>
	BREAK		<compatibility mode breakpoint trap>
	IOT		<compatibility mode IOT>
	NONRSXEMT	<non-RSX-11M  EMT execution>
	TRAP		<compatibility mode TRAP execution>
	ILLINST		<compatibility mode illegal instruction>
	ODDADDR		<compatibility mode odd address>
	TBIT		<compatibility mode T-bit>
	ACCVIO		<compatibility mode access violation>
	BADSTACK	<invalid compatibility mode stack pointer>
	INSFDYNMEM	<insufficient virtual address space>
	EXTERNABRT	<external abort>
	NOTSKIMG	<file is not a valid RSX-11M task image>
	BADLIBREF	<invalid library/common reference, !AD> /FAO=2
	LIBNOTFND	<open failure on library/common file, !AD> /FAO=2
	LOADERROR	<error loading image file, execution aborted>
	IMAGETERM	<'!AC' terminated, !%D> /FAO=2
	REGMSG		<	!AC = !OW !XW> /FAO=3
	NOCOMM		<unable to initialize process mailbox or common efn's>
	.END
