! SHRMSG.MDL - system definition file for shared messages
!
!	Version 'V03-002'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for the shared messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFIED BY:
!
!	V03-002	GAS0068		Gerry Smith	31-Mar-1982
!		Add NOTRUNC message.
!
!	V03-001	MLJ0084		Martin L. Jack,	28-Mar-1982  14:48
!		Clean up initial capitalization errors.
!
!	V017	KRM0036		Karl Malik	12-Jan-1982
!		Add CREATEDSTM message.
!
!	V016	BLS0127		Benn Schreiber	 1-Jan-1982
!		Add insvirmem
!
!	V015	WMC0031		Wayne Cardoza	22-dec-1981
!		Add ILLDIRCOPY message
!
!	V014	GAS0023		G. Smith	10-Dec-1981
!		Add CONFQUAL message
!
!	V013	SHZ0001		S. Zalewski	11-NOV-1981
!		Fix DELETE/CONFIRM message
!	
!	V012	PCG0001		P. George	10-Aug-1981
!		Add NOTTERM message.
!
!	V011	GWF0064		G. Fowler	29-Jun-1981
!		Add NODESTQUE and ILLDESQUE messages
!
!	V010	KRM0008		K. Malik	11-Feb-1981
!		Add DIRNOTCRE message
!
!	V009	TMH0006		T. Halvorsen	22-Jan-1980
!		Add ACTIMAGE message
!
!	V008	TMH0005		T. Halvorsen	03-Dec-1979
!		Add NOTLOCKED message
!
!	V007	TMH0004		T. Halvorsen	25-Nov-1979
!		Add EXISTS, UNLOCKED, RENAMED, PROTECTED messages
!
!	V006	TMH0003		T. Halvorsen	08-Nov-1979
!		Change FILNOTPUR to use only 1 argument rather than
!		having a numeric version argument.
!
!	V005	TMH0002		T. Halvorsen	29-Oct-1979
!		Change FILPURGED to use only 1 argument rather than
!		having a numeric version argument.
!
! 004	T. Halvorsen	26-Jul-1979
!	Add CBT message to indicate file copied contiguous best try
!
! 1-003 - Add HALTED, NOCMDMEM, QEMPTY for DR32 support routines.
!	  TCM0001 21-May-1979
! 1-002 - Add ENDABORT, ENDDIAGS, ENDNOOBJ for FORTRAN IV-PLUS.
!	  SBL 9-Mar-1979


! These message codes should not be used directly by a facility since
! they do not contain a subsystem (i.e., facility) identifier or a
! severity code.  Use the following formula to calculate actual facility
! message codes.

!	facility message code = common message code +
!				facility id * 65536 +
!				severity code


	.FACILITY	SHR,0 /SHARED /SYSTEM
	.SEVERITY	WARNING
	.BASE		512

	APPENDEDB	<!AS appended to !AS (!UL block!%S)> /FAO=3 /IDENT=APPENDED
	APPENDEDR	<!AS appended to !AS (!UL record!%S)> /FAO=3 /IDENT=APPENDED
	BADBYTE		<invalid data (!XB) at !XL> /FAO=2 /IDENT=BADDATA
	BADFIELD	<!AS field invalid at !XL> /FAO=2
	BADLONG		<invalid data (!XL) at !XL> /FAO=2 /IDENT=BADDATA
	BADWORD		<invalid data (!XW) at !XL> /FAO=2 /IDENT=BADDATA
	BEGIN		<!AS beginning> /FAO=1
	BEGIND		<!AS beginning at !%D> /FAO=2 /IDENT=BEGIN
	BEGINT		<!AS beginning at !%T> /FAO=2 /IDENT=BEGIN
	CLICB		<CLI control block at !XL> /FAO=1
	CLOSEIN		<error closing !AS as input> /FAO=1
	CLOSEOUT	<error closing !AS as output> /FAO=1
	COPIEDB		<!AS copied to !AS (!UL block!%S)> /FAO=3 /IDENT=COPIED
	COPIEDR		<!AS copied to !AS (!UL record!%S)> /FAO=3 /IDENT=COPIED
	CREATED		<!AS created> /FAO=1
	ENDED		<!AS ended> /FAO=1
	ENDEDD		<!AS ended at !%D> /FAO=2 /IDENT=ENDED
	ENDEDT		<!AS ended at !%T> /FAO=2 /IDENT=ENDED
	NEWFILES	<!UL file!%S created> /FAO=1
	OPENIN		<error opening !AS as input> /FAO=1
	OPENOUT		<error opening !AS as output> /FAO=1
	OVERLAY		<!AS being overwritten> /FAO=1
	READERR		<error reading !AS> /FAO=1
	REPLACED	<!AS being replaced> /FAO=1
	WILDCONCAT	<wildcard specification cannot be concatenated> /IDENT=CONCAT
	WILDOUTVER	<wildcard version required for output file>
	WRITEERR	<error writing !AS> /FAO=1
	ABEND		<!AS aborted> /FAO=1 /IDENT=ABORT
	ABENDD		<!AS aborted at !%D> /FAO=2 /IDENT=ABORT
	ABENDT		<!AS aborted at !%T> /FAO=2 /IDENT=ABORT
	SYSERRORPC	<!AS system service error at PC !XL> /FAO=2 /IDENT=SYSERROR
	SYNTAX		<error parsing '!AS'> /FAO=1
	NOVALUE		<'!AS' keyword requires a value> /FAO=1
	BADKEY		<'!AS' is an invalid keyword> /FAO=1
	BADVALUE	<'!AS' is an invalid keyword value> /FAO=1
	BADDELIM	<invalid delimiter following '!AS'> /FAO=1
	BADLOGIC	<internal logic error detected>
	NOWILD		<no wildcard permitted>
	TEXT		<!AS> /FAO=1
	IDXCONCAT	<indexed file cannot be concatenated> /IDENT=CONCAT
	RELCONCAT	<relative file cannot be concatenated> /IDENT=CONCAT
	HIGHVER		<higher version of !AS already exists> /FAO=1
	BADLOGICPC	<internal logic error detected at PC !XL> /FAO=1 /IDENT=BADLOGIC
	ATPC		<at PC !XL> /FAO=1
	BADCOPIES	<'!AS' is an invalid number of copies> /FAO=1 /IDENT=BADVALUE
	BADFORM		<'!AS' is an invalid form type> /FAO=1 /IDENT=BADVALUE
	BADJOBID	<'!AS' is an invalid job identifier> /FAO=1 /IDENT=BADVALUE
	BADJOBNAME	<'!AS' is an invalid job name> /FAO=1 /IDENT=BADVALUE
	BADPRTY		<'!AS' is an invalid priority> /FAO=1 /IDENT=BADVALUE
	BADQNAME	<'!AS' is an invalid queue name> /FAO=1 /IDENT=BADVALUE
	BADTIME		<'!AS' is an invalid time specification> /FAO=1 /IDENT=BADVALUE
	NOQUEUE		<!AS queue does not exist> /FAO=1
	NOJOBID		<job !UW not found in !AS queue> /FAO=1 /IDENT=NOJOB
	NOJOBNAME	<job !AS not found in !AS queue> /FAO=1 /IDENT=NOJOB
	SYSERROR	<system service error>
	NOTCOPIED	<!AS not copied> /FAO=1
	NOTCMPLT	<!AS not completely copied> /FAO=1
	RMSERROR	<RMS service error>
	UNXPCTSTS	<unexpected status detected. Expected '!AS'. Found:> /FAO=1
	HASHCONCAT	<hashed file cannot be concatenated> /IDENT=CONCAT
	INCOMPAT	<!AS (input) and !AS (output) have incompatible attributes> /FAO=2
	VALERR		<specified value is out of legal range>
	FILNOTDEL	<error deleting !AS> /FAO=1
	CONFDEL		<!/!AS, delete? (Y or N): > /FAO=1
	DELETED		<!AS deleted> /FAO=1
	DELVER		<explicit version number or wild card required>
	PURGEVER	<version numbers not permitted>
	CLOSEDEL	<error closing !AS> /FAO=1
	DIRTOOBUS	<directory is presently too active to be purged>
	NOFILPURG	<no files purged for !AS> /FAO=1
	FILNOTPUR	<error deleting !AS> /FAO=1
	SEARCHFAIL	<error searching for !AS> /FAO=1
	DELINTERR	<internal error in DELETE/PURGE utility>
	PARSEFAIL	<error parsing !AS> /FAO=1
	FILPURGED	<!AS deleted> /FAO=1
	ENDABORT	<!AS compilation aborted> /FAO=1
	ENDDIAGS	<!AS completed with !UL diagnostic!%S> /FAO=2
	ENDNOOBJ	<!AS completed with !UL diagnostic!%S - object deleted> /FAO=2
	HALTED		<transfer has been halted>
	NOCMDMEM	<no command memory has been allocated>
	QEMPTY		<queue empty>
	CBT		<insufficient contiguous space, file copied non-contiguously>
	EXISTS		<!AS already exists> /FAO=1
	UNLOCKED	<!AS unlocked> /FAO=1
	RENAMED		<!AS renamed to !AS> /FAO=2
	PROTECTED	<protection on !AS changed to !AS> /FAO=2
	NOTLOCKED	<!AS was not locked> /FAO=1
	ACTIMAGE	<error activating image !AS> /FAO=1
	DIRNOTCRE	<!AS directory file not created> /FAO=1
	NODESTQUE	<no such destination queue !AS> /FAO=1
	ILLDESQUE	<illegal destination queue name !AS> /FAO=1
	NOTTERM		<input device is not a terminal>
	CONFQUAL	<conflicting qualifiers>
	ILLDIRCOPY	<illegal directory copy of !AS attempted> /FAO=1
	INSVIRMEM	<insufficient virtual memory>
	CREATEDSTM	<!AS has been created in stream format> /FAO=1
	NOTRUNC		<truncation not allowed for this file organization>
	.END
