! SSMSG.MDL - system defintion file for System Service Messages
!
!	Version 'V03-003'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for System Service Messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFIED BY:
!
!	V03-003	RLRV3A1		Robert L. Rappaport	12-Apr-1982
!		Add SS$_DUPUNIT.
!
!	V03-002	MLJ0084		Martin L. Jack,	28-Mar-1982  14:48
!		Clean up initial capitalization errors.
!
!	V03-001	ACG0271		Andrew C. Goldstein,	23-Mar-1982  10:00
!		Add unique error status for directory allocation failure
!
!	V02-030	LJK0125		Lawrence J. Kenah	9-Feb-1982
!		Add message that restricts privileged shareable images
!		from referencing other shareable images. Make text for
!		SS$_RELINK more general.
!
!	V02-029	KTA0074		Kerbey T. Altmann	31-Jan-1982
!		Add new messages for SCS services.
!
!	V02-028	SRB0043		Steve Beckhardt		13-Jan-1982
!		Made small change in message text of SS$_CREATED message.
!
!	V02-027	TMH0027		Tim Halvorsen		31-Dec-1981
!		Add SS$_NOLICENSE message for DECnet license checking.
!
!	V02-026	ACG0245		Andrew C. Goldstein,	21-Dec-1981  14:54
!		Add SS$_NOTPRINTED and SS$_JBCERROR
!
!	V02-025	LJK0104		Lawrence J. Kenah	17-Dec-1981
!		Add SS$_PARTMAPPED for files whose mapping information
!		is not totally resident.
!
!	V02-024 SBL2024		Steve Lionel		4-Dec-1981
!		Add SS$_DBGOPCREQ status for use by debugger and
!		LIB$GET_OPCODE.
!
!	V02-023	LJK0093		Lawrence J. Kenah	1-Dec-1981
!		Add SS$_FORCEDEXIT status for use by job controller.
!
!	V02-022	ACG0227		Andrew C. Goldstein,	30-Nov-1981  14:41
!		Add SS$_DIRNOTEMPTY status.
!
!	V02-021	SRB0042		Steve Beckhardt		30-Nov_1981
!		Added SS$_EXDEPTH.
!
!	V02-020	MIR0044		Michael I. Rosenblum	13-Nov-1981
!		Added alternate success code SS$_INCOMPAT for
!		remote terminal incompatibility.
!
!	V02-019	SRB0040		Steve Beckhardt		2-Nov-1980
!		Added SS$_NOLOCKID.
!
!	V02-018	PHL0020		Peter H. Lipman		29-Oct-1981
!		Add alternate success code SS$_CONCEALED for $GETDVI
!
!	V02-017	RLR0002		Robert L. Rappaport	28-Oct-1981
!		Added SS$_BADRCT.
!
!	V02-016	WMC0010		Wayne M. Cardoza	23-Oct-1981
!		Added SS$_EXGBLPAGFIL.
!
!	V02-015	KTA0037		Kerbey T. Altmann	21-Oct-1981
!		Added 3 new messages for SCS services.
!
!	V02-014	RLR0001		Robert L. Rappaport	28-Aug-1981
!		Added SS$_FORCEDERROR status.
!
!	V02-013	WMC0001		Wayne Cardoza		24-Aug-1981
!		Fix spelling of SS$_EXPGFLQUOTA
!
!	V02-012	SRB0028		Steve Beckhardt		14-Jul-81
!		Added several more messages for lock manager
!
!	V02-011	KTA0022		Kerbey T. Altmann	10-Jun-1981
!		Add 2 new messages for inhibited system services.
!
!	V02-010	SRB0025		Steve Beckhardt		5-Jun-1981
!		Reserved status codes for specific no privilege
!		and exceeded quota errors.
!
!	V02-009	SRB0010		Steve Beckhardt		19-Mar-1981
!		Add new messages for lock manager.
!
!	V02-008	ACG0200		Andrew C. Goldstein,	11-Mar-1981  17:46
!		Add SS$_NOTALLPRIV status
!
!	V02-007	KTA0012		Kerbey T. Altmann	11-Mar-1981
!		Add 4 new messages for X25 group.
!
!	V03-006	ACG0182		Andrew C. Goldstein,	5-Dec-1980  11:39
!		Fix text of volume invalid message
!
!	V005	LMK0001		Len Kawell		22-Sep-1980
!		Improve text of network messages and add new disconnect
!		messages.
!
!	V004	KTA0004		Kerbey Altmann		18-Sep-1980
!		Re-edit to use new 3271 P.E. messages.
!
!
!	V03-003	STJ0005		Steven T. Jeffreys,	02-Sep-1980
!		Add NODEVAVL
!
!	V002	TMH0002		Tim Halvorsen		28-Aug-1980
!		Add CHAINW and remove NODEBUG messages for 3271 driver.
!		Remove ACTIVE since DEVACTIVE is already there.
!
!	001	TMH0001		Tim Halvorsen		09-Jun-1980
!		Add 3271 driver messages.
!		Document message space layout.
!---


!+
! SYSTEM STATUS CODES
!
!	LAYOUT OF MESSAGE SPACE:
!
!	MSG #s	   RANGE      # MSGS	    DESCRIPTION
!
!	0-127       0-3FF	128	FATAL ERRORS
!     128-191	  400-5FF	 64	HARDWARE DEFINED FATAL ERRORS
!     192-255	  600-7FF	 64	SUCCESS CODES
!     256-383	  800-BFF	128	WARNING CODES
!     384-447	  C00-DFF	 64	INFORMATIONAL CODES
!     448-511	  E00-FFF	 64	NONFATAL ERROR CODES
!    512-1023	1000-1FFF	512	SHARED MESSAGES (NOT HERE, SEE SHRMSG)
!   1024-1279	2000-27FF	256	FATAL ERRORS (CONTINUED FROM 400)
!   1280-1343	2800-29FF	 64	NO PRIVILEGE ERRORS
!   1344-1375	2A00-2AFF	 32	EXCEEDED QUOTA ERRORS
!   1376-4095	2B00-7FFF      2720	(UNUSED)
!-


!
! EXPLICITLY DEFINED SUCESS CODES
!
! DO NOT MIX THESE CODES WITH INCREMENTAL ASSIGNMENTS BELOW
!
	.FACILITY	SYSTEM,0 /SHARED /SYSTEM /PREFIX=SS$_ /MACRO=$SSDEF
	.SEVERITY	SUCCESS
	.BASE		0

	NORMAL		<normal successful completion>
!
! NOTE THAT CONTINUE,WASCLR,WASSET DO NOT HAVE ANY MESSAGE TEXT --
! SINCE THESE CODES USE THE SAME MESSAGE NUMBER AS NORMAL AND ACCVIO,
! THEY CAN NEVER BE MADE TO HAVE MESSAGES ASSOCIATED WITH THEM.
!
	.LITERAL	SS$_CONTINUE=1
	.LITERAL	SS$_WASCLR=1
	.LITERAL	SS$_WASSET=9

!
! SEVERE ERRORS (HEX 0-400, 2000-2800)
!
 

	.SEVERITY	FATAL

	ACCVIO		<access violation, reason mask=!XB, virtual address=!XL, PC=!XL, PSL=!XL> /FAO=4
	BADPARAM	<bad parameter value>
	EXQUOTA		<exceeded quota>
	NOPRIV		<no privilege for attempted operation>
! MAKE THE ABOVE ERRORS FALL INTO SHORT LITERALS
	ABORT		<abort>
	BADATTRIB	<bad attribute control list>
	BADESCAPE	<syntax error in escape sequence>
	BADIMGHDR	<bad image header>
	CHANINTLK	<channel usage interlocked>
	CTRLERR		<fatal controller error>
	DATACHECK	<write check error>
	DEVFOREIGN	<device is mounted foreign>
	DEVMOUNT	<device is already mounted>
	DEVNOTMBX	<device is not a mailbox>
	DEVNOTMOUNT	<device is not mounted>
	DEVOFFLINE	<device is not in configuration or not available>
	DRVERR		<fatal drive error>
	DUPLNAM		<duplicate process name>
	FILACCERR	<magnetic tape file access is nonblank>
	FILALRACC	<file already accessed on channel>
	FILNOTACC	<file not accessed on channel>
	FILNOTEXP	<file is not expired>
	FORMAT		<invalid media format>
	GPTFULL		<global page table is full>
	GSDFULL		<global section descriptor table is full>
	LCKPAGFUL	<no more pages may be locked in memory>
	ILLBLKNUM	<illegal logical block number>
	ILLCNTRFUNC	<illegal ACP control function>
	ILLEFC		<illegal event flag cluster>
	ILLIOFUNC	<illegal I/O function code>
	ILLPAGCNT	<illegal page count parameter>
	ILLSER		<illegal service call number>
	INCVOLLABEL	<incorrect volume label>
	INSFARG		<insufficient call arguments>
	INSFWSL		<insufficient working set limit>
	INSFMEM		<insufficient dynamic memory>
	INSFRAME	<insufficient call frames to unwind>
	IVADDR		<invalid media address>
	IVCHAN		<invalid I/O channel>
	IVDEVNAM	<invalid device name>
	IVGSDNAM	<invalid global section name>
	IVLOGNAM	<invalid logical name>
	IVLOGTAB	<invalid logical name table number>
	IVQUOTAL	<invalid quota list>
	IVSECFLG	<invalid process/global section flags>
	IVSSRQ		<invalid system service request>
	IVSTSFLG	<invalid status flag>
	IVTIME		<invalid time>
	LENVIO		<address space length violation>
	LKWSETFUL	<locked portion of working set is full>
	MBTOOSML	<mailbox is too small for request>
	MEDOFL		<medium is offline>
	NODATA		<mailbox is empty>
	NOIOCHAN	<no I/O channel available>
	NOLOGNAM	<no logical name match>
	NONEXDRV	<nonexistent drive>
	NOTFILEDEV	<device is not file structured>
	NOTINTBLSZ	<block size is greater than 2048>
	NOTLABELMT	<tape is not labeled>
	NOTSQDEV	<not a sequential device>
	PAGOWNVIO	<page owner violation>
	PARITY		<parity error>
	PARTESCAPE	<partial escape>
	PFMBSY		<page fault monitor is in use>
	PSTFULL		<process section table is full>
	RESULTOVF	<resultant string overflow>
	SECTBLFUL	<section table (process/global) is full>
	TAPEPOSLOST	<magnetic tape position lost>
	TIMEOUT		<device timeout>
	UNASEFC		<unassociated event flag cluster>
	UNSAFE		<drive unsafe>
	VASFULL		<virtual address space is full>
	VECINUSE	<AST vector already enabled>
	VOLINV		<volume is not software enabled>
	WRITLCK		<write lock error>
	NOTAPEOP	<no tape operator>
	IVCHNLSEC	<invalid channel for create and map section>
	NOMBX		<no associated mailbox for inbound connects>
	NOLINKS		<maximum network logical links exceeded>
	NOSOLICIT	<interrupt message not solicited>
	NOSUCHNODE	<remote node is unknown>
	REJECT		<connect to network object rejected>
	TOOMUCHDATA	<too much optional/interrupt data specified>
	BUGCHECK	<internal consistency failure>
	FILNOTCNTG	<file is not contiguous as required>
	BADSTACK	<bad stack encountered during exception dispatch>
	MCHECK		<detected hardware error, PC=!XL, PSL=!XL> /FAO=2
	DEVACTIVE	<device is active>
	HANGUP		<data set hang-up>
	OPINCOMPL	<operation is incomplete>
	ILLSEQOP	<illegal sequential operation>
	IVSECIDCTL	<invalid section identification match control>
	NOTNETDEV	<not a network communication device>
	IVPROTECT	<invalid page protection code>
	ACPVAFUL	<MTAACP's virtual address space is full>
	MTLBLLONG	<magnetic tape volume label can be no more than six characters>
	BUFBYTALI	<device does not support byte-aligned transfers>
	NOAQB		<ACP queue header not found>
	WRONGACP	<wrong ACP for device>
	BUFNOTALIGN	<buffer incorrectly aligned>
	DEVCMDERR	<device command error>
	DEVREQERR	<device request error>
	INSFBUFDP	<unable to allocate a buffered datapath>
	INSFMAPREG	<insufficient map registers>
	IVBUFLEN	<invalid buffer length>
	IVMODE		<invalid mode for requested function>
	MCNOTVALID	<device microcode is not valid>
	POWERFAIL	<power failure occurred>
	SHMGSNOTMAP	<shared memory global section not mapped during creation>
	TOOMANYLNAM	<logical name translation exceeded allowed depth>
	SHMNOTCNCT	<shared memory not connected>
	NOTCREATOR	<request denied, user is not on creator port>
	INTERLOCK	<unable to acquire system data structure interlock>
	BADQUEUEHDR	<interlocked queue corrupted>
	NOSLOT		<no PCB or swap slot available>
	SUSPENDED	<process is suspended>
	EXPORTQUOTA	<port's quota exceeded>
	NOSHMBLOCK	<no free shared memory block available for creation>
	BADQFILE	<invalid disk quota file format>
	NOQFILE		<no disk quota file available>
	QFACTIVE	<disk quota file is already active>
	QFNOTACT	<disk quota file is not active>
	DUPDSKQUOTA	<duplicate disk quota file entry>
	NODISKQUOTA	<no disk quota entry for this UIC>
	EXDISKQUOTA	<disk quota exceeded>
	IDMISMATCH	<ident mismatch with existing global section>
	NOWRT		<cannot create writable section to read-only file>
! **************
! NOTE:  THE ABOVE SET OF SEVERE ERROR MESSAGES IS FULL!!!!
!	 [VMSLIB.SRC]SHRMSG.MDL HAS USED MESSAGE NUMBERS HEX 1000-2000.
!	 ANY ADDITIONAL SEVERE ERROR MESSAGES MUST BE ADDED
!	 BELOW, IN THE RANGE HEX 2000-2800.
! **************


	.BASE		1024

	BADISD		<illegal image section descriptor>
	RELINK		<obsolete executable image - please relink>
	NOTINSTALL	<writable shareable images must be installed>
	SHARTOOBIG	<new version of shareable image too big - relink all images>
	NOP1VA		<P1 space not supported in shareable images>
	MULTRMS		<multiple RMS vectors specified>
	VECFULL		<privileged vector limit of 42 exceeded>
	IVLVEC		<section not installed with privilege>
	INSFSPTS	<insufficient SPTs to map process buffer to system>
	DISCONNECT	<process is disconnected from requested interrupt vector>
	PRIVINSTALL	<shareable images must be installed to run privileged image>
	PROTINSTALL	<protected images must be installed>
	BADVEC		<invalid change mode or message vector>
	REMRSRC		<insufficient system resources at remote node>
	PROTOCOL	<network protocol error>
	THIRDPARTY	<network logical link disconnected by a third party>
	NOSUCHUSER	<login information not recognized at remote node>
	SHUT		<remote node no longer accepting connects>
	UNREACHABLE	<remote node is not currently reachable>
	INVLOGIN	<login information invalid at remote node>
	NOSUCHOBJ	<network object is unknown at remote node>
	EXCPUTIM	<CPU time limit expired>
	OPRABORT	<aborted by operator>
	SHRIDMISMAT	<ident mismatch with shareable image>
	COMMHARD	<communications hardware error detected>
	IVCHAR		<invalid character>
	DEVINACT	<device inactive>
	CONNECFAIL	<connect to network object timed-out or failed>
	LINKABORT	<network partner aborted logical link>
	LINKDISCON	<network partner disconnected logical link>
	LINKEXIT	<network partner exited>
	PATHLOST	<path to network partner node lost>
	CLEARED		<virtual call was cleared>
	RESET		<circuit was reset>
	UNSOLICIT	<response not solicited>
	TOOMANYREDS	<too many redirects>
	IVLOCKID	<invalid lock id>
	SUBLOCKS	<cannot dequeue a lock with sublocks>
	PARNOTGRANT	<parent lock must be granted>
	CVTUNGRANT	<cannot convert an ungranted lock>
	FORCEDERROR	<forced error flagged in last sector read>
	ILLSELF		<illegal self reference>
	ILLCDTST	<illegal connection descriptor table state>
	NOLISTENER	<specified remote system process not listening>
	EXGBLPAGFIL	<exceeded global page file limit>
	BADRCT		<Replacement and Caching Table unrecoverable I/O error>
	DIRNOTEMPTY	<directory file is not empty>
	FORCEDEXIT	<forced exit of image or process by Job Controller>
	NOTPRINTED	<failed to queue spool file for print>
	JBCERROR	<error communicating with job controller>
	NOLICENSE	<operation requires software license>
	VCBROKEN	<virtual circuit broken>
	VCCLOSED	<virtual circuit closed>
	INSFCDT		<insufficient CDT entries>
	DEVNOTDISM	<device not dismounted>
	NOSHRIMG	<privileged shareable image cannot have outbound calls>
	DUPUNIT		<MSCP Controller - Duplicate Unit Number>


!
! HARDWARE FATAL EXCEPTION CODES (HEX 400-600)
!


	.BASE		128

	PLHLDR		<reserved for future use>
	ASTFLT		<AST fault, SP=!XL, param=!XL, PC=!XL, PSL=!XL, target PC=!XL, PSL=!XL> /FAO=6
	BREAK		<breakpoint fault at PC=!XL, PSL=!XL> /FAO=2
	CMODSUPR	<change mode to supervisor trap, code=!XL, PC=!XL, PSL=!XL> /FAO=3
	CMODUSER	<change mode to user trap, code=!XL, PC=!XL, PSL=!XL> /FAO=3
	COMPAT		<compatibility mode fault (code !UB) at PC=!XL, PSL=!XL> /FAO=3
	OPCCUS		<opcode reserved to customer fault at PC=!XL, PSL=!XL> /FAO=2
	OPCDEC		<opcode reserved to DIGITAL fault at PC=!XL, PSL=!XL> /FAO=2
	PAGRDERR	<page read error, reason mask=!XB, virtual address=!XL, PC=!XL, PSL=!XL> /FAO=4
	RADRMOD		<reserved addressing fault at PC=!XL, PSL=!XL> /FAO=2
	ROPRAND		<reserved operand fault at PC=!XL, PSL=!XL> /FAO=2
	SSFAIL		<system service failure exception, status=!XL, PC=!XL, PSL=!XL> /FAO=3
	TBIT		<T-bit pending trap at PC=!XL, PSL=!XL> /FAO=2
	DEBUG		<command interpreter debugger signal at PC=!XL, PSL=!XL> /FAO=2
! THE FOLLOWING CODES MUST BE IN ORDER SINCE THEY ARE CALCULATED
	ARTRES		<reserved arithmetic trap at PC=!XL, PSL=!XL> /FAO=2
	INTOVF		<arithmetic trap, integer overflow at PC=!XL, PSL=!XL> /FAO=2
	INTDIV		<arithmetic trap, integer divide by zero at PC=!XL, PSL=!XL> /FAO=2
	FLTOVF		<arithmetic trap, floating overflow at PC=!XL, PSL=!XL> /FAO=2
	FLTDIV		<arithmetic trap, floating/decimal divide by zero at PC=!XL, PSL=!XL> /FAO=2
	FLTUND		<arithmetic trap, floating underflow at PC=!XL, PSL=!XL> /FAO=2
	DECOVF		<arithmetic trap, decimal overflow at PC=!XL, PSL=!XL> /FAO=2
	SUBRNG		<arithmetic trap, subscript out of range at PC=!XL, PSL=!XL> /FAO=2
	FLTOVF_F	<arithmetic fault, floating overflow at PC=!XL, PSL=!XL> /FAO=2
	FLTDIV_F	<arithmetic fault, floating divide by zero at PC=!XL, PSL=!XL> /FAO=2
	FLTUND_F	<arithmetic fault, floating underflow at PC=!XL, PSL=!XL> /FAO=2
! THE ABOVE CODES MUST BE IN ORDER SINCE THEY ARE CALCULATED
	INHCHMK		<inhibited CHMKernel trap, code=!XL, PC=!XL, PSL=!XL> /FAO=3
	INHCHME		<inhibited CHMExecutive trap, code=!XL, PC=!XL, PSL=!XL> /FAO=3

!
! SUCCESS CODES (HEX 600-800)
!
 

	.SEVERITY	SUCCESS
	.BASE		192

	BUFFEROVF	<output buffer overflow>
	CONTROLO	<output completed under CTRL/O>
	CONTROLY	<operation completed under CTRL/Y>
	CREATED		<file/section did not exist - was created>
	MSGNOTFND	<message not in system message file>
	NOTRAN		<no string translation performed>
	SUPERSEDE	<logical name superseded>
	WASECC		<successful transfer; no data check>
	DEVALRALLOC	<device already allocated to this job>
	REMOTE		<assignment completed on remote node>
	CONTROLC	<operation completed under CTRL/C>
	NOTMODIFIED	<no pages in the section were modified>
	RDDELDATA	<read deleted data address mark>
	OVRDSKQUOTA	<disk usage exceeds disk quota>
	SYSVERDIF	<system version mismatch - privilege removed - please relink>
	FILEPURGED	<oldest file version purged>
	NOTALLPRIV	<not all requested privileges authorized>
	SYNCH		<synchronous successful completion>
	CONCEALED	<logical device name concealed physical device name>
	INCOMPAT	<feature incompatible with previous system version>
	DBGOPCREQ	<debugger opcode request for PC !XL !+>/FAO=2
	ALRDYCLOSED	<connection already closed>

!
! WARNING CODES (HEX 800-C00)
!


	.SEVERITY	WARNING
	.BASE		256

	ACCONFLICT	<file access conflict>
	BADCHKSUM	<bad file header checksum>
	BADFILEHDR	<bad file header>
	BADFILENAME	<bad file name syntax>
	BADFILEVER	<bad file version number>
	BADIRECTORY	<bad directory file format>
	CANCEL		<I/O operation canceled>
	DATAOVERUN	<data overrun>
	DEVALLOC	<device already allocated to another user>
	DEVASSIGN	<device has channels assigned>
	DEVICEFULL	<device full - allocation failure>
	DEVNOTALLOC	<device not allocated>
	DIRFULL		<directory is full>
	DUPFILENAME	<duplicate file name>
	ENDOFFILE	<end of file>
	ENDOFTAPE	<end of tape>
	EXTIDXFILE	<***** obsolete - delete when convenient>
	FCPREADERR	<file processor read error>
	FCPREWNDERR	<file processor rewind error>
	FCPSPACERR	<file processor space error>
	FCPWRITERR	<file processor write error>
	FILELOCKED	<file is deaccess locked>
	FILENUMCHK	<file identification number check>
	FILESEQCHK	<file identification sequence number check>
	FILESTRUCT	<unsupported file structure level>
	HEADERFULL	<file header is full>
	IDXFILEFULL	<index file is full>
	MBFULL		<mailbox is full>
	NOHOMEBLK	<Files-11 home block not found on volume>
	NONEXPR		<nonexistent process>
	NONLOCAL	<device is not a local device>
	NOHANDLER	<no condition handler found>
	NOSIGNAL	<no signal currently active>
	NOSUCHDEV	<no such device available>
	NOSUCHFILE	<no such file>
	RESIGNAL	<resignal condition to next handler>
	UNWIND		<unwind currently in progress>
	UNWINDING	<unwind already in progress>
	NOMOREFILES	<no more files>
	BEGOFFILE	<beginning of file>
	BLOCKCNTERR	<block count error>
	MUSTCLOSEFL	<must close file>
	WAITUSRLBL	<waiting for user labels>
	ILLUSRLBLRD	<illegal read of user labels>
	ILLUSRLBLWT	<illegal write of user labels>
	ILLLBLAST	<illegal user label AST control block address>
	ENDOFUSRLBL	<end of user labels>
	NOSUCHSEC	<no such (global) section>
	CLIFRCEXT	<CLI forced exit>
	FCPREPSTN	<file processor reposition error>
	TOOMANYVER	<too many higher file versions>
	NOTVOLSET	<volume is not part of a volume set>
	ENDOFVOLUME	<end of volume>
	NOMOREPROC	<no more processes>
	NODEVAVL	<no device available>
	NOTQUEUED	<request not queued>
	DGQINCOMP	<datagram queue operation incomplete>
	DIRALLOC	<allocation failure on directory file>


!
! INFORMATIONAL CODES (HEX C00-E00)
!


	.SEVERITY	INFORMATIONAL
	.BASE		384

	EOTIN		<EOT response to text>
	CHAINW		<chained write received>

!
! NONFATAL ERROR CODES (HEX E00-1000)
!


	.SEVERITY	ERROR
	.BASE		448

	LINEABRT	<host aborted transmission or failed to respond>
	DEADLOCK	<deadlock detected>
	NOLOCKID	<no lock id. available>
	EXDEPTH		<exceeded allowed depth>
	PARTMAPPED	<some file map pointers not permanently resident>
 
!
! NO PRIVILEGE FATAL ERROR CODES (HEX 2800-2A00)
!

	.SEVERITY	FATAL
	.BASE		1280

	.LITERAL	SS$_NOPRIVSTRT = 1280 @ 3

	NOCMKRNL	<operation requires CMKRNL privilege>
	NOCMEXEC	<operation requires CMEXEC privilege>
	NOSYSNAM	<operation requires SYSNAM privilege>
	NOGRPNAM	<operation requires GRPNAM privilege>
	NOALLSPOOL	<operation requires ALLSPOOL privilege>
	NODETACH	<operation requires DETACH privilege>
	NODIAGNOSE	<operation requires DIAGNOSE privilege>
	NOLOG_IO	<operation requires LOG_IO privilege>
	NOGROUP		<operation requires GROUP privilege>
	NOACNT		<operation requires ACNT privilege>
	NOPRMCEB	<operation requires PRMCEB privilege>
	NOPRMMBX	<operation requires PRMMBX privilege>
	NOPSWAPM	<operation requires PSWAPM privilege>
	NOALTPRI	<operation requires ALTPRI privilege>
	NOSETPRV	<operation requires SETPRV privilege>
	NOTMPMBX	<operation requires TMPMBX privilege>
	NOWORLD		<operation requires WORLD privilege>
	NOMOUNT		<operation requires MOUNT privilege>
	NOOPER		<operation requires OPER privilege>
	NOEXQUOTA	<operation requires EXQUOTA privilege>
	NONETMBX	<operation requires NETMBX privilege>
	NOVOLPRO	<operation requires VOLPRO privilege>
	NOPHY_IO	<operation requires PHY_IO privilege>
	NOBUGCHK	<operation requires BUGCHK privilege>
	NOPRMGBL	<operation requires PRMGBL privilege>
	NOSYSGBL	<operation requires SYSGBL privilege>
	NOPFNMAP	<operation requires PFNMAP privilege>
	NOSHMEM		<operation requires SHMEM privilege>
	NOSYSPRV	<operation requires SYSPRV privilege>
	NOBYPASS	<operation requires BYPASS privilege>
	NOSYSLCK	<operation requires SYSLCK privilege>

	.LITERAL	SS$_NOPRIVEND = (1344 @ 3) - 1
!
! EXCEEDED QUOTA FATAL ERROR CODES (HEX 2A00-2B00)
! 

	.SEVERITY	FATAL
	.BASE		1344

	.LITERAL	SS$_EXQUOTASTRT = 1344 @ 3

	EXASTLM		<exceeded AST quota>
	EXBIOLM		<exceeded buffered I/O quota>
	EXBYTLM		<exceeded byte count quota>
	EXDIOLM		<exceeded direct I/O quota>
	EXFILLM		<exceeded open file quota>
	EXPGFLQUOTA	<exceeded pagefile quota>
	EXPRCLM		<exceeded subprocess quota>
	EXTQELM		<exceeded timer queue entry quota>
	EXENQLM		<exceeded enqueue quota>

	.LITERAL	SS$_EXQUOTAEND = (1376 @ 3) - 1




	.END
