! SYSGMSG.MDL - system definition file for SYSGEN messages
!
!	Version V03-002
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for SYSGEN messages
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  8-Jun-1978
!
! MODIFICATION HISTORY:
!
!	V03-002	KDM0087		Kathleen D. Morse	6-Apr-1982
!		Add fatal error messages for multi-processing.
!
!	V03-001	JLV0200		Jake VanNoy		23-MAR-1982
!		Add EXTENDED and .BASE's.
!
!	V02-015	JLV0150		Jake VanNoy		4-Jan-1981
!		Add MISMATCH.
!
!	V02-014	JLV0144		Jake VanNoy		21-Dec-1981
!		Add NOTPARAM, NOPARAM, CREPARFIL, INVPARFIL
!
!	V02-013	LJK0102		Lawrence J. Kenah	16-Dec-1981
!		Add EMPTYFILE. Change text for SWAPAGINS.
!
!	V02-012	JLV0128		Jake VanNoy		22-Oct-1981
!		Add NEXNOTUBA, ENDUBA, SKIPPED.
!
!	V02-011	JLV0106		Jake VanNoy		22-Oct-1981
!		Add SYSVERCHK, SETMAX, SETMIN, DRIVENAM, NOSCS.
!
!	V02-010	JLV0086		Jake VanNoy		22-Sep-1981
!		Add UNKCPU.
!
!	V0209	MIR0007		Michael I Rosenblum	06-Aug-1981
!		Added NOAUTOCNF message.
!
!	V0208	SPF0001		Steve Forgey		12-Jun-1981
!		Added WRITEACT and WRITECUR messages.
!
!	V0207	JLV0024		Jake VanNoy		5-Jun-1981
!		Added NOADAPTER and MAXTOOBIG messages.
!
!	V0206	JLV0018		Jake VanNoy		30-Apr-1981
!		Add Config error messages. 
!
!	V0105	LMK0004		LEN KAWELL		25-FEB-1980
!		ADD SWAP/PAGE FILE ALREADY INSTALLED MESSAGE.
!
!	V0104	LMK0003		LEN KAWELL		18-FEB-1980
!		ADD SYSTEM VERSION MISMATCH MESSAGE.
!
!	V0103	LMK0002		LEN KAWELL		04-NOV-1979
!		ADDED SHARED MEMORY MESSAGES.
!
!	V0102	LMK0001		LEN KAWELL		09-JUL-1979
!		ADDED MAXUNITS MESSAGE.
!

!
! DEFINE SYSGEN  RELATED ERROR/STATUS VALUES
!
 
 
 
!
! DEFINE ERROR MESSAGES

!
	.FACILITY	SYSGEN,124 /SYSTEM /PREFIX=SYSG$_ /MACRO=$SYSGMSGDEF
	.SEVERITY	ERROR

.BASE 	0
	NOAUTOCNF	<autoconfigure all is inhibited>
	INVDPTINI	<invalid driver prologue init table value>
	NOUNLOAD	<driver is not unloadable>
	VECINUSE	<vector is in use>
	SPTFULL		<system page table is full>
	INVVEC		<invalid or unspecified interrupt vector>
	INVDPT		<invalid driver image - DPT$B_TYPE, VBN 2 .NEQ. DYN$C_DPT>
	MAXUNITS	<unit number greater than maximum units specified>
	NOSUCHMEM	<no shared memory found at specified NEXUS>
	BADPARAM	<insufficient shared memory to create specified data structures>
	BADCHKSUM	<shared memory data structures corrupted - reinitialization necessary>
	INCMEMNAM	<specified shared memory name does not match>
	SYSVERCHK	<system version mismatch - function aborted>
	SYSVERDIF	<system version mismatch - reassemble and relink driver>
	SWAPAGINS	<all additional page or swap files already installed>
	EMPTYFILE	<zero-length page or swap file cannot be installed> 

	ABORT	    	<abort>
	CONFQUAL    	<conflicting qualifiers, request aborted>
	OVERFLOW    	<overflow in floating addresses, illegal configuration>
	SYNTAX	    	<syntax error: '!AD' >/FAO=1
	INPUT_ERR   	<devices !AC must be entered as !AC >/FAO=2
	TOO_MNY     	<too many of this device type > 
	NULFIL	    	<null file specification >
	INVADAP		<invalid adapter name specified>
	UNKADAP		<unknown adapter type encountered>
	UNKCPU		<unknown CPU type encountered>
	NOADAPTER	<no adapter (nexus) number specified>
	MAXTOOBIG	<maxunits specified is too large>	
	NEXNOTUBA	<nexus is not a UNIBUS adapter>
	NOTPARAM	<not a parameter file>
	NOPARAM		<no such parameter>
	CREPARFIL	<unable to create parameter file>
	INVPARFIL	<invalid parameter file>
	SHMDBLUSE	<MA780 cannot be used for main memory and system interconnect>


.SEVERITY	WARNING

.BASE 	512
	OUT_RANGE   	<number cannot be less than 1 or larger than 127 >
	DEVNOTKNWN  	<device not known: /!AD/ >/FAO=1
	RSV_ERR     	<cannot have RSV device - set to zero >
	NODEVADAP   	<no devices on adapter !ZL>/FAO=1
	SETMAX		<value set to maximum for parameter !AC>/FAO=1
	SETMIN		<value set to minimum for parameter !AC>/FAO=1
	NOSCS		<error loading SCS code>
	ENDUBA		<end of UNIBUS address space>
	MISMATCH	<SYSGEN version mismatch with current SYS.EXE>

.SEVERITY	INFORMATIONAL

.BASE 	1024
	EQV_NOTICE  	<equivalent name - device !AD will be output as !AD >/FAO=2
	TWICE       	<device !AC - count changed from !ZL to !ZL >/FAO=3
	WRITEACT	<ACTIVE system parameters modified by process ID !XL>/FAO=1
	WRITECUR	<CURRENT system parameters modified by process ID !XL into file !AS>/FAO=2
	DRIVENAM	<driver name is !AC>/FAO=1
	SKIPPED		<section of address space was skipped>
	EXTENDED	<!AS extended>/FAO=1
.END
