! XPORTMSG.MDL - VAX/VMS System Message File for XPORT
!
!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for the BLISS XPORT messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
! AUTHOR:  Ward Clark		CREATION DATE:  27-Sept-1979
!
!**

!+
!
! The following are messages issued by the BLISS XPORT package.
!
!-


!
! Success messages
!
	.FACILITY	XPO,32 /SYSTEM
	.SEVERITY	SUCCESS
	.BASE		0

	NORMAL		<normal completion>
	CREATED		<file was successfully created and opened>
	INCOMPLETE	<incomplete amount of data read>
	NEW_FILE	<first read on concatenated file was successful>
	NEW_PAGE	<first read on a new page was successful>
	TEMPORARY	<temporary file-spec created>
	TERMINAL	<user terminal file-spec created>
!
! Warning messages
!

	.SEVERITY	WARNING
	.BASE		512

	END_FILE	<end-of-file has been reached>
!
! Error messages
!

	.SEVERITY	ERROR
	.BASE		1024

	BAD_ADDR	<invalid memory address>
	BAD_ALIGN	<memory element not on a fullword boundary>
	BAD_ARGS	<invalid argument list>
	BAD_CONCAT	<invalid concatenated file specification>
	BAD_DELIM	<invalid punctuation>
	BAD_DESC	<invalid string/data descriptor>
	BAD_DEVICE	<invalid device>
	BAD_DFLT	<invalid default file specification>
	BAD_DIRECT	<invalid directory>
	BAD_DTYPE	<invalid data type>
	BAD_FORMAT	<invalid record format>
	BAD_IO_OPT	<invalid I/O option>
	BAD_LENGTH	<invalid length>
	BAD_NAME	<invalid file name>
	BAD_NEW		<invalid new file specification>
	BAD_NODE	<invalid node>
	BAD_ORG		<invalid file organization>
	BAD_PROMPT	<invalid prompt>
	BAD_RECORD	<invalid record>
	BAD_REQ		<invalid XPORT request>
	BAD_RLTD	<invalid related file specification>
	BAD_RSLT	<invalid resultant file specification>
	BAD_SPEC	<invalid file specification>
	BAD_TYPE	<invalid file type>
	BAD_VER		<invalid file version>
	CHANNEL		<I/O channel assignment error>
	CLOSED		<file is already closed>
	CONFLICT	<conflicting options or attributes>
	CORRUPTED	<file is corrupted>
	EXISTS		<file already exists>
	FILE_LOCK	<file is locked>
	FREE_MEM	<dynamic memory deallocation error>
	GET_MEM		<dynamic memory allocation error>
	IN_USE		<file is currently in use>
	IO_BUFFER	<I/O buffering error>
	IO_ERROR	<I/O error>
	MISSING		<required parameter, option or attribute missing>
	NETWORK		<network error>
	NO_ACCESS	<file cannot be accessed>
	NO_BACKUP	<file cannot be backed up>
	NO_CHANNEL	<all I/O channels are in use>
	NO_CLOSE	<file cannot be closed>
	NO_CONCAT	<concatenated file specification not allowed>
	NO_CREATE	<file cannot be created>
	NO_DELETE	<file cannot be deleted>
	NO_DIRECT	<directory does not exist>
	NO_FILE		<file does not exist>
	NO_MEMORY	<insufficient dynamic memory>
	NO_OPEN		<file cannot be opened>
	NO_READ		<file cannot be read>
	NO_RENAME	<file cannot be renamed>
	NO_SPACE	<insufficient space>
	NO_SUBDIR	<sub-directory does not exist>
	NO_SUPPORT	<requested function not supported>
	NO_WRITE	<file cannot be written>
	NOT_CLOSED	<file has not been closed>
	NOT_EXPIRE	<expiration date has not been reached>
	NOT_INPUT	<file is not open for input>
	NOT_ONLINE	<device is not online>
	NOT_OPEN	<file has not been opened>
	NOT_OUTPUT	<file is not open for output>
	OPEN		<file is currently open>
	PREV_ERROR	<program terminated due to previous error>
	PRIVILEGED	<privileged operation>
	PROTECTED	<file protection denies access>
	PUT_MSG		<message output error>
	REC_LOCK	<record is locked>
	RENAME_NEW	<new file cannot be renamed>
	RENAME_OLD	<old file cannot be renamed>
	TRUNCATED	<record was truncated>
	WILDCARD	<wildcard error>
!
! Fatal error messages
!

	.SEVERITY	FATAL
	.BASE		2048

	BAD_IOB		<invalid IOB>
	BAD_LOGIC	<XPORT logic error detected>
	TERMINATE	<program terminated due to program request>
	.END
