!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:	DCL Differences command
!
! ABSTRACT:	The DCL DIFFERENCES command compares the contents of
!		two files.
!
! ENVIRONMENT:	VAX native, user mode
!
!--
!
! AUTHOR: Peter George, Benn Schreiber		CREATION DATE:	1-August-1981
!
! MODIFIED BY:
!
!	V03-001	PCG0001		Peter George		14-Oct-1981
!		Add TWOWIDTHS message.
!
!+++
!
! Return status codes for differences
!
!---


	.FACILITY	DIF,108/SYSTEM

!
! Success codes		(Severity level 1)
!
	.SEVERITY	SUCCESS

	SAMEFILE	<files are identical>
!
! Informational
!
	.SEVERITY	INFORMATION

	FILAREDIF	<files are different>
!
! Warning codes
!

	.SEVERITY	WARNING

	MAXDIF		<maximum number of difference records encountered - DIF aborted>
	MRGGTMTCH/FAO=2	<value of !UL for /MERGE is greater than /MATCH value of !UL!/!_/MERGE set to !-!UL>
	PARGTMTCH/FAO=2	<value of !UL for /PARALLEL is greater than /MATCH value of !UL!/!_/PARALLEL set to !-!UL>
	TWOWIDTHS	</WIDTH and /LINE_WIDTH are redundant - /LINE_WIDTH value ignored, /WIDTH value used>
!
! Error codes		(Severity level 2)
!

	.SEVERITY	ERROR

	INSVIRMEM	<insufficient virtual memory - DIF aborted>
	MAXDIFEXC/FAO=1	<maximum differences count of !UL exceeded>
!
! Severe errors
!
	.SEVERITY	SEVERE

	CMDLIN/FAO=1	<command line segment in error!/!2(_)\!AS\>
	CMDSYNTAX	<command syntax error>
	CONFQUAL	<conflicting command qualifiers>
	NOLOWVER/FAO=1	<no lower version of file !AS found>
	STRCPYERR	<unexpected error from string copy routine>
	SYSFAOERR	<unexpected error from SYS$FAO>
	TOOMNYDLM/FAO=1	<more than maximum of !UL comment delimiters specified>
	TOOMNYFIL	<more than two input files specified>

	.END
