.TITLE		CONVMSG		VAX-11 CONVERT Error Messages	V01-001

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! Facility:	VAX-11 CONVERT
!
! Environment:
!
!		VAX/VMS Operating System
!
! Abstract:
!		CONVERT and CONVERT/RECLAIM error messages
!
!
!--

!
! Author:	Keith B Thompson	Creation date:	August-1980
!
!
! Modified by:
!
!	V03-001	KBT0039		Keith Thompson		3-Apr-1982
!		Change the exception messages to info
!
!****

.FACILITY	CONVERT,	178	/SYSTEM		/PREFIX=CONV$_

.LITERAL	CONV$_FAO_MAX = 2

.SEVERITY	INFO

NI		<function not implemented yet>
PAD		<PAD option ignored, output record format not fixed>
RMS		<record caused RMS severe error>
RTL		<record longer than Maximum Record Length>
RTS		<record too short for Fixed record format file>
VFC		<record too short to fill fixed part of VFC record>
DUP		<duplicate Key encountered>
KEY		<invalid Record Key>
REX		<record already exist>
RSK		<record shorter than primary key>
RSZ		<record will not fit in block/bucket>
SEQ		<record not in order>

.SEVERITY	ERROR

BADBLK		<invalid option block>
CREA_ERR	<error creating !AS as output> /FAO=1
DELPRI		<can not delete primary key>
EXTN_ERR	<unable to extend output file>
FATALEXC	<fatal exception encountered>
BADSORT		<error trying to sort input file>
FILLIM		<exceeded open file limit>
IDX_LIM		<exceeded maximum index level>
ILL_KEY		<illegal key or value out of range>
ILL_VALUE	<illegal parameter value>
INP_FILES	<to many input files>
KEYREF		<no such key>
LOADIDX		<error loading secondary index !SB> /FAO=1
NARG		<wrong number of arguments>
NOKEY		<no such key>
NOTIDX		<file is not an index file>
NOTSEQ		<output file is not a sequential file>
ORDER		<routine called out of order>
OPENEXC		<error opening exception file !AS> /FAO=1
PROERR		<error reading prologue>
PROL_WRT	<prologue write error>
UDF_BKS		<can not convert UDF records into spanned file>
UDF_BLK		<can not fit UDF records into single block bucket>

INVBKT		<invalid bucket at VBN !SL> /FAO=1
PLV		<unsupported prologue version>

.END
