	.TITLE	LNK_MESSAGES V03-010
!---
!
!	Error messages for the VAX/VMS Linker
!
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:  VAX/VMS Linker
!
! ABSTRACT:
!
!	These are the error messages used by the Linker.
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, unprivileged user mode utility,
!	operates at non-AST level.
!
! AUTHOR:  Benn Schreiber,  18-Jun-1980
!
! MODIFIED BY:
!
!	V03-010		BLS0162		Benn Schreiber		22-Mar-1982
!		New message for /SHARE=COPY being used.
!
!	V03-009		BLS0151		Benn Schreiber		21-Feb-1982
!		Add message for inability to allocate fixup section
!
!	V03-008		BLS0111		Benn Schreiber		20-Nov-1981
!		Add messages for shareable image psect length errors
!
!	V03-007		BLS0103		Benn Schreiber		10-Nov-1981
!		Add several new messages
!
!	V03-006		BLS0090		Benn Schreiber		31-Oct-1981
!		Messages for environments and module local symbols
!
!	V03-005		BLS0081		Benn Schreiber		17-Sep-1981
!		Messages for entity ident check
!
!	V03-004		BLS0074		Benn Schreiber		29-Aug-1981
!		Shareable images again.  Move some messages to different
!		severities, add others.
!
!	V03-003		BLS0042		Benn Schreiber		25-Feb-1981
!		New messages for copyalways sections
!
!	V03-002		BLS0025		Benn Schreiber		10-Nov-1980
!		New messages for enhanced shareable images
!
!----

	.FACILITY	LINK,100/SYSTEM /PREFIX=LIN$_

	.SEVERITY	SUCCESS

	.SEVERITY	INFORMATIONAL

BASDUERRS	<basing image due to errors in relocatable references>
DATMISMCH/FAO=4	<creation date of !17%D in shareable image !AS!/!_differs from date of !17%D in shareable image library !AS>
IDMISMCH/FAO=6	<GSMATCH of !2XL,!6XL in shareable image !AS!/!_differs from GSMATCH of !2XL,!6XL in shareable image library !AS>
LIBFIND/FAO=4	<failed to find valid module or STB at RFA %X!XL:%X!XL!/!_for module !AC file !AS>
NONPICDAT/FAO=3	<!UL relocatable address reference!%S!/!_in module !AC file !AS>
NONPICIMG/FAO=1	<shareable image !AS is non-position independent>
OPTIGNSHR	<option ignored for shareable image>
OPTIGNSYS	<option ignored for system image>
TRACIGN		<supression of traceback overridden by DEBUG specification>
TFRSYS/FAO=1	<transfer address in system image !AS ignored>
UDFENV/FAO=1	<!_!AC>
UDFSYM/FAO=2	<!_!2(AC)>

	.SEVERITY	WARNING

ADRWRTDAT/FAO=4	<address data in shareable writeable section!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
ALREDEF/FAO=5	<multiple .TRANSFER for symbol !AC illegal!/!_psect !AC offset %X!XL!/!_in module !AC file !AS>
BASESYM/FAO=1	<base address symbol !AC is undefined or relocatable>
BASSHRBEL/FAO=3	<shareable image !AS has base of %X!XL!/!_which is below image base of %X!XL>
CLUBELBAS/FAO=3	<base address of %X!XL for cluster !AC!/!_is below image base of %X!XL>
CRFERR/FAO=1	<error encountered in Cross Reference>
DBGTFR/FAO=1	<image !AS has no Debugger transfer address>
EMPTYFILE/FAO=1	<no modules found in file !AS>
ENTIDMTCH/FAO=8	<!AC ident of !AC for entity !AC!/!_in module !AC file !AS!/!_does not match ident of !AC!/!_in module !AC file !AS>
ENTIDMTCHB/FAO=10 <!AC ident of !XB,!6XL for entity !AC!/!_in module !AC file !AS!/!_does not match ident of !XB,!6XL!/!_in module !AC file !AS>
ENTIDMTCHO/FAO=7 <object type of !AC for entity !AC!/!_in module !AC file !AS!/!_does not match object type of !AC!/!_in module !AC file !AS>
ENTIDMTCHT/FAO=5 <ident type for entity !AC!/!_in module !AC file !AS!/!_differs from ident type in module !AC file !AS>
EOMSTK/FAO=3	<!UL items left on Linker internal stack!/!_in module !AC file !AS>
FAOFAIL		<FAO system service failure>
GSDTYP/FAO=3	<illegal GSD record type (!UL.)!/!_in module !AC file !AS>
ILLFMLCNT/FAO=5	<Minimum argument count (!UL.) exceeds maximum (!UL.)!/!_in formal specification of symbol !AC!/!_in module !AC file !AS>
ILLRECLEN/FAO=3	<illegal record length (!UL.)!/!_in module !AC file !AS>
ILLRECTYP/FAO=4	<illegal record type (!UL.)!/!_in module !AC record !UL file !AS>
ILLSHROPR/FAO=3	<illegal shareable image ref expression operator!/!_in module !AC record !UL file !AS>
ILLSHRXPR/FAO=3	<illegal shareable image reference expression!/!_in module !AC record !UL file !AS>
ILLTIR/FAO=4	<illegal relocation command (!UL.)!/!_in module !AC record !UL file !AS>
ILLVPS/FAO=4	<illegal position (!UL.) or size (!UL.) in STO_VPS command!/!_in module !AC file !AS>
IMGBASED/FAO=1	<shareable image !AS is already based>
INTSTKOV/FAO=3	<Linker internal stack of !UL overflowed!/!_in module !AC file !AS>
INTSTKUN/FAO=3	<Linker internal stack of !UL underflowed!/!_in module !AC file !AS>
LIBNAMLNG/FAO=2	<library module name !AS has illegal length (!UL.)>
!MAXEXCED/FAO=3	<!UL. !AC exceeds maximum allowed of !UL.>
MULDEF/FAO=3	<symbol !AC multiply defined!/!_in module !AC file !AS>
MULCLUOPT/FAO=2	<cluster !AC multiply defined!/!_in options file !AS>
MULDEFPSC/FAO=3	<psect !AC multiply defined!/!_in module !AC file !AS>
MULPSC/FAO=3	<conflicting attributes for psect !AC!/!_in module !AC file !AS>
MULTFR/FAO=2	<multiply defined transfer address!/!_in module !AC file !AS>
NOEOM/FAO=3	<no end of module record found!/!_in module !AC file !AS>
NOEPM/FAO=3	<undefined entry mask of symbol !AC referenced!/!_in module !AC file !AS>
NONPICREF/FAO=4	<failure to use .ADDRESS for relocatable data !/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
NOSUCHMOD/FAO=2	<module !AS not found!/!_in library !AS>
NOTIMGLIB/FAO=1	<file !AS is not a shareable image symbol table library>
NOTPSECT/FAO=2	<relocation base set to other than psect base!/!_in module !AC file !AS>
NUDFENVS/FAO=1	<!UL undefined environment!%S:>
NUDFLSYMS/FAO=1	<!UL undefined module-local symbol!%S:>
NUDFSYMS/FAO=1	<!UL undefined symbol!%S:>
OVRALI/FAO=3	<conflicting alignment on overlayed psect !AC!/!_in module !AC file !AS>
PSCALI/FAO=4	<psect !AC alignment (!UL.) illegal!/!_in module !AC file !AS>
PSCNXR/FAO=2	<transfer address is not in executable, relocatable psect!/!_in module !AC file !AS>
RECLNG/FAO=2	<file !AS has a record of illegal length (!UL.)>
RECTYP/FAO=3	<file !AS record !UL is illegal (!UL.)>
SEQNCE/FAO=2	<illegal record sequence!/!_in module !AC file !AS>
SHRCPYIGN	<COPY value for /SHARE qualifier ignored, using NOCOPY>
SHRSEPCLU/FAO=0	<shareable image being placed in separate cluster>
SHRPSCREF/FAO=5	<reference to psect !AC is not position independent!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
SHRSYMREF/FAO=5	<reference to symbol !AC is not position independent!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
SHRSYMTRA/FAO=5	<Attempted .TRANSFER of shareable image symbol !AC illegal!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
STALITUDF/FAO=4	<Stack of undefined literal !UL in record !UL!/!_in module !AC file !AS>
STKOVFLO/FAO=2	<stack of !UL pages falls below control region to %X!XL>
TIRLNG/FAO=4	<object command data overflows record by !UL. bytes!/!_in module !AC record !UL file !AS>
TIRNYI/FAO=4	<unimplemented TIR command (!UL.) encountered!/!_in module !AC record !UL file !AS>
TRUNC/FAO=4	<truncation error in psect !AC offset %X!XL!/!_in module !AC file !AS>
TRUNCDAT/FAO=3	<computed value is %X!XL!/!_value written is %X!XL at location %X!XL>
UDEFPSC/FAO=3	<attempt to reference undefined psect number !UL.!/!_in module !AC file !AS>
USEUDFENV/FAO=5	<undefined environment !AC referenced!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
USEUDFEN2/FAO=5/ID=USEUDFENV <undefined environment number !UL referenced!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
USEUDFLSY/FAO=5	<undefined module-local symbol !AC referenced!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
USEUNDEF/FAO=5	<undefined symbol !AC referenced!/!_in psect !AC offset %X!XL!/!_in module !AC file !AS>
USEUNDEF2/FAO=3/ID=USEUNDEF <undefined symbol !AC referenced in debug or traceback record!/!_in module !AC file !AS>
USRTFR/FAO=1	<image !AS has no user transfer address>
WARNISUE	<completed with warnings>
WRNERS/FAO=2	<compilation warnings!/!_in module !AC file !AS>

	.SEVERITY	ERROR

CONFBASADR/FAO=5 <conflicting base address for image !AC!/!_base of %X!XL in file !AS!/!_conflicts with base of %X!XL in file !AS>
CONFIXMEM/FAO=1	<conflicting virtual memory requirement!/!_for fixup section for image !AS!/!_Restructure image or eliminate based shareable images>
CONFMEM/FAO=3	<conflicting virtual memory requirement!/!_at %X!XL for !UL. pages in cluster !AC>
ERRORISUE	<completed with errors>
ERRORS/FAO=2	<compilation errors!/!_in module !AC file !AS>
GETPTIERR/FAO=4	<error from $GETPTI, buffer %X!XL:%X!XL, image VPN !UL. for !UL. pages>
INSVIRMEM/FAO=2	<insufficient virtual memory for !UL. pages!/!_for cluster !AC>
LINERR/FAO=1	<command line segment in error!/!2(_)\!AS\>
MEMFUL		<insufficient virtual address space to complete this link>
MULSHRPSC/FAO=3	<psect !AC defined in shareable image !AS!/!_is multiply defined in shareable image !AS>
NOGSDREF/FAO=3	<no GSD reference to shareable image symbol !AC found!/!_in module !AC file !AS>
NOIMGFIL	<image file not created>
OPTLIN/FAO=3	<options line in error!/!_!AS'!AS'!AS>
OUTSIMG/FAO=6	<attempted store location %X!XL is outside !AC (%X!XL to %X!XL)!/!_in module !AC file !AS>
OUTSIMGP/IDENT=OUTSIMG/FAO=7 <attempted store location %X!XL is outside !AC (%X!XL to %X!XL)!/!_in psect !AC module !AC file !AS>
SHRPSCLNG/FAO=6	<Psect !AC has length of !UL!/!_in module !AC file !AS!/!_which exceeds length of !UL in shareable image !AS>

	.SEVERITY	SEVERE

BADCCC/FAO=3	<bad compilation completion code (!UL.)!/!_in module !AC file !AS>
BADIMGHDR/FAO=1	<bad image header!/!_in shareable image file !AS>
BADPSC/FAO=3	<transfer address in unknown psect (!UL.)!/!_in module !AC file !AS>
CMDSYNTAX	<command line syntax error>
CMDTOOLONG/FAO=1 <command line too long in options file !AS>
CONFQUAL	<conflicting qualifiers>
EOMFTL/FAO=2	<link abort specified!/!_in module !AC file !AS>
EXCPSC/FAO=2	<more than 65535 psects defined!/!_in module !AC file !AS>
FATALERROR	<fatal error message issued>
FIRSTMOD	<first input file being a library requires module extraction>
FORMAT		<file has illegal format>
ILLNAMELEN/FAO=6 <!AC !AC name length (!UL.) is illegal - not 1 to !UL.!/!_in module !AC file !AS>
ILLQUALVAL	<illegal qualifier value>
MEMBUG/FAO=3	<memory (de)allocation bug !UL, %X!XL, !UL>
MODNAM/FAO=2	<module !AC name length is illegal - not 1 to !UL.>
NOMODS		<no input modules specified (or found)>
NOPSCTS/FAO=2	<no psects defined in module !AC file !AS>
NOTOBJLIB/FAO=1	<file !AS is not an object library>
!OPTLENERR/FAO=6 <!AC option argument !AS has illegal length (!UL.) - not !UL. to !UL.!/!_in options file !AS>
OPTSYNERR/FAO=1	<syntax error in options file !AS>
OPTVALERR/FAO=5	<!AC option value !UL. is out of range (!UL. to !UL.)!/!_in options file !AS>
OPTARGMIS/FAO=1	<missing argument in options file !AS>
PREMEOF/FAO=1	<premature end of file encountered in options file !AS>
RELINK/FAO=2	<file !AS contains deferred relocation!/!_Relink !AS and all images linked against it>
SHRINSYS	<shareable image(s) cannot be linked into a system image>
STRLVL/FAO=4	<illegal object language structure level (!UL.) should be !UL.!/!_in module !AC file !AS>

	.END
