!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! THIS file CONTAINS THE DEFINITION FOR THE SORT FACILITY SPECIFIC
! ERROR MESSAGES.  THE FACILITY CODE IS 28 AND THE SEVERITY IS 4.
!
!--



	.TITLE		SOR$MSG
	.FACILITY	SORT,28 /SYSTEM /PREFIX=SOR$_ /MACRO=$SORDEF
	.SEVERITY	FATAL
	.BASE		0

	MISS_KEY	<key specification missing.>
	WORK_DEV	<work file !AS!/	device specified not random access or not local.> /FAO=1
	NO_WRK		<need work files cannot do sort in memory.>
	VM_FAIL		<failed to get required virtual memory !SL.> /FAO=1
	WS_FAIL		<failed to get required working set space !SL.> /FAO=1
	SORT_ON		<sort already in progress.>
	BAD_KEY		<invalid key specification.>
	NUM_KEY		<too many keys specified.>
	BAD_LEN		<output record length less than 18 bytes for magtape.>
	ONE_IN		<only one input file allowed.>
	IND_OVR		<indexed sequential output requires overlay qualifier.>
	INCONSIS	<inconsistent data in file !AS.> /FAO=1
	VAR_FIX		<cannot change variable length records into fixed length.>
	BAD_TYPE	<invalid sort process.>
	LRL_MISS	<lrl must be specified.>
	BAD_SPEC	<invalid specification file record.!/	field: !AS.> /FAO=1
	BAD_LRL		<input file !AS.!/	record size greater than specified lrl.> /FAO=1
	BAD_FILE	<file size invalid.>
	BAD_ADR		<invalid descriptor address specified.>
	MAP		<failed to map work file.>
	EXTEND		<failed to extend work file.>
	KEY_LEN		<key length invalid. key number !SL, size !SL.> /FAO=2
	CLEAN_UP	<failed to reinitialize work area and files.>
	BAD_MERGE	<merge order must be between 2 and 10>
	BAD_ROUTIN	<bad routine address has been passed>
	INP_FILES	<too many input files>
	BAD_ORDER	<input file !UL is out of order> /FAO=1
	.END
