!	Version 'V03-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************


!
! Parser error messages.
!

	.FACILITY	EDT,133 /SYSTEM /MACRO=$EDTMSGDEF
	.SEVERITY	WARNING

	ERRINCOM	<Error in command>
	UNRCOM		<Unrecognized command>
	INVPARFOR	<Invalid parameter for SET or SHOW>
	INVVALSET	<Invalid value in SET command>
	NUMVALREQ	<Numeric value required>
	QUOSTRREQ	<Quoted string required>
	ERRRANSPC	<Error in range specification>
	ERRCOMOPT	<Error in command option>
	UNRCOMOPT	<Unrecognized command option>
	COLONREQ	<':' required>
	UNXCHRAFT	<Unexpected characters after end of command>
	VARREQ		<Variable required>
	MACKEYREQ	<MACRO or KEY required>
	PARSTKOVF	<Parsing stack overflow>
	ENTMUSTBE	<Entity must be WORD, SENTENCE, PAGE, or PARAGRAPH>
	NONALPHANUM	<Delimiter for SUBSTITUTE strings must be non alphanumeric>
	SUBSTRNULL	<Search string in SUBSTITUTE must not be null>
!
! Other error messages.
!


	.BASE		100

	ABOBYCC		<Aborted by CTRL/C>
	FORHLPANO	<For help on another keypad key, press the key>
	TOEXITHLP	<To exit from HELP, type a space>
	TORETKEY	<To return to the keypad diagram, press the return key>
	ATTPASCUR	<Attempt to PASTE current buffer>
	ATTCUTAPP	<Attempt to CUT or APPEND to current buffer>
	NOSELRAN	<No select range active>
	PARENMIS	<Parenthesis mismatch>
	INVBUFNAM	<Invalid buffer name>
	INSMEM		<Insufficient memory>
	INVENT		<Invalid entity>
	INVSUBCOM	<Invalid subcommand>
	CHGMODTER	<Change mode may be entered only from the terminal>
	NOJNLFIL	<Journal file could not be opened>
	INPFILOPN	<Input file could not be opened>
	OUTFILCRE	<Output file could not be created>
	COMFILNOP	<Command file could not be opened>
	COMFILNEX	<Command file does not exist>
	FILNAM		<File name:>
	INPFILNEX	<Input file does not exist>
	PLSANSYNQ	<Please answer Y(es), N(o), Q(uit), or A(ll)>
	LINEXC255	<Line exceeded 255 characters, truncated>
	KEYNOTDEF	<That key is not definable>
	NODEFN		<No definition>
	RANNONCON	<Range must be contiguous>
	DSTMOVCOP	<Destination for MOVE or COPY not found>
	RANSPCSEQ	<Range specified by /SEQUENCE would cause duplicate or non-sequential numbers>
	INVOPTCOM	<Invalid option for that command>
	INPRECLGE	<Input record too large, truncated to 255 characters>
	PRSKEYDEF	<Press the key you wish to define>
	NOWENTDEF	<Now enter the definition terminated by ENTER>
	NOSUCHLIN	<No such line>
	STRNOTFND	<String was not found>
	TOPOFBUF	<Backup past top of buffer>
	BOTOFBUF	<Advance past bottom of buffer>
	CLDNOTALN	<Could not align tabs with cursor>
	CONCHKFLD	<Consistency check failed, please check your file>
	NOOUTFIL	<No output file name>
	NOFILSPC	<File specfication required>
	COMBUFEXH	<Command buffer exhausted>
	NOHLPAVL	<Help file could not be opened>
	ERRINPFIL	<Error reading input file>
	ERROUTFIL	<Error writing output file>
	RECTOOBIG	<Record too big, truncated to 255 characters>
	SELALRACT	<Select is already active>
	EXDISKQUOTA	<Disk quota exceeded, using overdraft>

    

	.BASE		200

	WRKFILOVF	<Work file overflow>
	IOERRWRK	<I/O error on work file>
	EDITORABO	<Editor aborted>

	.END
