!	BACKUPMSG.MSG - BACKUP Messages
!
!	Version	'V03-002'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
!
! FACILITY:
!	Backup/Restore
!
! ABSTRACT:
!	This file contains the messages for BACKUP.
!
! ENVIRONMENT:
!	VAX/VMS user mode.
!
!--
!
! AUTHOR: M. Jack, CREATION DATE: 27-Aug-1980
!
! MODIFIED BY:
!
!	V03-002	ACG0276		Andrew C. Goldstein,	29-Mar-1982  16:56
!		Add BACKUP$_SSCHANGE message
!
!	V03-001	MLJ0082		Martin L. Jack,	16-Mar-1982  18:52
!		Change text of NOFILES.
!
!	V02-011	MLJ0062		Martin L. Jack,	6-Dec-1981  17:18
!		Clarify text of ACCONFLICT.  Add messages INCDELERR, INCDELETE,
!		INCENTERR, INCBADDIR, INCFILSPE to support /INCREMENTAL.
!
!	V02-010	MLJ0054		Martin L. Jack,	15-Oct-1981  19:53
!		Add messages NONCONTIG, NOSUCHRVN, STARTDELETE, DELETE,
!		CONFQUAL, QUOTAFILE.  Modify text of POSITERR, SOFTRERRS,
!		SOFTWERRS.
!
!	V02-009	MLJ0043		Martin L. Jack,	8-Sep-1981  16:49
!		Account for RMS logical device change.
!
!	V02-008	MLJ0036		Martin L. Jack,	28-Aug-1981  17:18
!		Extensive rewording/clarification/addition of messages.
!
!	V02-007	ACG0109		Andrew C. Goldstein,	3-Jun-1981  19:48
!		Add excessive error rate messages
!
!	V02-006	ACG0206		Andrew C. Goldstein,	20-May-1981  20:28
!		Fix tape positioning error message
!
!	V02-005	MLJ0025		Martin L. Jack,	8-May-1981  10:39
!		Add message WRITEBACK.  Delete message INVOUTWILD.  Change FAO
!		parameters for message INVQUAVAL.
!
!	V02-004	MLJ0020		Martin L. Jack,	20-Apr-1981  21:48
!		Implement /JOURNAL qualifier.
!
!	V02-003	MLJ0014		Martin L. Jack,	6-Apr-1981  23:15
!		Correct and clarify VBN sequence-error messages.
!
!	V02-002	MLJ0010		Martin L. Jack,	25-Mar-1981  13:55
!		Add messages for standalone ACP, standalone disk initialize,
!		and unmounted volume detection.
!
!	V02-001	MLJ0004		Martin L. Jack,	20-Feb-1981  14:17
!		Implement operator assisted tape handling.
!
!**

.title BACKUPMSG
.facility BACKUP,163/system
!
! Copies of shared messages (needed for standalone version).
!
.severity warning
OPENIN		<error opening !AS as input>/FAO=1
OPENOUT		<error opening !AS as output>/FAO=1
READERR		<error reading !AS>/FAO=1
WRITEERR	<error writing !AS>/FAO=1
CLOSEIN		<error closing !AS as input>/FAO=1
CLOSEOUT	<error closing !AS as output>/FAO=1
!
! Bug check messages.
!
.severity fatal
WAITIDLEBCB	<attempted wait on idle buffer>
BUFFERSLOST	<all buffers are lost>
FREEBADBUFF	<attempted to free busy (or free) buffer>
ACTIVEBCB	<buffer active during reel switch>
!
! Command parser messages.
!
.severity fatal
INVQUAVAL	<value '!AD' invalid for /!AS qualifier>/FAO=2
INVDEVTYP	<invalid backup device type !AS>/FAO=1
PARSE		<error opening !AS>/FAO=1
INCDEVLIS	<disk and tape devices mixed in list>
ONEF11OUT	<file-structured output must not be a list>
LISINPSAV	</LIST requires save set as input>
CMPOUTF11	</COMPARE requires save set as first input>
SAVSETNAM	<save set name must be in first list element>
ONEF11DEV	<both input and output must not be save sets>
ONEIMGDEV	</IMAGE input specification must not be a list>
ONEPHYDEV	</PHYSICAL specification must not be a list>
PHYFILSPE	</PHYSICAL specification must have only device name>
IMGFILSPE	</IMAGE specification must have only device name>
INCFILSPE	</INCREMENTAL specification must have only device name>
MOUNTF11	<!AS must be mounted Files-11>/FAO=1
MOUNTFOR	<!AS must be mounted foreign>/FAO=1
CONFQUAL	<conflicting qualifiers>
!
! Fatal errors
!
.severity fatal
NOTANSI		<tape is not valid ANSI format>
NOTSAVESET	<!AS is not a BACKUP save set>/FAO=1
LABELERR	<error in tape label processing on !AS>/FAO=1
POSITERR	<error positioning !AS>/FAO=1
GETCHN		<error getting device characteristics for !AS>/FAO=1
CONTINUED	<!AS contains a continued file - cannot append>/FAO=1
TAPEFULL	<!AS is full>/FAO=1
WRONGVOL	<!AS is not the next volume in the set>/FAO=1
BADBLKSIZE	<!AS has inconsistent block size>/FAO=1
PHYSET		<physical save set supplied to nonphysical operation>
NONPHYSET	<nonphysical save set supplied to physical operation>
PHYDEVGEO	<device type of !AS does not match input>/FAO=1
ALLOCMEM	<error allocating virtual memory>
FREEMEM		<error freeing virtual memory>
OPERFAIL	<error requesting operator service>
NOTJOURNAL	<!AS is not a BACKUP journal>/FAO=1
INVBJLSTR	<invalid structure level in BACKUP journal>
INVBJLSIZ	<invalid record size in BACKUP journal>
INVBJLTYP	<invalid record type in BACKUP journal>
INVBJLEOF	<invalid end of file position in BACKUP journal>
ABORT		<operator requested abort on fatal error>
READERRS	<excessive error rate reading !AS>/FAO=1
WRITERRS	<excessive error rate writing !AS>/FAO=1
FATALERR	<fatal error on !AS>/FAO=1
SSCHANGE	<unexpected end of save set on !AS>/FAO=1
!
! File scan errors.
!
.severity fatal
MAXVOLS		<too many volumes in volume set !AS>/FAO=1
PROCINDEX	<error processing index file on !AS, RVN !UL>/FAO=2
NOSUCHRVN	</VOLUME=!UL invalid, volume set contains !UL volumes>/FAO=2
.severity error
OPENDIR		<error opening directory !AS[!AC]>/FAO=2
READDIR		<error reading directory !AS[!AC]>/FAO=2
BADDIR		<directory !AS[!AC] has invalid format>/FAO=2
!
! General non-fatal errors
!
.severity error
BADBLOCK	<bad blocks on !AS do not match input>/FAO=1
CREDIRERR	<error creating directory !AS>/FAO=1
INVHOMBLK	<!AS has invalid home block>/FAO=1
INVRECSIZ	<invalid record size in save set>
INVRECTYP	<invalid record type in save set>
INVATTSTR	<invalid attribute record structure level in save set>
INVATTSIZ	<invalid attribute record size in save set>
VBNMISSING	<!AS has missing blocks !UL through !UL>/FAO=3
VBNERROR	<!AS has duplicate blocks !UL through !UL>/FAO=3
VBNPASTEOF	<!AS has blocks !UL through !UL past end of file>/FAO=3
FIDERROR	<unexpected file change in !AS>/FAO=1
READATTR	<error reading attributes for !AS>/FAO=1
WRITEATTR	<error writing attributes for !AS>/FAO=1
READBLOCK	<error reading block !UL of !AS>/FAO=2
WRITEBLOCK	<error writing block !UL of !AS>/FAO=2
BADDATA		<error in block !UL of !AS detected during save>/FAO=2
VERIFYERR	<verification error for block !UL of !AS>/FAO=2
EOFMISMATCH	<end of file position mismatch for !AS>/FAO=1
DENSITY		<!AS does not support specified density - default used>/FAO=1
SHORTBLOCK	<save set block too short>
BLOCKCRC	<software block CRC error>
HDRCRC		<software header CRC error>
BLOCKLOST	<block of !AS lost due to unrecoverable error>/FAO=1
POSERROR	<error positioning !AS>/FAO=1
NOTBKBLOCK	<invalid subsystem code in save set>
INVBLKHDR	<invalid block header in save set>
INVSTRUCT	<invalid structure level in save set>
INVBLKSIZE	<invalid block size in save set>
CONTINUE	<unable to continue processing !AS>/FAO=1
WRITEBACK	<error writing backup date for !AS file ID (!UL,!UL,!UL)>/FAO=4
DELETE		<error deleting !AS file ID (!UL,!UL,!UL)>/FAO=4
INCDELERR	<error deleting !AS>/FAO=1
INCENTERR	<error creating directory entry for !AS>/FAO=1
INCBADDIR	<saved directory !AS has invalid format>/FAO=1
!
! Bad block messages
!
.severity error
READBAD		<error reading bad block data on !AS>/FAO=1
DIAGPACK	<!AS is a diagnostic pack>/FAO=1
FACTBAD		<cannot read factory bad block data on !AS>/FAO=1
MAXBAD		<bad block table overflow for !AS>/FAO=1
NOBADDATA	<bad block data not found on !AS>/FAO=1
!
! Standalone ACP messages
!
.severity fatal
ALLOCFAIL	<file structure allocation failure for !AS>/FAO=1
BADSETCNT	<incorrect number of devices in output specification>
CLUSTER		<unsuitable cluster factor for !AS>/FAO=1
DISKFRAG	<free space on !AS is too fragmented>/FAO=1
INCRVN		<incorrect relative volume mounted on !AS>/FAO=1
INCSETCNT	<incorrect number of devices in input specification>
INVATTVAL	<invalid attribute record value in save set>
INVFILEXT	<invalid file extension linkage in !AS>/FAO=1
LARGECNT	<!AS is too large to be processed>/FAO=1
NOHOMEBLK	<no valid home block found on !AS>/FAO=1
NOBITMAP	<no valid storage bitmap found on !AS>/FAO=1
NOINDEXF	<no valid index file header found on !AS>/FAO=1
NOVOLDATA	<volume summary data for !AS not found - /IMAGE cannot be used>/FAO=1
ODS2SAVE	<save set disk on !AS must be structure level 2>/FAO=1
READBMAP	<error reading storage bitmap on !AS>/FAO=1
READIMAP	<error reading index file bitmap on !AS>/FAO=1
SAVSETCLU	<save set disk cluster factor must be 1>
STRUCLEV	<inconsistent structure level on !AS>/FAO=1
VOLINSET	<!AS is already part of a volume set>/FAO=1
.severity error
QUOTAFILE	<quota file is too small - use DISKQUOTA to rebuild>
!
! Warning messages
!
.severity warning
BLKZERO		<block zero of !AS is bad - volume not bootable>/FAO=1
NOT1STVOL	<!AS is not the start of a save set>/FAO=1
NOFILES		<no files selected from !AS>/FAO=1
NONCONTIG	<!AS is not contiguous due to insufficient contiguous space>/FAO=1
ACCONFLICT	<!AS is open for write by another user>/FAO=1
!
! Informational messages
!
.severity informational
SOFTRERRS	<!UL recoverable media error!%S occurred reading !AS>/FAO=2
SOFTWERRS	<!UL recoverable media error!%S occurred writing !AS>/FAO=2
XORERRS		<!UL error!%S recovered by redundancy group in !AS>/FAO=2
STARTVERIFY	<starting verification pass>
STARTRECORD	<starting backup date recording pass>
STARTDELETE	<starting file deletion pass>
RESUME		<resuming operation on volume !UL>/FAO=1
READYREAD	<mount volume !UL on !AD: for reading!/Press return when ready: >/FAO=3
READYWRITE	<mount volume !UL on !AD: for writing!/Press return when ready: >/FAO=3
WRITENABLE	<write enable volume !UL on !AD:!/Press return when ready: >/FAO=3
SPECIFY		"specify option (QUIT!AC)!/BACKUP> "/FAO=1
JOURNAL		<journalling to !AS>/FAO=1
!
! Success reports
!
.severity success
COMPARED	<compared !AS>/FAO=1
COPIED		<copied !AS>/FAO=1
CREATED		<created !AS>/FAO=1
CREDIR		<created directory !AS>/FAO=1
INCDELETE	<deleted !AS>/FAO=1
.end
