!---
!
!	Error messages for the command language editor
!
! IDENT V02-004
!
!---

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:  Command language editor
!
! ABSTRACT:
!
!	These are the error messages used by the command language editor
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, unprivileged user mode utility,
!	operates at non-AST level.
!
! AUTHOR:  Tim Halvorsen,  Feb 1980
!
! MODIFIED BY:
!
!	V004	DWT0008		David W. Thiel	8-Dec-1981
!		Add "parameter Pn missing" error.
!
!	V003	BLS0089		Benn Schreiber	16-Oct-1981
!		Add /cli qualifier value conflicts with cli type in tables
!
!	V002	TMH0002		Tim Halvorsen	20-Nov-1980
!		Add "too many entities defined in mutual exclusion lists".
!
!	V001	TMH0001		Tim Halvorsen	13-Nov-1980
!		Remove label missing on parameter message since that
!		checking is no longer done.
!----

.FACILITY	CLEDIT,155 /SYSTEM /PREFIX=MSG$_

.SEVERITY	ERROR

SYMTOOLNG	<string too long>
MISSNGSYM	<missing argument>
BADVALUE	<illegal qualifier value>
BADPNAME	<illegal parameter name, must be P1 through P8>
CLIQUAL		</CLI qualifier value conflicts with CLI type in tables>
DUPSYM		<"!AS" is a duplicate symbol definition>/fao=1
LISTNOTFND	<attribute name not previously defined>
MULTCHNG	<attribute cannot be specified twice>
NOPROMPT	<required prompt missing from definition>
NOROOM		<not enough room in command tables>
NOVERBS		<verb table full>
TOOMNYGST	<number of symbol records exceeds count in image header>
TOOMNYINP	<too many inputs defined>
TOOMNYOUT	<too many outputs defined>
TOOMNYMOD	<too many modifiers defined>
GRPTOOBIG	<too many entities defined in mutual exclusion lists>
CONFATTR	<conflicting attributes in definition>
VERBNOTFND	<verb '!AS' not found in command tables>/FAO=1
BADIONAME	<'!AS' has not been previously defined>/FAO=1
NOINPTAB	<new tables file cannot be written unless input tables supplied>
EMPTYDEF	<no attributes supplied - DEFINE ignored>
NOSUCHRTN	<unknown CLI routine "!AS">/FAO=1
MISSNGPARM	<missing parameter "P!1ZL">/FAO=1

.SEVERITY	INFORMATIONAL

NOMODS		<no modifications made>

.SEVERITY	FATAL

IMAGEFMT	<command tables image has illegal format>
BADSTRLVL	<structure level in command tables not recognized>

.END
