!---
!
!	Error messages for LOGINOUT
!
! IDENT V02-003
!
!---

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:  LOGINOUT
!
! ABSTRACT:
!
!	These are the error messages used by the LOGINOUT program.
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, privileged utility.
!
! AUTHOR:  Tim Halvorsen,  March 1981
!
! MODIFIED BY:
!
!	V02-003	HRJ0036		Herb Jacobs		08-Dec-1981
!		Added more messages for terminal type restrictions.
!
!	V02-002	HRJ0031		Herb Jacobs		02-Nov-1981
!		Add messages for time of day and user account restrictions.
!
!	V001	TMH0001		Tim Halvorsen	22-Oct-1981
!		Add error message for captive accounts
!		Change to use system-wide facility number.
!----

.FACILITY	LOGIN,211 /SYSTEM /PREFIX=LGI$_

.SEVERITY	FATAL			! Default severity is fatal

jbcmixup	"fatal job controller interaction problem"
logdisabl	"logins are currently disabled - try again later"
exquota		"maximum number of users exceeded - try again later"
clifail		"error activating command interpreter !AS"/FAO=1
cliprot		"error protecting command interpreter pages"
clisymtbl	"error creating space for command interpreter symbol table"
notvalid	"user authorization failure"
fileacc		"error accessing system authorization file"
userauth	"error accessing authorization record"
inputerr	"error opening primary input file SYS$INPUT"
outputerr	"error opening primary output file SYS$OUTPUT"
cmdinput	"error reading command input"
openin		"error opening !AS as input"/FAO=1 /WARNING
captive		"qualifier not allowed in captive accounts"
badhour		"you are not authorized to login at this time"
userexc		"you are at maximum allowed processes for your user name"
acntexc		"you are at maximum allowed processes for your account name"
nodialin	"you are not authorized to login on a dial in line today"
noremote	"you are not authorized to login via set host today"

.END
