!
! IMAGE FILE PATCH UTILITY MESSAGES AND LITERALS
!
!	Version 'V03-001'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! MODIFIED BY:
!
!	V03-001	MTR0005		Mike Rhodes		25-Mar-1982
!		Upgrade the MISSQUO message to reflect its true action.
!
!	V02-005	MTR0001		Mike Rhodes		01-Oct-1981
!		Add two informational messages for the /INITIALIZE qualifier
!		to the SET PATCH_AREA command.  BADINITSZ and PREVINIT.
!
!	V02-004	KDM0027		Kathleen D. Morse	04-Dec-1980
!		Change ECOSET and ECONOTSET to be informational messages.
!

!
! INFORMATIONAL MESSAGES	(SEVERITY LEVEL 3)
!

	.FACILITY	PATCH,109 /SYSTEM /PREFIX=PAT$_ /MACRO=$PATMSG
	.SEVERITY	INFORMATIONAL
	.BASE		0

	LONGDST		<unable to include all module names in symbol table>
	MODNOTADD	<insufficient symbol table space to add module '!AC'> /FAO=1
	NOTALLSYM	<unable to initialize symbols for default modules>
	NOUPDATE	<no patch for update qualifier eco level !ZB> /FAO=1
	NUMTRUNC	<number truncated>
	REDEFSYM	<redefining symbol !AD from !XL to !XL> /FAO=4
	STGTRUNC	<string truncated>
	UPDATE		<patch with eco level !ZB ignored due to update qualifier> /FAO=1
	ECONOTSET	<eco level !ZL not set in !AD> /FAO=3
	ECOSET		<eco level !ZL already set in !AD> /FAO=3
	BADINITSZ	<illegal size value, defaulting patch size to !XL bytes>/FAO=1
	PREVINIT	<patch area has previously been initialized>

!
! WARNING MESSAGES	(SEVERITY LEVEL 0)
!


	.SEVERITY	WARNING

	BADCSP		<scope setting not module or routine>
	GBLONLY		<cannot obtain global copy of image section "!AC"> /FAO=1
	GBLWARN		<patching local copy of global image section "!AC"> /FAO=1
	NORSTBLD	<cannot build symbol table>
	NOSUCHMODU	<no such module name '!AC'> /FAO=1
	NOSUCHSYM	<no such symbol>
	NOSYMBOL	<no such symbol '!AC'> /FAO=1

!
! SEVERE ERRORS	(SEVERITY LEVEL 2)
!


	.SEVERITY	ERROR

	BADECO		<illegal eco level of !ZL in !AD> /FAO=3
	EXARANGE	<invalid range of addresses>
	FRERANGE	<storage package range error>
	FRESIZE		<storage package size error>
	INSUFPAT	<!UL bytes requested, patch area at !XL contains !UL bytes> /FAO=3
	INVARRDSC	<invalid array descriptor>
	INVCHAR		<invalid character>
	INVCMD		<invalid command>
	INVDSTREC	<invalid DST record>
	INVNUMBER	<invalid numeric string>
	MULTECO		<multiple eco levels (!UB and !UB) set for one patch> /FAO=2
	NOACCESS	<cannot access image section>
	NODECODE	<cannot decode instruction>
	NOENCODE	<cannot encode instruction "!AC"> /FAO=1
	NOFREE		<no free storage available>
	NOPATAREA	<insufficient patch area at !XL, size=!ZL> /FAO=2
	NOTPATADR	<patch address is !XL not !XL> /FAO=2
	NSADDR		<address !XL is not within image> /FAO=1
	OLDINSCHK	<memory location !XL not equal to "!AC"> /FAO=2
	OLDVALCHK	<memory location !XL not equal to !XL> /FAO=2
	PARSEERR	<internal parsing error>
	PATERR		<internal patch coding error>
	PATHTLONG	<too many qualifiers on name>
	REPLACEERR	<replacement value too large for location>

!
! FATAL ERRORS	(SEVERITY LEVEL 4)
!


	.SEVERITY	FATAL

	BADIDENT	<unable to patch image with ident of !AD> /FAO=2
	CLIERR		<cli error parsing command line>
	CLSERR		<close error code of !XL on file !AD> /FAO=3
	CNTERR		<connect error code of !XL on file !AD> /FAO=3
	CRMPSC		<error code of !XL mapping section> /FAO=1
	DELTVA		<error code of !XL deleting !XL to !XL> /FAO=3
	ENDPRS		<error code of !XL on command line parse end> /FAO=1
	EXPREG		<error code of !XL expanding program region> /FAO=1
	GETERR		<read error code of !XL on file !AD> /FAO=3
	GETTIM		<error code of !XL on $GETTIM> /FAO=1
	HDRBLK		<too many isd's for image header blocks>
	INITPRS		<error code of !XL on command line parse init> /FAO=1
	JNLPUT		<error writing to journal file>
	MEMBUG		<dynmem error  size=!XL addr=!XL error=!XL> /FAO=3
	MODIFYERR	<modify error code of !XL on file !AD> /FAO=3
	NUMVAL		<error code of !XL requesting update value> /FAO=1
	OPNERR		<open error code of !XL on file !AD> /FAO=3
	PRIMIN		<error code of !XL parsing input file> /FAO=1
	PRIMOUT		<error code of !XL parsing output file> /FAO=1
	PUTERR		<put error code of !XL on file !AD> /FAO=3
	SECOUT		<error code of !XL parsing journal file> /FAO=1
	TEROUT		<error code of !XL parsing command file> /FAO=1

!
! NEW MESSAGES WITH NO SEVERITY LEVELS BUILT IN.
!


	.SEVERITY	WARNING

	NOLCL		<image does not contain local symbols>
	NOGBL		<some or all global symbols not accessible>
	MULTOPR		<multiple successive operators in expression>
	EXPSTKOVR	<expression too nested, stack overflow>
	NOANGLE		<unmatched angle brackets in expression>
	NOOPRND		<missing operand in expression>
	INVOPR		<unrecognized operator in expression>
	INVPATH		<invalid pathname started by !AS> /FAO=1
	BADOPCODE	<opcode '!AD' is unrecognized> /FAO=2
	RESOPCODE	<opcode '!AD' is reserved> /FAO=2
	OPSYNTAX	<instruction operand syntax error>
	BRTOOFAR	<destination !XL is too far for branch operand> /FAO=1
	NOBRANCH	<instruction requires branch-type operand>
	NUMOPRNDS	<'!AC' instructions must have !SL operands> /FAO=2
	NOTDONE		<!AC not yet a supported feature> /FAO=1
	INVIMGHDR	<inconsistent debug and symbol data in image header>
	DIVZERO		<attempt to divide by zero>
	EXTBIT		<illegal extract bit number - greater than 31>
	INVQUO		<quoted argument not allowed in current mode>
	NOTQUO		<unquoted argument not allowed in ASCII or INSTRUCTION modes>
	MISSQUO		<unmatched quotation marks in argument, closing quote assumed>
	INVTOKEN	<unrecognized token '!AS'> /FAO=1
	INVOPRND	<unable to resolve operand '!AD'> /FAO=2
	INSOPRND	<missing instruction operand>
	OUTCMDLNG	<output command line too long for buffer>
	DIFVAL		<memory contains different value than specified>
	OPRNDLNG	<operand "!AD!AD" too long for internal buffers> /FAO=4
	NONCONTIG	<non-contiguous image file being written>
	SYNTAX		<command syntax error at or near '!AS'> /FAO=1
	DUPCOMFIL	<command file '!AD' already being written> /FAO=2
	NOLITERAL	<no LITERAL translation exists for !XL> /FAO=1
	WRTFIL		<updating image file !AD> /FAO=2
	NORELOC		<relocation of CASE instructions not supported>
	EXPSHRPAT	<attempt to expand patch area for shareable image>

	.END
