.TITLE		FDLMSG		VAX-11 FDL Utilities Error Messages	V03-001

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982 BY					    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! Facility:	VAX-11 FDL Utilities
!
! Environment:
!
!		VAX/VMS Operating System
!
! Abstract:
!		FDL error messages
!
!
!--

!
! Author:	Keith B Thompson	Creation date:	August-1980
!
!
! Modified by:
!
!	V03-001	KBT0033		Keith Thompson		31-Mar-1982
!		Add invdatim message
!
!****

.FACILITY	FDL,	 	180	/SYSTEM		/PREFIX=FDL$_

.LITERAL	FDL$_FAO_MAX = 5

.SEVERITY	INFO

TITLE		<empty ident or title>

.SEVERITY	WARNING

ABKW		<ambiguous key word on line !UL !/ \!AD\> /FAO=3
INVDATIM	<invalid date/time on line !UL> /FAO=1
MULSEC		<multiple secondary definition on line !UL> /FAO=1
NOQUAL		<no qualifier on line !UL> /FAO=1
NULLPRI		<null primary block>
RFLOC		<unable to locate related file>
VALPRI		<value required on primary on line !UL> /FAO=1
UNQUAKW		<unrecognized qualifier keyword on line !UL !/ \!AD\> /FAO=3
UNSECKW		<unrecognized secondary keyword on line !UL !/ \!AD\> /FAO=3
WARNING		<parsed with warnings>

.SEVERITY	ERROR

ABPRIKW		<ambiguous primary key word on line !UL !/ \!AD\> /FAO=3
CREATE		<error creating !AS> /FAO=1
FDLERROR	<error parsing FDL file>
ILL_ARG		<wrong number of arguments>
MULPRI		<multiple primary definition on line !UL> /FAO=1
OPENFDL		<error opening !AS> /FAO=1
OUTORDER	<key or area primary defined out of order on line !UL> /FAO=1
SYNTAX		<syntax error on line !UL !+ !+ !/ \!AD\> /FAO=5
UNPRIKW		<unrecognized primary keyword on line !UL !/ \!AD\> /FAO=3

.END
